manager/api/beans/src/main/java/io/apiman/manager/api/beans/apps/ApplicationVersionBean.java, manager/api/beans/src/main/java/io/apiman/manager/api/beans/audit/AuditEntryBean.java, manager/api/beans/src/main/java/io/apiman/manager/api/beans/contracts/ContractBean.java, manager/api/beans/src/main/java/io/apiman/manager/api/beans/idm/RoleMembershipBean.java, manager/api/beans/src/main/java/io/apiman/manager/api/beans/plans/PlanVersionBean.java, manager/api/beans/src/main/java/io/apiman/manager/api/beans/policies/PolicyBean.java, manager/api/beans/src/main/java/io/apiman/manager/api/beans/services/ServiceVersionBean.java
As the dialect can be configured as a system property (i.e. apiman.hibernate.dialect) there's no need to set the strategy
=> APIMAN-243

common/util/src/main/java/io/apiman/common/util/ReflectionUtils.java, gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/EngineImpl.java
As discussed, uses reflection to call an initialize if it's defined, rather than an explicit interface.
=> APIMAN-325 Add initialize method for metrics

gateway/engine/core/src/main/java/io/apiman/gateway/engine/components/IBufferFactoryComponent.java, gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/components/BufferFactoryComponentImpl.java, gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/io/ByteBuffer.java, gateway/platforms/vertx/src/main/java/io/apiman/gateway/vertx/components/BufferFactoryComponentImpl.java, gateway/platforms/vertx/src/main/java/io/apiman/gateway/vertx/io/VertxApimanBuffer.java
Thoughts:
- Should we have a create method that accepts byte[] *without* any copying the array (or perhaps this should be the default behaviour).
- Should we have a `relinquishBuffer`? Perhaps we can look at how Netty does its pooling/reuse. This is probably a strong candidate for reuse optimisations.
=> IBufferFactoryComponent Interface and implementations

gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/IServiceObjectBean.java, gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/ServiceRequest.java, gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/ServiceResponse.java, gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/GatewayServlet.java, gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/GatewayThreadContext.java, gateway/platforms/vertx/src/main/java/io/apiman/gateway/vertx/http/HttpGatewayStreamer.java, gateway/platforms/vertx/src/main/java/io/apiman/gateway/vertx/http/HttpServiceFactory.java
I've spent a long while today working through a few different implementations of how to represent transport security in apiman. Although the implementations are simple, there are a wide range of security implications we need to consider.
This is my preferred idea vs concept 1, and turns out to be simpler, I think, but has a few downsides which are worth considering. We will also need to extend this in some way to try and make sure that side-channels (like policies making requests) and connectors (i.e. backend connections) obey the same rules (or at least dire warnings that isn't really secure otherwise).
Essentially we simply encapsulate this logic into the request. 
Advantages:
- Encapsulates this into the request, keeps the implementation very simple
- This object is forwarded onto …
=> Idea for transport secure: Concept 2

manager/ui/apiman-plugin/plugins/apiman/html/org/apiman-user-entry.html, manager/ui/apiman-plugin/plugins/apiman/html/org/org-manage-members.html, manager/ui/apiman-plugin/plugins/apiman/html/org/org-new-member.html, manager/ui/apiman-plugin/plugins/apiman/ts/apimanPlugin.ts, manager/ui/apiman-plugin/plugins/apiman/ts/org/org-new-member.ts
it is now possible to add multiple members with the same roles in a single action. You click an entry to select and click again to deselect, as below: 
:see_no_evil:  Caveats:
- Made workaround for very annoying CSS issue where the search box is marginally larger than the search icon. It works fine by having a tiny inline CSS snippet, but really needs a better solution - suggest @EricWittmann looks at is as I don't want to meddle with his CSS too much (example without work-around below).
- There's a bug present in the old version that allows you to (attempt to) add users to an org who have already been added. I will put the PR for that separately.
=> Completed org-new-member port with all features, plus an enhancement

pom.xml
Note that 1 test fails under Java 8, but that's unrelated to this doclint fix.
Thanks to this SO thread: http://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete
=> Add profile to exclude doclint under java8

distro/wildfly8/src/main/resources/overlay/standalone/configuration/apiman.properties
This fixes the issue of config not reaching the factory, but there's a strange problem that's only exhibiting in manual testing that I haven't been able to get to the bottom of yet (see https://issues.jboss.org/browse/APIMAN-443)
=> Connector factory is a special case for its apiman.properties config paths

manager/ui/hawtio/index.html
Base tag specifies base URL for relative URLs.  Previous favicon was using a absolute URL.
=> APIMAN-455 Apiman favicon is now displaying

distro/db-es/src/test/java/io/apiman/distro/db/CreateESDatabaseTest.java, distro/db/src/test/java/io/apiman/distro/db/CreateH2DatabaseTest.java, test/common/src/main/java/io/apiman/test/common/util/TestUtil.java
In order to run project testsuite against APIMan instance with custom datasource the one has to populate the db. Thus we shoudl be also able to run these tests against external server.
=> Allowing test properties to be overridden from command line in distro/db and distro/db-es modules

gateway/platforms/war/wildfly8/api/pom.xml, gateway/platforms/war/wildfly8/gateway/pom.xml, manager/api/war/pom.xml, manager/api/war/wildfly8/pom.xml, manager/ui/hawtio/pom.xml, manager/ui/hawtio/wildfly8/pom.xml, tools/services/pom.xml
To aid in IDE/server integration, it is extremely helpful if projects that generate wars create war artifacts named to match the intended target context names.
=> APIMAN-480 Add <finalName> tag to all poms using war packaging

manager/api/beans/src/main/java/io/apiman/manager/api/beans/plugins/PluginBean.java
Inclusion of this sequence generation strategy is causing runtime problems within the application (when using PostgreSQL) and also during DDL generation for Oracle and perhaps other RDBMSs.  This is the only entity configured this way and all other entities are correctly getting generated ids from the configured hibernate_sequence.  Aligning PluginBean to match other entities within the project.
=> APIMAN-549 Remove sequence GenerationType.IDENTITY from PluginBean

distro/ddl/pom.xml
Removed the h2-update build step within the ddl project as it implicitly requires a clean before it will build properly.  This step is part of a work in progress and may be removed in the future, keeping it around until we complete the next phase of the liquibase work.
=> Remove ddl h2-update step as it's causing build issues

gateway/platforms/vertx3/pom.xml, gateway/test/pom.xml
I discovered some glitches, which I've managed to resolve (thanks StackOverflow!)
Essentially, I am now properly exporting the test classes from the vertx3 gateway, which ensure they're available on the classpath when you run `mvn clean test -Dapiman.gateway-test.config=vertx3-mem`. By default they're not available, so they may/may not be on the classpath.
Also ensure that a few other things are reliably on the classpath (in-memory). See: https://github.com/apiman/apiman/compare/apiman:master...msavy:8fixes?expand=1#diff-0bc78dba935aa46d68cf49b963ef5a65R135
I've double checked and tests on java8 for the vert.x 3 port are always passing now.
=> Ensure reliable testing under Java8

.travis.yml
At present, this is in-memory, vert.x in-memory & elasticsearch.
Added some retry logic which helps get around annoying transient issues and/or unusual timing problems with eventually consistent bits.
=> Use a build matrix to switch between different gateway permutations.

manager/test/api/src/main/java/io/apiman/manager/test/server/ManagerApiTestServer.java
Turning off multicast discovery as it causes issues when building the project on multiple servers inside local network. If there is a need for it to be enabled, then feel free to reject. Clustering of nodes running on the same machine should still work.
=> Disabled ES clustering over multicast in test server

.travis.yml
- Trim down redundant matrix entries (they are run by in the base install builds anyway)
- Add more log noise filtering
=> Trim down redundant matrix entries & noise reduction

.travis.yml
... as install takes easily long enough to allow ES service to start
Saves us a whopping 10 seconds ;-).
=> Don't need the sleep in travis-ci

distro/ddl/pom.xml, distro/ddl/src/main/liquibase/current/000-apiman-manager-api.db.sequences.changelog.xml, distro/ddl/src/main/liquibase/current/010-apiman-manager-api.db.tables.changelog.xml, distro/ddl/src/main/liquibase/master.xml, distro/pom.xml, pom.xml
Added distro/ddl to the apiman build process
Updated ddl SNAPSHOT version to match project -> 1.2.0-SNAPSHOT
Upgraded liquibase to version 3.4.1
Changed ddl generation goals to execute during maven compile phase
Added global property to master.xml to treat MySQL clob type as longtext
Synchronized the changelogs with the entity generated changelogs prior to manual updates
Keeping manual LONGBLOB update in the changelogs - will need to document this for future JPA @Lob columns
Added defaultSchemaName to PostgreSQL updateSql goal - see comments in pom
Successfully loaded MySQL DDL
Successfully loaded PostgreSQL DDL
=> APIMAN-556 Updates to correct liquibase DDL generation issues

README.md
Fixed a typo.  When referring to JDK, use correct JDK version numbering.
=> APIMAN-619 - Build settings for Java 7 and earlier clients

gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/ssl/SSLSessionStrategyFactory.java, manager/api/gateway/src/main/java/io/apiman/manager/api/gateway/rest/RestGatewayLink.java
Weld is still unhappy after this SSL stuff has been fixed
```
11:45:51,188  WARN FAILED o.e.j.s.ServletContextHandler@e4bd0f2{/apiman,null,STARTING}: java.lang.AbstractMethodError: org.jboss.weld.environment.jetty.WeldDecorator.decorate(Ljava/lang/Object;)Ljava/lang/Object;
java.lang.AbstractMethodError: org.jboss.weld.environment.jetty.WeldDecorator.decorate(Ljava/lang/Object;)Ljava/lang/Object;
at org.eclipse.jetty.servlet.ServletContextHandler$Context.createFilter(ServletContextHandler.java:1150)
at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:120)
at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:852)
at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
at …
```
=> Fix issues with SSL construction

gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/ESClientFactory.java, gateway/test/src/main/java/io/apiman/gateway/test/server/GatewayServer.java, manager/api/war/src/main/java/io/apiman/manager/api/war/WarApiManagerConfig.java, manager/api/war/src/main/java/io/apiman/manager/api/war/WarCdiFactory.java, manager/test/api/src/main/java/io/apiman/manager/test/server/ManagerApiTestServer.java, manager/test/api/src/main/java/io/apiman/manager/test/server/TestCdiFactory.java, manager/test/api/src/test/java/io/apiman/manager/test/es/ESMetricsAccessorTest.java
Not sure whether this was worth adding as an extra config option in various places, so I just hard-coded a larger default in those areas.
Where it was easy I added an extra option to make it configurable (EsClientFactory).
Before merging it might be worth putting this one through CI a few times to see whether it trips anymore.
=> Add timeout option for jest client, and double default T/O in many places - useful in CI scenarios

manager/ui/hawtio/plugins/api-manager/html/forms/edit-policy.html, manager/ui/hawtio/plugins/api-manager/html/policyForms/Default.include, manager/ui/hawtio/plugins/api-manager/html/policyForms/authorization.include, manager/ui/hawtio/plugins/api-manager/html/policyForms/basic-auth.include, manager/ui/hawtio/plugins/api-manager/html/policyForms/caching.include, manager/ui/hawtio/plugins/api-manager/html/policyForms/ignored-resources.include, manager/ui/hawtio/plugins/api-manager/html/policyForms/ip-list.include, manager/ui/hawtio/plugins/api-manager/html/policyForms/quota.include, manager/ui/hawtio/plugins/api-manager/html/policyForms/rate-limiting.include, manager/ui/hawtio/plugins/api-manager/html/policyForms/transfer-quota.include, manager/ui/hawtio/plugins/api-manager/html/policyForms/url-rewriting.include, manager/ui/hawtio/plugins/api-manager/html/service/service-def.html, manager/ui/hawtio/plugins/api-manager/html/service/service-endpoint.html, manager/ui/hawtio/plugins/api-manager/html/service/service-impl.html, manager/ui/hawtio/plugins/api-manager/html/service/service-plans.html, manager/ui/hawtio/plugins/api-manager/html/service/service-policies.html, manager/ui/hawtio/plugins/api-manager/ts/apimanPlugin.ts, manager/ui/hawtio/plugins/api-manager/ts/directives.ts, manager/ui/hawtio/plugins/api-manager/ts/forms/edit-policy.ts, manager/ui/hawtio/plugins/api-manager/ts/policies.ts, manager/ui/hawtio/plugins/api-manager/ts/service/service-activity.ts, manager/ui/hawtio/plugins/api-manager/ts/service/service-contracts.ts, manager/ui/hawtio/plugins/api-manager/ts/service/service-def.ts, manager/ui/hawtio/plugins/api-manager/ts/service/service-endpoint.ts, manager/ui/hawtio/plugins/api-manager/ts/service/service-impl.ts, manager/ui/hawtio/plugins/api-manager/ts/service/service-plans.ts, manager/ui/hawtio/plugins/api-manager/ts/service/service-policies.ts, manager/ui/hawtio/plugins/api-manager/ts/service/service.ts
Changes:
- Added public method to policies file (parent controller), to allow check for entity status.
- Added `ng-disabled` directive to each field for each service tab, if said check returns a status other than 'Ready'.
- To handle custom forms, which are currently generated with JSON-Editor: Added a few statements to the `JsonSchemaPolicyConfigFormController`, which checks the entity status and disables the entire custom form if the status is anything other than 'Ready'. In the future, we can disable individual fields, but for the moment it seems to be a little bit more trouble than it's worth, so, for now, disabling the entire form seems to be the way to go.
Reference
- ["Page is dirty" warning sometimes happen when the page isn't dirty](https://issues.jboss.org/browse/APIMAN-714)
- …
=> re #714 #485 Disable Fields if Service is Published

manager/ui/pom.xml
This is the small tweak that makes it get past the previous build issue we discussed.
Now hitting issues with NPM deps and TS compilation errors, but think that's a separate concern.
=> Make sure WF8 UI is built

gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/CachingESRegistry.java, gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/ESRegistry.java, manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/OrganizationResourceImpl.java
Changes:
- For each method that involves parsing data for metrics (located in the `OrganizationResourceImpl` class), add a check for existence of `fromDate` to `toDate`, and throw `invalidMetricCriteriaException` error if either doesn't exist.
- Make `getApplicationId` method public in `CachingESRegistry` class.
- Change call from `getApplicationKey` to `getApplicationId` in the `loadAndCacheApp` method within the `CachingESRegistry` class.
JIRA: https://issues.jboss.org/browse/APIMAN-711
cc @EricWittmann @msavy
=> re #711 Add invalidMetricCriteriaException for Metrics Endpoints

manager/ui/hawtio/plugins/api-manager/html/app/apiModal.html, manager/ui/hawtio/plugins/api-manager/html/app/app-apis.html
Changes:
- Re-added CSS styling to read-only fields that remove the disabled styling appearance.
JIRA: https://issues.jboss.org/browse/APIMAN-768
=> re #768 Remove disable styling from read-only fields

gateway/engine/core/src/main/java/io/apiman/gateway/engine/components/jdbc/IJdbcConnection.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/components/jdbc/VertxJdbcConnection.java, gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/components/jdbc/suitetests/ExecuteTest.java
So, my solution here allows things to done cleanly with PreparedStatement under the covers - however, as you rightly pointed out the `execute` method doesn't have parameters for some reason. I've worked around that by actually executing a `updateWithParams`.
I'll make a PR upstream to see if they'll accept an addition of `executeWithParams`. Should be easy :).
=> vertx with query params

manager/ui/hawtio/plugins/api-manager/html/service/service-impl.html, manager/ui/hawtio/plugins/api-manager/ts/app/app-apis.ts, manager/ui/hawtio/plugins/api-manager/ts/directives.ts, manager/ui/hawtio/plugins/api-manager/ts/service/service-impl.ts
Changes:
Added a function that is called when the form is submitted. The function, using Regex, checks the first 7 characters of the endpoint to see if it contains `http://`. If it does, then the `saveService()` method is called. If it doesn't, it will then check to see if the first 8 characters of the endpoint contains `https://`. If it does, then the `saveService()` method is called. If that fails, then the user will see an error that reads `Please ender a valid endpoint that begins with http:// or https://.`. See screenshot below:
I also moved the `apimanApiModal` directive to the directives file, because it was really confusing to have it hidden at the bottom of a controller file.
JIRA: https://issues.jboss.org/browse/APIMAN-790
=> re #790 FE Endpoint Validation

manager/ui/hawtio/plugins/api-manager/html/api/api_entity.include, manager/ui/hawtio/plugins/api-manager/ts/api/api.ts
Changes:
- Added a close icon to the top right hand corner of the 'Why Can't I Publish?' checklist popover. Clicking the icon results in a closed popover.
- Needed to re-add the ability to toggle the popover by clicking on the same 'Why Can't I Publish?' button that opens the popover. Added a check in the controller for this.
JIRA: https://issues.jboss.org/browse/APIMAN-826
Screenshot:
=> re #826 Add ability to dismiss popover with close button

manager/ui/hawtio/plugins/api-manager/html/api/api-impl.html, manager/ui/hawtio/plugins/api-manager/ts/api/api-impl.ts
Fixes a bug where the save button remains disabled on second change for the Implementation tab.
JIRA: https://issues.jboss.org/browse/APIMAN-860
=> re #860 Fix for save button remaining disabled

manager/ui/hawtio/plugins/api-manager/html/api/api-def.html
Since this is a blocking issue I just decided to revert the addition of UI-Select for this page.
I may be getting a little overeager here in trying to switch to UI-Select, but as I'm diving in, this switch is more problematic for some views than others. It seems like there are many `$watch`'s that are also integrated with other functionality, such as dirty checking and sometimes state setting.
While I'd prefer to have a cleaner implementation of these features, I know it's certainly not ideal nor efficient to rewrite these on the go, especially without testing in place. I think we should still switch to UI-Select, but it may be a while before we can transition completely.
JIRA: https://issues.jboss.org/browse/APIMAN-861
=> #861 Fix for inability to save API definition

gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/InMemoryCacheStoreComponent.java
The cache expiry logic in `InMemoryCacheStoreComponent.get()` is incorrect. Instead of checking that the expiry is in the past (as it does within the `getBinary()` method), it checks whether it is in the future.
This results in all cache entries retrieved via the `get()` method being considered immediately 'expired' and being removed from the cache.
This PR modifies the logic in `get()` to match that of `getBinary()` to fix the behaviour.
=> Fixes inverted cache expiry logic.

test/policies/src/main/java/io/apiman/test/policies/Configuration.java, test/policies/src/main/java/io/apiman/test/policies/PolicyTester.java
Allows the developer to specify the test policy configuration as a file on the classpath, rather than inline in the `@Configuration` annotation. An example would be to hold test policy configurations in the `src/test/resources` folder in the plugin project.
Specifying all but trivial configuration in policy tests as a string can make the configuration values difficult to read and maintain. This is because policy configuration is often held in JSON format, requiring escaping of the string. Example:
```java
private static final String PASSTHROUGH_CONFIG = "{\"cookieName\":\"XSESSION\",\"cookiePath\":\"/\",\"invalidateSession\":true,\"responseBehaviour\":\"PassThrough\",\"skipBackendCall\":false}";
@Test
@Configuration(PASSTHROUGH_CONFIG)
@BackEndService(EchoBackEndService.class)
public void …
```
=> Specify test policy configuration as a file on the classpath

gateway/platforms/war/standalone/api/pom.xml, gateway/platforms/war/standalone/common/pom.xml, gateway/platforms/war/standalone/es/pom.xml, gateway/platforms/war/standalone/gateway/pom.xml, gateway/platforms/war/standalone/pom.xml
In the `1.1.x` branch, the POM versions for the standalone WARs are currently 1.1.9-Final, whereas in the rest of the POMs in the branch they are `1.1.10-SNAPSHOT`.
=> Updates POM versions for standalone WARs to 1.1.10-SNAPSHOT.

distro/data/src/main/resources/data/apiman-realm.json
This change should allow newer versions of KC to work with our deployment guide, and doesn't break with our shipping version of KC.
I've tested it several times, and it all seems to work fine, but would appreciate @EricWittmann and @kahboom testing it to see if you can break it (delete your existing apiman realm in KC and import this one).
One item of discussion is the fact that the KC import/export format of the version we share in our developer's guide is actually [very different to the one which ship with](https://gist.github.com/msavy/4c94bd70483a814c7a32) - however it still works (for now).  I suggest we update it once we move to the new version of KC. I'll make a JIRA ticket for that.
=> Set direct access grants only for apiman-gateway-api

common/util/src/main/java/io/apiman/common/util/ApimanStrLookup.java, distro/wildfly9/src/main/resources/overlay/standalone/configuration/themes/apiman/login/resources/css/login.css, manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/ActionResourceImpl.java, manager/ui/hawtio/plugins/api-manager/html/api/api_entity.include, manager/ui/hawtio/plugins/api-manager/html/client/client_entity.include, manager/ui/hawtio/plugins/api-manager/ts/api/api.ts, manager/ui/hawtio/plugins/api-manager/ts/client/client.ts, manager/ui/hawtio/plugins/api-manager/ts/directives.ts
The re-register and re-publish buttons had some display issues which are now fixed.
Also re-registering a client app after breaking all its contracts wasn't properly working.  It has been fixed by trying to retire the client when it has no more contracts.
=> Re-register/publish fixes

manager/ui/hawtio/plugins/api-manager/ts/forms/edit-gateway.ts, manager/ui/hawtio/plugins/api-manager/ts/forms/new-gateway.ts, manager/ui/hawtio/plugins/api-manager/ts/rpc.ts
Changes:
- Add regex check for JSON key `password` in all responses that result in an error when testing a new or existing gateway.
JIRA: https://issues.jboss.org/browse/APIMAN-876
Notes:
We need to make some big improvements here. The regex is only checking for JSON, not accounting for the fact that users can configure their policies to return a response in XML or YAML. We need to support these as well.
In addition, the check is only done for the Edit Gateway and New Gateway views, and in their respective controllers. This check should be done at the service level for all failed requests. The regex check was returning the original error before the formatted error and was causing some issues from within the service, so it had to be moved to the controller for now. I was able to do this …
=> re #876 Login Failure

manager/ui/hawtio/plugins/api-manager/html/api/api_entity.include
Changed cursor on the "Why can't I publish?" popover close button to `pointer` instead of `default`.
JIRA: https://issues.jboss.org/browse/APIMAN-864
=> re #864 Change cursor to pointer instead of default

manager/api/beans/src/main/java/io/apiman/manager/api/beans/contracts/NewContractBean.java, manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/OrganizationResourceImpl.java, manager/test/api/src/test/resources/test-plan-data/contracts/contracts/003_create-contract1.resttest, manager/test/api/src/test/resources/test-plans/contracts-testPlan.xml
Hi Eric, 
i've extended the Apiman REST call which creates a contract. Now it also takes an optional parameter which allows the creation of a contract with custom "apiKey". I thought it would also be useful to others. 
I've installed the code formatter but intelliJ had an opinion of its own, so you will see come commits reverting the file and manually apply the changes.
I've also extended a current test *.resttet to test this.
Maybe it would be work having a small section on the README, specifying how the test works, it took me a while to figure it out. (especially the resttest). 
Thanks
Andrea
=> Feature: When creating a contract with a custom "apiKey" so we can override original key generation.

pom.xml
Upgrade to latest version as internal builds need the ability to set `npmRegistryURL` which is only available in >= 0.27.
=> Upgrade frontend plugin to 0.27

common/config/src/main/java/io/apiman/common/config/options/HttpConnectorOptions.java, distro/wildfly8/src/main/resources/overlay/standalone/configuration/apiman.properties, distro/wildfly9/src/main/resources/overlay/standalone/configuration/apiman.properties, gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/HttpConnectorFactory.java, gateway/platforms/war/micro/src/main/java/io/apiman/gateway/platforms/war/micro/GatewayMicroService.java, gateway/platforms/war/standalone/common/src/main/resources/apiman.properties
Adds the ability to control whether the gateway automatically follows redirects (301, 302 etc.) from the back-end service.
Prior to this change, the redirect behaviour of the gateway was the OkHttp default of 'follow redirects'. This can lead to some unexpected behaviour when back-end services return a redirect status code intended for the *client*, not the gateway.
The default setting (and the behaviour today) results in the gateway attempting to load the URL to which the client should be redirected, rather than passing through the 301/302 to the client. This change makes that behaviour configurable.
* A new property has been added to `HttpConnectorOptions`.
* The `HttpConnectorFactory` applies the redirect property to the OkHttpClient.
* The default value for redirects has been set to …
=> Configurable redirect follow behaviour for gateway

common/config/src/main/java/io/apiman/common/config/options/AbstractOptions.java, common/config/src/main/java/io/apiman/common/config/options/ConnectionOptions.java, distro/wildfly8/src/main/resources/overlay/standalone/configuration/apiman.properties, gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/HttpConnectorFactory.java, gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/HttpServiceConnection.java, gateway/platforms/war/standalone/common/src/main/resources/apiman.properties
* Adds the ability to control whether the gateway automatically follows redirects (301, 302 etc.) from the back-end service.
* Adds the ability to set the read timeout and connect timeout values for the service connection.
Prior to this change, the redirect behaviour of the gateway was the OkHttp default of 'follow redirects'. This can lead to some unexpected behaviour when back-end services return a redirect status code intended for the *client*, not the gateway.
The default setting (and the behaviour today) results in the gateway attempting to load the URL to which the client should be redirected, rather than passing through the 301/302 to the client. This change makes that behaviour configurable.
* A new `ConnectionOptions` class has been added that is fed by the engine configuration. …
=> Configurable connection options (timeouts, redirects) for service connector in 1.1.x

.gitignore, gateway/engine/policies/src/main/java/io/apiman/gateway/engine/policies/IgnoredResourcesPolicy.java, gateway/engine/policies/src/main/java/io/apiman/gateway/engine/policies/config/IgnoredResource.java, gateway/engine/policies/src/main/java/io/apiman/gateway/engine/policies/config/IgnoredResourcesConfig.java, gateway/engine/policies/src/test/java/io/apiman/gateway/engine/policies/IgnoredResourcesPolicyTest.java, gateway/test/src/test/resources/test-plan-data/policies/ignored-resources-xml/002-register-client.resttest, gateway/test/src/test/resources/test-plan-data/policies/ignored-resources/002-register-client.resttest, manager/ui/hawtio/plugins/api-manager/html/directives/requestMethod.html, manager/ui/hawtio/plugins/api-manager/html/policyForms/authorization.include, manager/ui/hawtio/plugins/api-manager/html/policyForms/ignored-resources.include, manager/ui/hawtio/plugins/api-manager/ts/directives.ts, manager/ui/hawtio/plugins/api-manager/ts/policies.ts
- Added verb (http method) support for Ignore resources policy rule.
- Adjusted tests to cover new cases. 
- Reshaped UI to support new functionalities. 
`IgnoredAligators`
http://gfycat.com/ThatBowedAlligatorgar
`AuthBorer`
http://gfycat.com/AliveKindlyBorer
1. Policies gui components
I think we may improve a little bit the way we style policies. 
Currently we use nested style (which is slightly invalid) or direct style on elements. 
I think that we can have separate style templates for this (with gulp support). 
It might look better to clean all rules at the same time so I'm not pushing that here.
2. Separate ts files per policy.
It may be better to have separate ts files per policy (this may speed up gulp building)
Do we have any reasons to keep it in one file?
=> Ignore Resources Policy: enhance to allow shading by VERB

manager/api/core/src/main/java/io/apiman/manager/api/core/IStorage.java, manager/api/es/src/main/java/io/apiman/manager/api/es/EsStorage.java, manager/api/jpa/src/main/java/io/apiman/manager/api/jpa/JpaStorage.java, manager/api/micro/src/main/java/io/apiman/manager/api/micro/ManagerApiMicroServiceApplication.java, manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/APIResourceImpl.java, manager/api/rest-impl/src/main/resources/io/apiman/manager/api/rest/impl/i18n/messages.properties, manager/api/rest/src/main/java/io/apiman/manager/api/rest/contract/IAPIResource.java, manager/api/war/wildfly8/src/main/webapp/WEB-INF/web.xml, manager/test/api/src/main/java/io/apiman/manager/test/server/ManagerApiTestServer.java, manager/test/api/src/main/java/io/apiman/manager/test/server/TestEsStorageWrapper.java, manager/test/api/src/main/java/io/apiman/manager/test/server/TestManagerApiApplication.java, manager/test/api/src/test/resources/test-plan-data/apis/delete_unpublished/000_create-unpublished-api1.resttest, manager/test/api/src/test/resources/test-plan-data/apis/delete_unpublished/001_get-unpublished-api1.resttest, manager/test/api/src/test/resources/test-plan-data/apis/delete_unpublished/002_delete-unpublished-api1.resttest, manager/test/api/src/test/resources/test-plans/apis-testPlan.xml
This is a proposed change described in:
https://issues.jboss.org/browse/APIMAN-942
=> Changes for APIMAN-942 - Ability to delete an unpublished service.

common/util/pom.xml, distro/karaf/bundles/gateway/gateway-osgi-servlet/pom.xml, distro/karaf/bundles/gateway/gateway-osgi/pom.xml, distro/karaf/features/src/main/resources/repository/features.xml, distro/karaf/test/pom.xml, gateway/engine/core/pom.xml
- Add dynamic Import Package to apiman-common-util in order to load the classes required to create the PluginRegistry, ....
- Update the features file to deploy the jest bundle committed to SMX project
- Recalculate some of the packages to be exported
- Deploy apiman-gateway-engine-es and apiman-gateway-engine-policies as bundle
=> Solve issue with "No IRegistry class configured" reported by Apiman Gateway bundle

common/util/pom.xml, distro/karaf/bundles/gateway/gateway-osgi-api/pom.xml, distro/karaf/bundles/gateway/gateway-osgi/pom.xml, distro/karaf/features/src/main/resources/repository/features.xml
Apiman Gateway Api can be deployed on Karaf  after doing these modifications
- Add missing package to Apiman Common Util
- Deploy okHTTP client as wrapped bundle
- Remove comments from gateway bundles
- Remove some embedded dependencies
=> Apiman Gateway Api can be deployed on Karaf

gateway/engine/es/pom.xml, gateway/engine/policies/pom.xml, gateway/platforms/servlet/pom.xml, gateway/platforms/vertx3/vertx3/pom.xml, gateway/test/pom.xml, manager/api/es/pom.xml, manager/api/micro/pom.xml, manager/api/war/pom.xml, manager/test/api/pom.xml, pom.xml, test/common/pom.xml, tools/ldap/pom.xml
cc @rnc 
BTW I also removed some unused deps. We seem to have a fair few, but it's a pain to figure out because the command to find unused deps often conflicts with the command that figures out transitive deps. It's a decent starting point, though.
```
mvn dependency:analyze -DignoreNonCompile=true 
```
Also, I found a neat plugin to sort pom files in a sensible way automatically. Here's the command I tried out that imitates our usage. I've not applied it broadly, just FYI.
```
mvn com.github.ekryd.sortpom:sortpom-maven-plugin:sort -Dsort.keepBlankLines -Dsort.predefinedSortOrder=custom_1 -Dsort.sortProperties=true -Dsort.sortDependencies=scope,groupId,artifactId
```
=> Fix remaining transitive issues and enable enforcement of transitive dep flaws

manager/ui/war/apiman/README.md, manager/ui/war/plugins/api-manager/css/apiman.css, manager/ui/war/plugins/api-manager/html/headers/README.md, manager/ui/war/plugins/api-manager/html/headers/amg.include, manager/ui/war/src/main/sdk/json-schema.html
Changes:
- Added the `amg` navigation header using the existing top loading bar; added some minor styling.
- Added a `README.md` for the headers and configuration directories, although this might be overkill. I thought we should document the possible values and how they are used somewhere.
- This also includes the change to get the JSON Schema testing page thing working again (updated paths for scripts).
JIRA: https://issues.jboss.org/browse/APIMAN-974
=> re #974 Navbar Header

manager/ui/war/npm-shrinkwrap.json, manager/ui/war/package.json, pom.xml
Changes:
- Updated Swagger Java implementation version to 1.5.7 in pom.xml.
- Updated swagger-ui version to 2.1.4 in package.json.
JIRA: https://issues.jboss.org/browse/APIMAN-977
=> re #977 Update swagger & swagger-ui

gateway/engine/es/src/test/java/io/apiman/gateway/engine/es/ESRegistryMarshallingTest.java, manager/api/es/src/main/java/io/apiman/manager/api/es/EsMarshalling.java, manager/api/jpa/src/main/java/io/apiman/manager/api/jpa/JpaStorage.java, manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/CurrentUserResourceImpl.java, manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/OrganizationResourceImpl.java, manager/api/security/src/main/java/io/apiman/manager/api/security/impl/AbstractSecurityContext.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2293 - “ The diamond operator ("<>") should be used ”. You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S2293
=> Simplify the generics declaration by using the diamond operator ("<>") to reduce the verbosity of generics code.

manager/ui/war/plugins/api-manager/html/policyForms/ignored-resources.include, manager/ui/war/src/main/sdk/json-schema.html
Swapped the "method" and "path" labels on the table header of the Ignored Resources Policy Configuration page.
JIRA: https://issues.jboss.org/browse/APIMAN-968
=> re #968 Swap method and path on table

gateway/engine/policies/src/main/java/io/apiman/gateway/engine/policies/config/AuthorizationRule.java, gateway/engine/policies/src/main/java/io/apiman/gateway/engine/policies/config/IgnoredResource.java
This pull request is focused on resolving occurrences of FindBugs rule HE_EQUALS_USE_HASHCODE - “ Class defines equals() and uses Object.hashCode() ”. You can find more information about the issue here: http://findbugs.sourceforge.net/bugDescriptions.html#HE_EQUALS_USE_HASHCODE
And
Sonar rule squid:S2097 - “ "equals(Object obj)" should test argument type ”. You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S2097
=> Override hashcode whenever overriding equals() and "equals(Object obj)" should test argument type

gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/InMemoryCacheStoreComponent.java, manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/OrganizationResourceImpl.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2184 - “ Math operands should be cast before assignment”. You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S2184
=> Casting math operands before assignment

common/auth/src/main/java/io/apiman/common/auth/AuthTokenUtil.java, common/config/src/main/java/io/apiman/common/config/ConfigFactory.java, common/plugin/src/main/java/io/apiman/common/plugin/PluginUtils.java, common/util/src/main/java/io/apiman/common/util/AesEncrypter.java, common/util/src/main/java/io/apiman/common/util/ApimanPathUtils.java, common/util/src/main/java/io/apiman/common/util/Basic.java, common/util/src/main/java/io/apiman/common/util/ReflectionUtils.java, common/util/src/main/java/io/apiman/common/util/ServiceRegistryUtil.java, common/util/src/main/java/io/apiman/common/util/SimpleStringUtils.java, gateway/engine/core/src/main/java/io/apiman/gateway/engine/components/ldap/result/DefaultExceptionFactory.java, gateway/engine/core/src/main/java/io/apiman/gateway/engine/components/ldap/result/DefaultLdapResultCodeFactory.java, gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/LDAPConnectionFactory.java, gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/ESUtils.java, gateway/test/src/main/java/io/apiman/gateway/test/server/GatewayTestUtils.java, manager/api/beans/src/main/java/io/apiman/manager/api/beans/BeanUtils.java, manager/api/core/src/main/java/io/apiman/manager/api/core/util/PolicyTemplateUtil.java, manager/api/jpa/src/main/java/io/apiman/manager/api/jpa/JpaUtil.java, manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/audit/AuditUtils.java, manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/util/ExceptionFactory.java, manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/util/FieldValidator.java, manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/util/SearchCriteriaUtil.java, manager/test/api/src/main/java/io/apiman/manager/test/util/ManagerTestUtils.java, test/common/src/main/java/io/apiman/test/common/util/TestUtil.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1118 - “ Utility classes should not have public constructors ”. You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1118
=> Adding private constructor to util classes (containing static methods only)

gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/ApiRequestExecutorImpl.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/connector/HttpConnector.java, manager/api/es/src/main/java/io/apiman/manager/api/es/EsStorage.java, manager/api/jpa/src/main/java/io/apiman/manager/api/jpa/JpaStorage.java, manager/test/api/src/main/java/io/apiman/manager/test/junit/ManagerRestTester.java, manager/test/api/src/test/java/io/apiman/manager/test/es/ESMetricsAccessorTest.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1155 - “Collection.isEmpty() should be used to test for emptiness”. You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1155
=> Using Collection.isEmpty() to test for emptiness

gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/util/CaseInsensitiveStringMultiMap.java
Looks like this:
```
new CaseInsensitiveMultiMap().add("a", "x").add("b", "y").add("c", "foo")
.add("c",` "BAR").add("C", "baz");
#toString
{a => [x], b => [y], c => [foo, BAR, baz]}
```
=> Nice toString for CaseInsensitiveStringMultiMap

manager/api/es/src/main/java/io/apiman/manager/api/es/EsMarshalling.java
Tests pass OK, and from what I can ascertain this doesn't change any intended behaviour, but as I'm not the original author of this I just want someone to review it to check.
The issue is that the XContentBuilder is never closed, so its underlying builder is, in turn, never closed.
@EricWittmann Please check this out.
=> (Bug) Fix multiple resource leaks in ES Marshalling code - *please review*

manager/ui/war/README.md, manager/ui/war/npm-shrinkwrap.json, manager/ui/war/package.json
Changes:
- Update `package.json` to include exact version of `angular-moment`
- Update `README.md` to include brief text about `npm-shrinkwrap.json`
- Rewrite `npm-shrinkwrap.json` to include changes
Was able to replicate the issue on both a clean and existing clone, using both the `http` and `https` NPM registries, on and off the VPN, with different versions of Node and NPM.
Tested this fix on both clean and existing clones. See example <a href="https://gist.github.com/kahboom/5b552f07c88667309e4b">here</a>.
JIRA: https://issues.jboss.org/browse/APIMAN-998
=> re #998 Fix for `npm install`

manager/ui/war/plugins/api-manager/html/api/api_entity.include, manager/ui/war/plugins/api-manager/html/client/client-apis.html, manager/ui/war/plugins/api-manager/ts/api/api.ts, manager/ui/war/plugins/api-manager/ts/rpc.ts
Changes:
- Add modal template and button to delete API (let me know if you don't like the cog dropdown option. I personally like it but we can go the traditional button route, I just didn't want to clutter the UI or "encourage" the user to delete).
- Add request to API to delete API
- Add comparison check for user input vs name of API after forcing both as lowercase, for user convenience
- Quick fix for How to Invoke API modal close button not working (JIRA: https://issues.jboss.org/browse/APIMAN-1001)
- Minor styling (mostly inline for now, will be improved later)
Also, in the future we need to implement a check that determines whether to show/hide the delete button at all in the UI. For now, the user will know because they will get an error when they try to delete an "undeletable" API. …
=> re #996 Delete APIs in UI

common/util/src/main/java/io/apiman/common/util/AesEncrypter.java, common/util/src/main/java/io/apiman/common/util/crypt/AesDataEncrypter.java, distro/wildfly9/src/main/resources/overlay/standalone/configuration/apiman.properties, gateway/engine/core/src/test/java/io/apiman/gateway/engine/impl/AesDataEncrypterTest.java
Changes (btw please tell me if I'm saying any of this incorrectly lol):
- Add implementation of `IDataEncrypter` interface, called `AesDataEncrypter`. Accepts a `config` Map, where it retrieves the `secretKey` from.
- Add new `encrypt` and `decrypt` methods to the `AesEncrypter` class that accept a `secretKey` string parameter.
- Add unit tests.
- Adding another bullet point to distract from the fact that it feels like I did so much more, but really only wrote a few lines of code.
Test screenshot because I have one, so why not:
JIRA: https://issues.jboss.org/browse/APIMAN-824
cc @EricWittmann @msavy
=> re #824 Accept secretKey in new implementation of IDataEncrypter

common/servlet/src/main/java/io/apiman/common/servlet/AuthenticationFilter.java, common/util/src/main/java/io/apiman/common/util/Basic.java, gateway/engine/policies/src/main/java/io/apiman/gateway/engine/policies/BasicAuthenticationPolicy.java, gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/HttpApiConnection.java, gateway/test/src/test/resources/test-plan-data/policies/basic-auth-static/004-failure.resttest, gateway/test/src/test/resources/test-plan-data/policies/basic-auth-static/005-failure.resttest, test/policies/src/main/java/io/apiman/test/policies/PolicyTestRequest.java
This PR normalises the HTTP Basic scheme name to match that of RFC1945.
See: http://tools.ietf.org/html/rfc1945#section-11.1
This fixes an issue with strict back-end services rejecting 'BASIC' (the current value) instead of 'Basic'.
=> Normalises HTTP Basic scheme name to match that of RFC1945

manager/ui/war/plugins/api-manager/html/catalog/api-catalog.html
Re-added the tagging label to `(press enter)`, since setting it to `false` was causing issues. Will create a GH issue in the ui-select repo to report this bug (after testing it on a few Plunkrs to make sure it's not just an issue with some other interaction).
=> re #1025 Fix for dropdown not working

manager/ui/war/plugins/api-manager/css/apiman.css, manager/ui/war/plugins/api-manager/html/catalog/api-catalog.html
Fixed styling issue where hidden filters were not displaying properly, adjusted height of all input fields.
Screenshots:
Vertical alignment of text:
=> re #1025 Adjust styling again, fixes for hidden filters

manager/ui/war/plugins/api-manager/css/apiman.css, manager/ui/war/plugins/api-manager/ts/directives.ts
Fixed the issue where inline editor buttons had a gap between them and the editor textarea, only in Chrome.
Tested on Chrome, FF, and Safari.
Screenshot:
JIRA: https://issues.jboss.org/browse/APIMAN-802
=> re #802 Fix for Chrome inline editor buttons

manager/api/es/src/main/java/io/apiman/manager/api/es/EsStorage.java, manager/test/api/src/test/resources/test-plan-data/plans/delete/005_activity.resttest, manager/test/api/src/test/resources/test-plan-data/plans/delete/006_version-activity.resttest, manager/test/api/src/test/resources/test-plans/plans-testPlan.xml
Whoops. How embarrassing. Somehow I ended up using the development query in my PR. 
I've added some extra tests, as I obviously wasn't covering this properly before (but coincidentally it seemed to be working).
=> (Bug) Fix ES query accidentally left with hard-coded dev values

gateway/engine/policies/src/main/java/io/apiman/gateway/engine/policies/auth/JDBCIdentityValidator.java
Small thing found by Coverity some time ago. Thought I might as well clear it up. I guess it was left behind from debug or something.
=> (Chore) Remove redundant function call

manager/api/jpa/pom.xml, manager/api/jpa/src/main/java/io/apiman/manager/api/jpa/AbstractJpaStorage.java, manager/api/jpa/src/main/java/io/apiman/manager/api/jpa/JpaStorage.java
Unfortunately it doesn't seem possible to do these delete queries in any reasonable way with just JQPL that also works around MySQL's inability to execute correlated subqueries.
Hibernate seems unable to cope with rewriting the correlated subquery for MySQL (some of the other JPA impls are possibly able to do it, so this solution only targets hibernate).
Hence, this solution uses 2 different paths. One for MySQL and another for all other DBs (which seem to support correlated subqueries with no issue).
=> [APIMAN-1109] (Bug) Add workaround for MySQL shortfalls by using Native SQL. 

distro/tomcat8/pom.xml, pom.xml
At the moment, the gateway logs in Tomcat don't work, as there's no SLF4J `StaticLoggerBinder` on the classpath. Tomcat uses JUL as its default logging provider.
Adds the SLF4J-JUL bridge dependency, enabling SLF4J loggers to work, and removing the logging system error on startup (http://www.slf4j.org/codes.html#StaticLoggerBinder).
=> Adds Tomcat logging provider.

gateway/engine/beans/pom.xml, gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/util/CaseInsensitiveStringMultiMap.java, gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/util/IStringMultiMap.java, gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/util/QueryMap.java, gateway/engine/beans/src/test/java/io/apiman/gateway/engine/beans/util/CaseInsensitiveStringMultiMapTest.java, gateway/engine/beans/src/test/java/io/apiman/gateway/engine/beans/util/MultimapTest.java, gateway/engine/beans/src/test/java/io/apiman/gateway/engine/beans/util/QueryMapTest.java, gateway/test/src/test/java/io/apiman/gateway/test/logging/TestLogger.java, gateway/test/src/test/resources/test-plan-data/policies/logging/002-log.resttest, pom.xml
- #toLowerCase type comparisons are now done without causing object creation.
Caveat: map expects only ASCII for keys (as per HTTP spec), else will not
be case insensitive.
- A fast hashing algorithm, xxHash, was selected and an implementation used
which also causes no allocation.
- Optimised for the most common behaviour: frequent access and modifications
with bijective mappings. Further work may be done to improve multi-value
performance if it proves necessary.
- More efficient iterator which doesn't create anywhere near as much garbage,
as an unmodifiable version of the real internal elements are returned.
- Iteration isn't especially efficient for very large datasets, as the entire
underlying array is iterated over. In most cases our tables are extremely
small, which doesn't justify …
=> perf(gateway-engine-beans) Reimplement CaseInsensitiveStringMultiMap to substantially improve performance and reduce GC. [APIMAN-1113]

manager/ui/war/plugins/api-manager/html/api/api-impl.html, manager/ui/war/plugins/api-manager/ts/api/api-impl.ts
**Issue(s):**
**JIRA 1**: https://issues.jboss.org/browse/APIMAN-1135
**JIRA 2**: https://issues.jboss.org/browse/APIMAN-1108
There were two bugs occurring:
1. Regardless of whether you have a single gateway or multiple, the save button in the Implementation tab is disabled unless the endpoint field is dirtied. This is a bug because it should not be checking if the field is dirty, rather that there is a valid value there at all. For instance, if you were to add an endpoint, save it, and then add the gateway _after_, the save button would still be disabled unless you dirtied the endpoint field.
2. Assuming you _did_ dirty the endpoint field, the save button would become enabled, but upon pressing the save button, the gateway information is not retained or persisted. You will still see the …
=> re #1135 #1108 Fix for bug with saving API gateway in UI

gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/util/CaseInsensitiveStringMultiMap.java
This fixes APIMAN-1142 - but it's actually completely coincidental. It's lucky that I was the one who implemented that map, so it occurred to me that it could be where the issue lay.
=> fix(gateway-engine-beans) CaseInsensitiveStringMultiMap put didn't handle hash collisions properly.

gateway/engine/policies/pom.xml, gateway/engine/policies/src/main/java/io/apiman/gateway/engine/policies/TimeRestrictedAccessPolicy.java, gateway/engine/policies/src/main/java/io/apiman/gateway/engine/policies/config/TimeRestrictedAccess.java, gateway/engine/policies/src/test/java/io/apiman/gateway/engine/policies/TimeRestrictedAccessPolicyTest.java, manager/ui/war/plugins/api-manager/ts/policies.ts
Implementation supporting ISO 8601 format as api input (more human readable format):
Old format:
``"timeStart": "2016-04-12T12:00:00.000Z"``
New format:
``"timeStart": "12:00:00"``
Internal implementation still using Date object for flexibility. 
If we want to store data as strings some additional refactoring will be required.
No user interface changes - everything should be as it was :)
I tried to use new `TestingPolicy` annotation, but it wasn't flexible enough to use it for that particular example.
=> APIMAN-1102 - Modify the Time Restricted Access Policy config format

distro/data/src/main/resources/ddls/apiman-gateway_mssql11.ddl, distro/data/src/main/resources/ddls/apiman_mssql11.ddl, distro/data/src/main/resources/sample-configs/apiman-ds_mssql.xml, distro/data/src/main/resources/sample-configs/apiman_gw-ds_mssql.xml, distro/ddl/pom.xml
This PR adds DDL and Maven plugin configuration to support MS SQL Server.
See https://issues.jboss.org/browse/APIMAN-951
* Instructions and config (commented, in line with current Oracle example) added to POM to enable DDL generation
* Schema files added
* JBoss datasource examples added
The sample DS files assume separate schemas (again, in line with the Oracle ones), but GW and Manager should be able to cooexist within the same schema, assuming no naming conflicts (https://issues.jboss.org/browse/APIMAN-1092).
=> APIMAN-951 Adds MS SQL Server support.

manager/ui/war/plugins/api-manager/ts/dialogs.ts
cc @EricWittmann - This is a timing issue, as we had discussed. We should be switching to UI-Bootstrap native directives for modals, as the Dialogs factory being used here is not native and uses a ton of jQuery while also creating a new $rootScope on command, which is really not good practice and is causing some issues. Since we don't have E2E tests implemented for the UI, I'm afraid of what the repercussions of switching to UI-Bootstrap would be, or what would break without us finding out until later, etc.
So, for now it's just a matter of finding the magic number for $timeout, so that it's not too slow for faster machines or too fast (requiring two clicks) for slower machines.
=> re # 1169 Update timeout to 75

gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/http/HttpApiFactory.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/http/HttpPolicyAdapter.java
> An endpoint MUST NOT generate an HTTP/2 message containing
> connection-specific header fields 
https://tools.ietf.org/html/rfc7540
This error was occurring because the backend was HTTP/1.1 and
hence we were inadvertently setting an illegal value.
Thanks to @bagder [for pointing this out](https://twitter.com/bagder/status/767052367686688768 ).
Need to do a little bit more work before I enable ALPN by default (as it's a bit fussy and needs JARs putting on the class-path and such), but this fixes a key issue.
JIRA: APIMAN-1217
=> fix(gateway-platforms-vertx3) Filter out Connection header when HTTP2 

gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/HttpApiConnection.java
Suppressed headers are not always removed from downstream requests to back-end APIs, nor in responses to the caller. This is because the comparison of header names is done in a _case-sensitive_ manner. According to [RFC-2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2):
> Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.
There is a set of 'suppressed headers' in `io.apiman.gateway.platforms.servlet.connectors.HttpApiConnection`. There are two comparison loops - one for requests and one for responses. In these loops the header keys are checked against the suppressed set and conditionally included if absent.
Currently, the comparison with the suppressed set is case-sensitive, resulting in suppressed …
=> Use case insensitive comparison for suppressed headers.

gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/HttpApiConnection.java
Don't copy Connection and Transfer-Encoding header from the the response as these are set by the servlet container (Tomcat)
=> APIMAN-1221 Don't copy Connection and Transfer-Encoding header

gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/ESRateLimiterComponent.java, manager/api/es/src/main/resources/io/apiman/manager/api/es/index-settings.json
ElasticSearch 2.X has deprecated _id from specific mapping. It expect
id should be specified explicitly.ES won't offer to parse document first
time just to retrieve the field that was specified as the id field.
ElasticSearch 2.X doesn't expect Version parameter at the time of index
creation.
the above two mentioned changes in ES 2.X were failing APIMan to work
for ElasticSearch 2.x. I have removed all the id field from
index-settings.json , and have put a hack in
ESRateLimiterComponent.java.It pass version only at the time of index
updation.
=> ElasticSearch 2.X fixes

gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/PolicyFailure.java, test/policies/src/main/java/io/apiman/test/policies/PolicyFailureError.java
Small change means you get a useful display of the error instead of a memory reference.
=> feat(test) More meaningful policy test errors.

gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/util/CaseInsensitiveStringMultiMap.java, gateway/engine/beans/src/test/java/io/apiman/gateway/engine/beans/util/CaseInsensitiveStringMultiMapTest.java
Different bits of code were using #getAllEntries/#getAllValues in different ways. Some required collision filtering, others not. The solution was to overload with additional parameters so that both can be provided.
Also:
- spec(gateway-engine-beans) Tests to verify the above.
- bug(gateway-engine-beans) Incidentally discovered bug that caused #size to
be inaccurate in certain collision cases. May want to consider deprecating
size as it is likely not quite what people expect and therefore not very
useful.
=> bug(gateway-engine-beans) Fixes collision filtration on CaseInsenstiveStringMultiMap #getAllEntries and #getAllValues.

gateway/engine/pom.xml, gateway/engine/vertx-polling/pom.xml, gateway/engine/vertx-polling/src/main/java/io/apiman/gateway/engine/vertx/polling/BadResponseCodeError.java, gateway/engine/vertx-polling/src/main/java/io/apiman/gateway/engine/vertx/polling/URILoadingRegistry.java, gateway/engine/vertx-polling/src/main/java/io/apiman/gateway/engine/vertx/polling/UnsupportedProtocolException.java, gateway/platforms/vertx3/vertx3-common/pom.xml, gateway/platforms/vertx3/vertx3-common/src/main/java/io/apiman/gateway/platforms/vertx3/common/verticles/Json.java, gateway/platforms/vertx3/vertx3/pom.xml, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/common/config/VertxEngineConfig.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/io/package-info.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/services/package-info.java, gateway/platforms/vertx3/vertx3/src/main/resources/io/apiman/gateway/platforms/vertx3/i18n/messages.properties, pom.xml
Example [data file](https://gist.githubusercontent.com/msavy/cb245f4ed5228e8aa368a03b035f4b9b/raw/25dcc614dba43821b7623e16302b404c39bdeeca/apiman-gateway-api.json) to read in:
```
{
"apis": [{
"publicAPI": true,
"organizationId": "foo",
"apiId": "foo",
"version": "foo",
"endpoint": "http://www.example.org/fgdfgfdgdfdfd",
"endpointType": "rest",
"endpointContentType": "",
"endpointProperties": {},
"parsePayload": false,
"apiPolicies": [{
"policyJsonConfig": "",
"policyImpl": "plugin:io.apiman.plugins:apiman-plugins-test-policy:1.2.9-SNAPSHOT:war/io.apiman.plugins.test_policy.TestPolicy"
}]
}],
"clients": [{
"organizationId": "foo",
"clientId": "fooClient",
"version": "foo",
"apiKey": "12345",
"contracts": [{
"apiOrgId": "foo",
"apiId": "foo",
"apiVersion": "foo",
"plan": "foo",
"policies": …
```
=> Vert.x one-shot, URI pull registry (JSON).

common/plugin/src/main/java/io/apiman/common/plugin/PluginUtils.java, gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/DefaultPluginRegistry.java
@EricWittmann 
as discussed, I haved added below commit for APIMAN-1235.
maven .m2 local repository system property is added to the common method so it is used by both apiman-gateway and apiman-manager.
=> APIMAN-1235: override maven .m2 local repository system property added

gateway/platforms/war/pom.xml
@EricWittmann Is there a way to add JARs to the classpath easily in our WAR/WF distros? For instance, adding the log4j2-slf4j JAR if people wanted to use that, or logback, etc as their implementation?
=> Add slf4j logger factory to WAR path

gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/Contract.java, gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/Policy.java, gateway/engine/vertx-polling/pom.xml, gateway/engine/vertx-polling/src/main/java/io/apiman/gateway/engine/vertx/polling/URILoadingRegistry.java, gateway/engine/vertx-polling/src/main/java/io/apiman/gateway/engine/vertx/polling/exceptions/BadResponseCodeError.java, gateway/engine/vertx-polling/src/main/java/io/apiman/gateway/engine/vertx/polling/exceptions/OAuth2Exception.java, gateway/engine/vertx-polling/src/main/java/io/apiman/gateway/engine/vertx/polling/exceptions/UnsupportedProtocolException.java, gateway/engine/vertx-polling/src/main/java/io/apiman/gateway/engine/vertx/polling/fetchers/FileResourceFetcher.java, gateway/engine/vertx-polling/src/main/java/io/apiman/gateway/engine/vertx/polling/fetchers/HttpResourceFetcher.java, gateway/engine/vertx-polling/src/main/java/io/apiman/gateway/engine/vertx/polling/fetchers/ResourceFetcher.java, gateway/engine/vertx-polling/src/main/java/io/apiman/gateway/engine/vertx/polling/fetchers/auth/AbstractOAuth2Base.java, gateway/engine/vertx-polling/src/main/java/io/apiman/gateway/engine/vertx/polling/fetchers/auth/AuthType.java, gateway/engine/vertx-polling/src/main/java/io/apiman/gateway/engine/vertx/polling/fetchers/auth/Authenticator.java, gateway/engine/vertx-polling/src/main/java/io/apiman/gateway/engine/vertx/polling/fetchers/auth/BasicAuth.java, gateway/engine/vertx-polling/src/main/java/io/apiman/gateway/engine/vertx/polling/fetchers/auth/KeycloakOAuth2Client.java, gateway/engine/vertx-polling/src/main/java/io/apiman/gateway/engine/vertx/polling/fetchers/auth/NoneAuth.java, gateway/engine/vertx-polling/src/main/java/io/apiman/gateway/engine/vertx/polling/fetchers/auth/OAuth2Client.java, gateway/engine/vertx-polling/src/main/java/io/apiman/gateway/engine/vertx/polling/fetchers/auth/OAuth2ClientCredentials.java, pom.xml
* Add BASIC & OAuth2 client auth support for HTTP/HTTPS file loading.
* Refactor for improved extensibility, with assumption additional auth methods will be added later.
=> feat(polling-registry) Add BASIC & OAuth2 client auth support for HTTP/HTTPS file loading.

gateway/platforms/vertx3/vertx3/pom.xml, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/connector/ConnectorFactory.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/connector/HttpConnector.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/connector/HttpConnectorOptions.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/http/HttpClientOptionsFactory.java, gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/connector/HttpConnectorDrainTest.java, pom.xml
* Add LRUCache of HttpClient in ClientConnector to make use of connection pooling when connecting to similarly configured backends (e.g. same endpoint,  same security settings, etc).
* Clean up constructor by adding HttpConnectorOptions.
* Change some URL to URI (URL is blocking in `equals`).
=> fix(platform-vertx) Add LRUCache of HttpClient in ClientConnector.

pom.xml
Gets rid of associated warnings in Maven output.
=> build(pom) No longer need MaxPermSize in Java 8+

gateway/platforms/vertx3/vertx3/pom.xml
Sorry, another small warning-eliminating build PR :-).
=> build(platform-vertx) Fix shade plugin build warnings. Upgrade to 2.4.3.

gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/util/CaseInsensitiveStringMultiMap.java, gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/util/IStringMultiMap.java, gateway/engine/beans/src/test/java/io/apiman/gateway/engine/beans/util/CaseInsensitiveStringMultiMapTest.java
- MultiMap bug fix for deletion with specific collision ordering.
- Updated tests to hit this issue (requires specific ordering in combination with collision).
=> bug(gateway-engine) MultiMap bug fix for deletion with specific collision ordering.

gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/util/CaseInsensitiveStringMultiMap.java, gateway/engine/beans/src/test/java/io/apiman/gateway/engine/beans/util/CaseInsensitiveStringMultiMapTest.java
- MultiMap: Correct ordering of values in #toString. Now respects insertion order.
Hat tip to @outofcoffee 
Also thanks to Holger for neat IntStream [trick](http://stackoverflow.com/a/29409584/2766538).
=> bug(gateway-engine) MultiMap: Correct ordering of values in #toString.

gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/common/config/VertxEngineConfig.java, gateway/test/src/test/resources/vertx3/conf-es.json
This is the equivalent to the Servlet's properties definition feature, and helps avoid repetition - such as repeated ES component config.
Example:
```json
{ 
"variables": {
"test": {
"foo": {
"es": {
"type": "jest"
}
}
}
},
"registry": {
"class": "io.apiman.gateway.engine.es.ESRegistry",
"config": {
"client": {
"type": "${test.foo.es.type}",
"cluster-name": "elasticsearch",
"host": "localhost",
"port": "9200",
"initialize": true
}
}
}
}
```
=> feat(gateway-vertx) Variables section in config to allow vars transclusion.

gateway/engine/core/src/main/java/io/apiman/gateway/engine/IPolicyFailureWriter.java, gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/ApiRequestExecutorImpl.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/connector/HttpConnector.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/http/HttpPolicyAdapter.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/verticles/ApimanVerticleWithEngine.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/verticles/HttpGatewayVerticle.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/verticles/HttpsGatewayVerticle.java, gateway/test/src/test/java/io/apiman/gateway/test/Policy_IgnoredResourcesXmlTest.java, gateway/test/src/test/java/io/apiman/gateway/test/SimplePayloadPolicyTest.java, gateway/test/src/test/resources/test-plan-data/policies/ignored-resources-xml/003-success.resttest
* feat(gateway-vertx) Use policy failure and error writers. Reenable corresponding tests.
* fix(gateway-core) Ensure Vert.x implementation works with #parsePayload quirks in ApiRequestExecutor.
ApiRequestExecutor is called before ApiConnection has been returned by the upfront payload parsing feature, this means that the Vert.x implementation will cause `NullPointerException` errors when drainHandler and full are invoked. 
Simple null checks bypass this issue, although a more thorough refactoring may be considered in future (albeit, the accumulation of complexity in this area of code has made it exceptionally difficult to understand, so a general refactoring would probably make sense.).
=> feat(gateway-vertx) Use policy failure and error writers. Reenable corresponding tests.

gateway/platforms/vertx3/vertx3/pom.xml, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/ApimanLauncher.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/ApimanVersionCommand.java, pom.xml
* build(gateway-vertx) Build fat jar as own classifier.
* refactor(gateway-vertx) Own command launcher and override version.
* build(pom) Ensure timestamp is populated
```
Apr 23, 2017 5:53:20 PM io.apiman.gateway.platforms.vertx3.ApimanVersionCommand
INFO: Apiman 1.2.10-SNAPSHOT @ 2017-04-23 16:45:39
Apr 23, 2017 5:53:20 PM io.apiman.gateway.platforms.vertx3.ApimanVersionCommand
INFO: Vert.x 3.4.0
```
For releases date is not shown
=> Build fat jar as own classifier & override version command.

distro/vertx/src/main/resources/overlay/log4j2.xml
Didn't seem to break anything, somehow.
=> fix(distro-vertx) Typo in log4j2.xml

gateway/engine/core/src/main/java/io/apiman/gateway/engine/components/jdbc/IJdbcConnection.java, gateway/engine/core/src/main/java/io/apiman/gateway/engine/components/jdbc/IJdbcResultSet.java, gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/components/jdbc/JdbcTestSuite.java
Generally this would only occur if there was a TZ disagreement between various parts of the system. Previous failed attempts to fix this missed that H2 picks up its TZ from System properties and can't be overridden via API.
=> test(gateway-vertx) Fix build issue that could occur due to TZ contraindiction

gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/api/ApiResourceImpl.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/api/ClientResourceImpl.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/api/auth/AuthFactory.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/verticles/ApiVerticle.java
This was only evident when doing some manual testing using KC OAuth2, as automated tests only use BASIC.
=> fix(gateway-vertx) Ensure ApiVerticle parses body early to avoid losing it if OAuth2 kicks in.

gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/connector/HttpConnector.java
Was looking in the outbound set which was obviously always empty, whoops. It caused chunked mode to be used from the gateway to API (but would reappear for client).
=> fix(gateway-vertx) HttpConnector predicate looked in wrong map for Content-Length

gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/http/HttpPolicyAdapter.java
Thanks to @EricWittmann for helping me discover this one. I was aided in fixing the issue by @vietj's comment @ https://github.com/eclipse/vert.x/issues/1244#issuecomment-165532673.
=> fix(gateway-vertx) Ensure #resume called in error cases before #end to avoid potential TCP hang.

gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/verticles/HttpsGatewayVerticle.java
Gated enabling of ALPN if an implementation is available, for instance from Jetty's ALPN Boot.
=> feat(gateway-vertx): Enable ALPN if a implementation is available.

gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/verticles/InitVerticle.java
InitVerticle log use {0} syntax instead of {} as this ensures JUL will still work.
=> fix(gateway-vertx): InitVerticle log use {0} syntax instead of {}.

manager/api/micro/pom.xml
@EricWittmann I think this issue was caused when you added something around i18n to WAR but it wasn't also added to Micro. Not sure if I need to add it anywhere else? 
It seems to cause some failures in certain parts of the UI when using any of the micro distros, anyway.
=> build(manager-api-micro): Missing ICU dep for micro

gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/ssl/SSLSessionStrategyFactory.java
The previous code allow only TLS v1.0 when devMode is true.
With this modification, all versions of TLS will be accepted.
=> Update SSLSessionStrategy for devMode to allow all TLS version

gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/EngineErrorResponse.java, gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/DefaultPolicyErrorWriter.java, gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/TracePolicyErrorWriter.java
* For example if NPE occurs in a custom policy it now returns a clearer message to the user.
=> fix(gateway-engine) Clearer handling of unexpected exceptions in ErrorWriter impls

gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/api/auth/KeycloakOAuthFactory.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/common/config/VertxEngineConfig.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/verticles/ApiVerticle.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/verticles/HttpGatewayVerticle.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/verticles/HttpsGatewayVerticle.java
Please check https://issues.jboss.org/browse/APIMAN-1292
=> feat(gateway-vertx) new host property in verticles config

gateway/platforms/vertx3/vertx3/pom.xml
Current configuration was causing providers manifests to be overwritten.
=> build(distro-vertx) Ensure shade plugin merges providers

gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/ESCacheStoreComponent.java
Cache population for ES doesn't work for the simple/non-binary implementation.
Ensures the JSON object is set in the `head`, instead of the cache entry itself(!) in `ESCacheStoreComponent.put()`, from where it is expected to be read in `ESCacheStoreComponent.get()`.
=> Fixes broken ES cache population.

gateway/engine/prometheus/pom.xml, gateway/engine/prometheus/src/main/java/io/apiman/gateway/engine/prometheus/PrometheusScrapeMetrics.java, gateway/engine/prometheus/src/test/java/io/apiman/gateway/engine/prometheus/BasicMetricsTest.java, gateway/engine/prometheus/src/test/resources/log4j.properties
The Prometheus metrics implementation throws an exception when `null` is passed as the client ID. This is because client ID is a mandatory label, and labels can't be `null`.
* Allows Prometheus metrics implementation to be used with no client ID.
* Reenables the Prometheus metrics tests (which start their own server).
=> Allows Prometheus metrics implementation to be used with no client ID

distro/tomcat8/pom.xml, gateway/platforms/war/tomcat8/api/pom.xml, gateway/platforms/war/tomcat8/api/src/main/resources/log4j2.xml, gateway/platforms/war/tomcat8/gateway/pom.xml, gateway/platforms/war/tomcat8/gateway/src/main/resources/log4j2.xml, manager/api/war/tomcat8/pom.xml, manager/ui/war/tomcat8/pom.xml, manager/ui/war/tomcat8/src/main/resources/log4j2.xml, pom.xml
This PR fixes the SLF4J binding errors and Log4J configuration issues with the Tomcat WARs.
* Tomcat WARs now use the Log4J2 provider, via the project's common logging module.
* In addition, commons-logging is routed to Log4J2.
=> Fix Tomcat logging

gateway/platforms/war/tomcat8/api/pom.xml, gateway/platforms/war/tomcat8/gateway/pom.xml, manager/api/war/tomcat8/pom.xml, manager/ui/war/tomcat8/pom.xml
Following on from https://github.com/apiman/apiman/pull/654, this PR adds the SLF4J API dependency to Tomcat distributions to ensure logs from plugins are also routed correctly.
=> Fixes plugin logging in Tomcat distributions.

manager/ui/war/entry.js, manager/ui/war/gulpfile.js, manager/ui/war/package.json, manager/ui/war/plugins/api-manager/ts/consumer/consumer-api.ts, manager/ui/war/plugins/api-manager/ts/rpc.ts, manager/ui/war/plugins/includes.ts, manager/ui/war/yarn.lock
Recent version updates had broken the rendering of Swagger docs. This update fixes these issues and,
as an added bonus, allows OpenAPI documents to be rendered.
Fixes APIMAN-1302
=> fix(ui): Fix rendering of Swagger/OpenAPI docs.

gateway/engine/core/src/main/java/io/apiman/gateway/engine/IConnectorConfig.java, gateway/engine/core/src/main/java/io/apiman/gateway/engine/IConnectorFactory.java, gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/AbstractConnectorConfig.java, gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/ApiRequestExecutorImpl.java, gateway/engine/core/src/main/java/io/apiman/gateway/engine/policy/IPolicyContext.java, gateway/engine/core/src/main/java/io/apiman/gateway/engine/policy/PolicyContextImpl.java, gateway/engine/core/src/test/java/io/apiman/gateway/engine/impl/AbstractConnectorConfigTest.java, gateway/engine/core/src/test/java/io/apiman/gateway/engine/impl/DefaultEngineFactoryTest.java, gateway/engine/core/src/test/java/io/apiman/gateway/engine/impl/TestConnectorConfigImpl.java, gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/ConnectorConfigImpl.java, gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/HttpApiConnection.java, gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/HttpConnectorFactory.java, gateway/platforms/servlet/src/test/java/io/apiman/gateway/platforms/servlet/auth/basic/BasicAuthTest.java, gateway/platforms/servlet/src/test/java/io/apiman/gateway/platforms/servlet/auth/tls/BasicMutualAuthTest.java, gateway/platforms/servlet/src/test/java/io/apiman/gateway/platforms/servlet/auth/tls/CAMutualAuthTest.java, gateway/platforms/servlet/src/test/java/io/apiman/gateway/platforms/servlet/auth/tls/CipherAndProtocolSelectionTest.java, gateway/platforms/servlet/src/test/java/io/apiman/gateway/platforms/servlet/auth/tls/StandardTLSTest.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/api/IRouteBuilder.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/common/config/VertxEngineConfig.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/connector/ConnectorFactory.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/connector/HttpConnector.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/connector/VertxConnectorConfig.java, gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/connector/HttpConnectorDrainTest.java, test/policies/src/main/java/io/apiman/test/policies/PolicyTesterConnectorConfig.java, test/policies/src/main/java/io/apiman/test/policies/PolicyTesterConnectorFactory.java
Adds IConnectorConfig, which we can expand to allow twiddling of various connector configuration aspects by policies.
=> Allow policies to suppress and permit headers

gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/ApiRequestExecutorImpl.java
Closes APIMAN-1335
Signed-off-by: Marc Savy <marc@rhymewithgravy.com>
=> fix(gateway-engine) Assign connector config to context early to avoid NPE in Vert.x

gateway/engine/es/pom.xml, gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/ESMetrics.java, gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/PollCachingESRegistry.java
This PR fixes https://github.com/apiman/apiman/issues/683
I am not sure about the logging, but it is better for the moment than printing every time the whole stacktrace.
Please let me know, what you think :)
=> #683: Don't invalidate the cache if ES goes down

common/config/src/main/java/io/apiman/common/config/options/TLSOptions.java
You are not able to connect the vertx gateway with an API that is secured over https.
You are running into the following error:
```
[DEBUG] 2018-08-28 14:15:22.010 [vert.x-eventloop-thread-3] HttpConnector - Connecting to XXX | ssl?: true port: 8,443 verb: GET path: /SalesForce/SalesForce/REST/Services
[ERROR] 2018-08-28 14:15:22.027 [vert.x-eventloop-thread-3] ContextImpl - Unhandled exception
io.vertx.core.VertxException: java.security.UnrecoverableKeyException: Password must not be null
at io.vertx.core.net.impl.SSLHelper.createContext(SSLHelper.java:304) ~[apiman-gateway.jar:?]
at io.vertx.core.net.impl.SSLHelper.getContext(SSLHelper.java:446) ~[apiman-gateway.jar:?]
at io.vertx.core.net.impl.SSLHelper.validate(SSLHelper.java:466) ~[apiman-gateway.jar:?]
at …
```
=> fix: vertx cert error because of typo

manager/ui/war/tomcat8/src/main/webapp/WEB-INF/web.xml, manager/ui/war/tomcat8/src/main/webapp/login.html
If the session was not valid there was no redirect to the login page of Tomcat 8.
With this small fix we are able to do a redirect and have a whitelisting of the login CSS files.
This works also if you use keycloak as login provider instead of tomcat. Otherwise also the keycloak login page was not loaded correctly.
Thanks @bekihm for finding this out and help me with the debugging of this :)
@msavy and @EricWittmann Please let us know what you think of this.
=> Small fix for redirect in Tomcat (with Keycloak)

gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/api/ApiResourceImpl.java, gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/api/ApiRessourceImplTest.java
Hi togehter,
we have encountered a small issue with the vertx json config:
The problem is how the endpoint was builded if you set a special endpoint and use port 443 or 80, but not specify this port in the endpoint sring:
**Example**:
```json
// You can force a particular endpoint to be reported here (e.g.
// if you have some clustered setup with exotic DNS setup)
"endpoint": "https://gateway.e2e.ch",
// Verticle configuration
// Port - The port a given verticle listens on (where relevant)
// Count - Number of given verticle type launched
"verticles": {
"http": {
"port": 8082,
"count": 1
},
"https": {
"port": 443,
"count": 0
},
"api": {
"port": 8081,
"count": 1
}
},
```
**Result:**
This ended up in the UI with a missing slash after the host under "Endpoint"
* …
=> Fix how vertx public endpoint is assembled in UI

manager/api/es/src/main/java/io/apiman/manager/api/es/EsStorage.java
Hi together,
I encountered a little bug while making some tests:
If you create a plan, delelte the plan and recreate a plan with the same name you got an error in the UI:
```json
{"root_cause":[{"type":"version_conflict_engine_exception","reason":"[planPolicies][TestOrg:TestPlan:1.0]: version conflict, document already exists (current version [1])","index_uuid":"9RrVDUg2Sda7nj-Ufg4IqQ","shard":"3","index":"apiman_manager"}],"type":"version_conflict_engine_exception","reason":"[planPolicies][TestOrg:TestPlan:1.0]: version conflict, document already exists (current version [1])","index_uuid":"9RrVDUg2Sda7nj-Ufg4IqQ","shard":"3","index":"apiman_manager"}
```
The Plan is still created in the UI but the planVersion document is missing in ES.
**Steps to reproduce / Environment**
- Elasticsearch …
=> Fix recreation of a plan - Elasticsearch Issue

manager/ui/war/plugins/api-manager/html/catalog/api-catalog.html
This is a little UI fix for the API Catalog. 
If you use the filter for tags it gets annoying if the selected tags are not shown.
=> fix-ui: Show selected tags in API Catalog

.travis.yml, gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/LDAPConnectionFactory.java, gateway/engine/policies/src/test/java/io/apiman/gateway/engine/policies/BasicAuthLDAPSTest.java, gateway/engine/policies/src/test/java/io/apiman/gateway/engine/policies/util/DefaultLdapComponentReloaded.java
I just fix method getConnection() in LDAPConnectionFactory + Add a unit test class : BasicAuthLDAPSTest.
The fix was successfully tested on a existing gateway, by adding a BasicAuth policy, connected by LDAPS on corporate LDAP directory.
=> apiman-722 : BasicAuth, LDAPS - Fix Error "SERVER_DOWN, java.net.SocketException: Connection reset" in SSL.

distro/tomcat8/src/main/resources/overlay/conf/apiman.properties, distro/wildfly10/src/main/resources/overlay/standalone/configuration/apiman.properties, distro/wildfly11/src/main/resources/overlay/standalone/configuration/apiman.properties
A comma  separated list work only if the comma is escaped. Because the communs-configuration library (version 1.10) is called with getString(), then that return only the first word.
With the value allowedProtocols=TLSv1.2,TLSv1.1, apiman load only "TLSv1.2".
To fix issues we can:
- Escaped comma,
- Move library  communs-configuration to 2.2 ( more complicated)
- Use getArrayString(), many refactoring because getString is use in generic code for String and List
=> Fix example configuration with comma separated list

distro/data/src/main/resources/data/all-policyDefs.json, gateway/engine/beans/src/test/java/io/apiman/gateway/engine/beans/util/QueryMapTest.java, gateway/engine/policies/src/main/java/io/apiman/gateway/engine/policies/CachingPolicy.java, gateway/engine/policies/src/main/java/io/apiman/gateway/engine/policies/config/CachingConfig.java, gateway/engine/policies/src/test/java/io/apiman/gateway/engine/policies/CachingPolicyTest.java
* An alternative to #652, with a configuration option to maintain backwards compatibility.
* This enables the CachingPolicy to optionally include query string in its cache key, per RFC7234.
According to RFC7234 (https://tools.ietf.org/html/rfc7234#section-2),
> 'The primary cache key consists of the request method and target URI.'
For historical reasons, this is not the behaviour of this policy, which instead uses only the path part of the URI, not the query string. The behaviour mentioned in the RFC can be enabled using a configuration option, `includeQueryInKey`, whose default is `false`.
Appropriate test coverage is added to verify the behaviour with the configuration [en|dis]abled. Also reenables ignored unit tests for QueryMap and adds another test case for an empty map.
We should …
=> Make Caching policy more RFC7234 compliant w.r.t. query string

gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/InMemoryRateLimiterComponent.java
We have detected a bug in the InMemoryRateLimter while using it with vertx.
Because vertx creates multiple threads we have in each thread a different buckets Map containing different entries for the same bucketId.
You can see this here, that the same request is handled by two different threads and this results in a wrong remaining limit:
```
2019-03-27T13:33:13.631314600Z [DEBUG] 2019-03-27 13:33:13.630 [vert.x-eventloop-thread-2] HttpConnector - Connecting to petstore.swagger.io | ssl?: true port: 443 verb: GET path: /v2
...
2019-03-27T13:34:04.557650800Z [DEBUG] 2019-03-27 13:34:04.557 [vert.x-eventloop-thread-3] HttpConnector - Connecting to petstore.swagger.io | ssl?: true port: 443 verb: POST path: /v2
```
If we make the the Hashmap static we can avoid this problem.
@EricWittmann Do …
=> Fix InMemoryRateLimiter

distro/vertx/src/main/resources/overlay/configs/conf-es.json, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/api/auth/KeycloakOAuthFactory.java
This is a fix for https://issues.jboss.org/browse/APIMAN-1339
Without this fix it is not possible to connect vertx with a standalone keycloak installation that is secured by a self signed certificate.
Please let me know what you think :)
=> APIMAN-1339: Support self signed certificates from keycloak in vertx

distro/vertx/src/main/resources/overlay/configs/conf-es.json, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/api/Router2ResteasyRequestAdapter.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/api/auth/KeycloakOAuthFactory.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/api/auth/NoneAuth.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/common/config/VertxEngineConfig.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/logging/ApimanLog4j2LogDelegate.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/verticles/ApiVerticle.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/verticles/ApimanVerticleBase.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/verticles/HttpsGatewayVerticle.java, pom.xml, test/common/src/main/java/io/apiman/test/common/echo/EchoServerVertx.java
We had the requirement that the the vert.x gateway (as server) defines the TLS protocol version for the connection between Client <-> Gateway.
This was not possible with the existing configuration.
I had to upgrade vert.x to get some methods to achieve this functionality and add a new flag to the configuration file. 
The other setting in `connector-factory` section is only for the connection Gateway <-> Unmanaged API. 
So this was not suitable for our case and for vert.x it is only a dummy setting. 
Vertx will only log: "Can't set allowed protocols on Vert.x gateway"
So I put the new setting in the `ssl` section of the config file.
I think we have to change the documentation also a bit for this, or the other conf.json files. I will do this if this gets merged.
And again I have to thank …
=> Make TLS protocols configurable for vert.x (Client <-> Vert.x Server)

manager/ui/war/plugins/api-manager/html/consumer/consumer-api.html, manager/ui/war/plugins/api-manager/ts/catalog/api-catalog.ts, manager/ui/war/plugins/api-manager/ts/consumer/consumer-api.ts
Fixes Issue apiman#738. It enables the showing of Swagger YAML API definitions in the ui
=> Fix YAML API definitions not showing (#738)

test/common/src/main/java/io/apiman/test/common/json/JsonCompare.java
@bekihm and I noted that the test MirgrateTest.Export often fails because of a correlation failure.
`MigrateTest.Export Data » java.lang.RuntimeException: Correlation failure`
This is caused by comparing different json arrays (actual vs expected) and missmarch of actual values with different correlation values.
We sort the arrays now before the compare so we have the same structure with the actual and the expected, this should avoid to run into the mismatch of actual and expected json.
=> Fix correlation failure for MigrateTest.Export by sorting json arrays

common/es/src/main/resources-filtered/io/apiman/common/es/util/apiman_manager-settings.json, manager/api/es/src/main/java/io/apiman/manager/api/es/EsStorage.java, manager/api/es/src/main/resources/io/apiman/manager/api/es/index-settings.json
Here we go:
The problem was that mapping type "string" is not supported anymore in elasticseach. It is replaced with keyword and text. String will be changed automatically if you create an index with old mapping definitions.
In our case the field "data" was mapped with keyword, that can only store 32KB.
I changed it to text. So new installations does not have this problem anymore.
The migration process is a bit more complex for old installations:
1. Check if the old mapping applies
2. If yes, create a tmp index with new mapping
3. Reindex apiman_manger to tmp
4. Delete old apiman_manger index
5. Reindex tmp to apiman_manager
6. Delete tmp
Everything is made asynchronous so the UI does not freeze.
It is hard to test, because you need an existing elasticsearch with this kind of documents. …
=> Fixes #736 -changed field mapping for "data" and added migration method

manager/ui/war/plugins/api-manager/html/plan/plan_entity.include, manager/ui/war/plugins/api-manager/ts/plan/plan.ts
It is only possible to delete an unlooked plan.
> Use this endpoint to delete a plan. Only an unlocked plan may be deleted.
So we added a little check if a plan version is locked and then hide the delete button.
As always thanks to @bekihm
=> Little UI improvement: Hide delete button if not able to delete a plan

manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/OrganizationResourceImpl.java
We encountered a small issue:
If you delete an API, the API Definition is never deleted in the storage.
If you create a new API with the same name as the deleted API it shows the old definition.
This can cause a lot of dangling definitions.
Thanks to @bekihm for reviewing.
=> Delete ApiDefinition files in storage if the whole API gets deleted

gateway/engine/core/pom.xml, manager/ui/war/src/main/assembly/ui.xml
With this small improvement we fix a maven warning when building on windows and also added a missing export package which caused a lot of annoying warnings in IntelliJ IDEA.
Thanks again to @bekihm :)
=> Fix maven errors

gateway/test/src/test/java/io/apiman/gateway/test/junit/vertx3/ApiToFileRegistry.java, gateway/test/src/test/java/io/apiman/gateway/test/junit/vertx3/Vertx3GatewayFileRegistryServer.java, gateway/test/src/test/java/io/apiman/gateway/test/junit/vertx3/Vertx3GatewayHelper.java, gateway/test/src/test/java/io/apiman/gateway/test/junit/vertx3/Vertx3GatewayTestServer.java
We run a jenkins pipeline to test the apiman project.
We encountered that the resource loading of the test files failed if the directory name contains a `@`.
We fixed this an reduced also the duplicate code :)
Thanks @bekihm for reviewing
=> Fix resource loading because special characters in directory name

manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/util/SwaggerWsdlHelper.java
Use of a "safe" accessor to get host and basePath instead of searching in the whole json.
This fix a NPE that was caused through some special swagger files.
=> Little improvement for SwaggerWsdlHelper.java

.travis.yml
The action '-Dapiman-test.type=es -Dapiman.gateway-test.config=servlet-es' was failing because it is now being interpreted as a single string seemingly. 
Trying double quotes to see whether that works.
=> ci(travis): Use double quotes on travis actions

distro/eap7/src/main/resources/overlay/standalone/configuration/standalone-apiman.xml, distro/wildfly10/src/main/resources/overlay/standalone/configuration/standalone-apiman.xml, distro/wildfly11/src/main/resources/overlay/standalone/configuration/standalone-apiman.xml, gateway/engine/core/src/main/java/io/apiman/gateway/engine/rates/RateLimiterBucket.java, gateway/platforms/war/tomcat8/api/src/main/webapp/WEB-INF/web.xml, gateway/platforms/war/wildfly8/api/src/main/webapp/WEB-INF/web.xml, manager/api/war/tomcat8/src/main/webapp/WEB-INF/web.xml, manager/api/war/wildfly8/src/main/webapp/WEB-INF/web.xml, manager/test/api/src/test/java/io/apiman/manager/test/es/ESMetricsAccessorTest.java, manager/ui/war/wildfly8/src/main/webapp/WEB-INF/web.xml
I need to be able to easily use a different realm and URL when the Keycloak server is external. This allows the use of environment variables, making them easily overridden for a docker container, while leaving the current defaults. Also fix test that did not wait for Elasticsearch to start.
=> Allow override of Keycloak Realm & URL via environment

manager/ui/war/plugins/api-manager/ts/policies.ts
A customer asked us if there is a maximum value for the rate-limiting policy.
The limit is of type long in the java code but this can't be easily represented in javascript.
So we decided to check for `Numbers.isSafeInteger`.
Via the UI following applies:
The value is restricted through Javascript.
The maximum value you can set via the **UI is 9007199254740991** (2<sup>53</sup> - 1).
Via the REST API following applies:
The value is restricted through Java.
The maximum value you can set via the **REST API is 9223372036854775807**(2<sup>63</sup> - 1).
So let us know what you think about this little improvement :)
=> Only safe integers for rate limiting policy

distro/vertx/src/main/resources/overlay/log4j2.xml, gateway/engine/core/src/main/java/io/apiman/gateway/engine/handler/ErrorHandler.java, gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/DefaultPolicyErrorWriter.java, gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/HttpApiConnection.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/connector/HttpConnector.java
Some little gateway improvements:
- allow setting the log level of the vertx gateway via a system property `apiman.gateway-logLevel`
- log policy error (till now you saw the stacktrace only if the trace was on and the stacktrace was returned in the response)
- Log connection errors instead of send them in the response 
- In a production environment the trace mode is normally off and the gateway should not leek internal information of the backend service like hostname, IP and ports. 
```json
{"responseCode":502,"message":"Connection refused: tp-volk.e2e.ch/10.110.120.192:10013"}
```
=> Improve gateway logging and hide sensitive data

manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/OrganizationResourceImpl.java, manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/util/SwaggerWsdlHelper.java, tools/server-all/pom.xml
When i downloading wsdl definitions i realized that only one endpoint was replaced (soap:address) by gateway endpoint, but in some SOAP web services (all of Microsoft .net), wsdl returns 2 endpoints one for soap 1.0 and other for soap 1.2.
Example:
`  <wsdl:service name="Service">
<wsdl:port binding="tns:ServiceSoap" name="ServiceSoap">
<soap:address location="https://localhost:8443/apiman-gateway/TEST/TEST2/1.0"/>
</wsdl:port>
<wsdl:port binding="tns:ServiceSoap12" name="ServiceSoap12">
<soap12:address location="http://<mylocalserver>/my-service.asmx"/>
</wsdl:port>
</wsdl:service>
`
I added some changes on SwaggerWsdlHelper and the definition was show correct.
`  <wsdl:service name="Service">
<wsdl:port binding="tns:ServiceSoap" name="ServiceSoap">
<soap:address …
=> Soap12 endpoint replacement

manager/ui/war/plugins/api-manager/ts/policies.ts
Just a little fix for `undefined` handling, otherwise we set always the `MAX_SAVE_INTEGER` value as default if you add a new policy
=> Rate Limiting Policy: Handle undefined

gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/InMemoryRegistry.java, gateway/engine/filesystem/README.md, gateway/engine/filesystem/pom.xml, gateway/engine/filesystem/src/main/java/io/apiman/gateway/engine/filesystem/LocalFileRegistry.java, gateway/engine/filesystem/src/main/java/io/apiman/gateway/engine/filesystem/model/RegistryWrapper.java, gateway/engine/filesystem/src/test/java/io/apiman/gateway/engine/filesystem/LocalFileRegistryTest.java, gateway/engine/filesystem/src/test/resources/populated-registry.json, gateway/engine/pom.xml, gateway/platforms/war/pom.xml, pom.xml
Adds local file based registry implementation.
This allows the Gateway to run in 'headless' mode, without an external backing store. This is particularly useful when immutability is preferred, such as when using a GitOps approach.
It is also particularly valuable when rolling deployments are required, where different instances of the gateway may be running at the same time with different, versioned, configurations, where pointing to a single backing store would be problematic.
Set the registry implementation and path to the registry:
```
apiman-gateway.registry=io.apiman.gateway.engine.filesystem.LocalFileRegistry
apiman-gateway.registry.registry-path=/path/to/registry.json
```
The registry JSON can be created by using [apiman-cli](https://github.com/apiman/apiman-cli), for example;
``` …
```
=> Adds local file registry implementation.

gateway/engine/ispn/src/main/java/io/apiman/gateway/engine/ispn/InfinispanBackingStore.java, gateway/engine/redis/src/main/java/io/apiman/gateway/engine/redis/common/RedisBackingStore.java, gateway/engine/storage-common/src/main/java/io/apiman/gateway/engine/storage/component/AbstractCacheStoreComponent.java, gateway/engine/storage-common/src/main/java/io/apiman/gateway/engine/storage/store/IBackingStore.java, gateway/engine/storage-common/src/main/java/io/apiman/gateway/engine/storage/store/MapBackingStore.java
Passes through the cache TTL to underlying backing store.
Some backing stores require that the TTL be set on a per entry basis. Not setting them per entry, for some implementations, means that no TTL is set and entries persist forever 🤦 
This change flows through to the relevant implementations that support it; in particular ISPN and Redis. Note: the non-production `Map` based implementation never supported expiry, and this change doesn't affect the semantics.
=> Passes through cache TTL to underlying backing store

gateway/engine/filesystem/src/main/java/io/apiman/gateway/engine/filesystem/LocalFileRegistry.java, gateway/engine/filesystem/src/test/java/io/apiman/gateway/engine/filesystem/LocalFileRegistryTest.java
We discovered that the LocalFileRegistryTest cannot properly load resources in a project path with signs which get url encoded within the class.getResource method (see [stackoverflow](https://stackoverflow.com/questions/8928661/how-to-avoid-getting-url-encoded-paths-from-url-getfile/8928965)).
We found this out on our jenkins system which creates under some circumstances a workspace folder with an @ symbol in the path (see [jenkins issue](https://issues.jenkins-ci.org/browse/JENKINS-30231)).
=> Avoid url encoding resource access in LocalFileRegistry

manager/ui/war/src/main/java/io/apiman/manager/ui/server/beans/BearerTokenCredentialsBean.java, manager/ui/war/src/main/java/io/apiman/manager/ui/server/kc/KeyCloakBearerTokenGenerator.java, pom.xml
We use keycloak in a much newer version (10.0.2) for a long period now.
So I think it's save to update to this version for the apiman project as well :)
=> Update keycloak to 10.0.2

common/plugin/pom.xml, distro/tomcat8/src/main/resources/overlay/conf/apiman.properties, distro/wildfly10/src/main/resources/overlay/standalone/configuration/apiman.properties, distro/wildfly11/src/main/resources/overlay/standalone/configuration/apiman.properties, manager/api/exceptions/src/main/java/io/apiman/manager/api/rest/exceptions/mappers/RestExceptionMapper.java
The Manger REST API does always send the complete stacktrace:
```java
{
"type": "NotAuthorizedException",
"errorCode": -1,
"message": "Access denied.",
"moreInfoUrl": null,
"stacktrace": "io.apiman.manager.api.rest.exceptions.NotAuthorizedException: Access denied.\n\tat io.apiman.manager.api.rest.exceptions.util.ExceptionFactory.notAuthorizedException(ExceptionFactory.java:55)\n\tat io.apiman.manager.api.security.impl.AbstractSecurityContext.checkAdminPermissions(AbstractSecurityContext.java:187)\n\tat 
...
```
We added the new option to enable this with `apiman-manager.config.features.rest-response-should-contain-stacktraces=false`, because most of the time you don't need the stacktrace.
Because the properties files from wildfly differ I added the missing content in a separate commit.
=> Disable stacktrace for manager REST responses

manager/ui/war/plugins/api-manager/html/admin/admin-export.html, manager/ui/war/plugins/api-manager/html/admin/admin-gateways.html, manager/ui/war/plugins/api-manager/html/admin/admin-plugins.html, manager/ui/war/plugins/api-manager/html/admin/admin-policyDefs.html, manager/ui/war/plugins/api-manager/html/admin/admin-roles.html, manager/ui/war/plugins/api-manager/html/admin/admin_tabs.include
Hi @EricWittmann,
I looked into the plugins page and reverted a commit from Marc from 2018.
This fixes the routing but breaks the design (two buttons instead of nice tabs).
I think the design is not that important for the moment.
The only problem now is that the 2.0.0 Plugins can not be found.
But I am not sure if this was caused by the release pipeline (they are uploaded to maven central?)?
=> Fix #907 - broken plugin page

gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/PollCachingEsRegistry.java
We had found an issue with the `PollingEsRegistry` which overwrites the index creation of the `EsRegistry`. So indices are missing if the `PollingEsRegistry` is used instead of the `EsRegistry`
=> PollingEsRegistry overwrites EsRegistry indices on index creation

distro/data/src/main/resources/bootstrap/default-gateway.json, distro/data/src/main/resources/ddls/apiman_h2.ddl, distro/data/src/main/resources/ddls/apiman_mysql5.ddl
With the commit of the devportal, I pushed some broken ddls (probably from my testing testing phase).
The change of the date in the initial data will force an update of the gateway password.
=> Rollback ddl files and force update of gateway password

.github/workflows/verify.yaml, distro/wildfly/pom.xml
I would like to push the docker image of wildfly on each master build.
I am not sure if this already works because I am not very familiar with github actions.
@EricWittmann Can you please take a look at it? :)
=> Push wildfly docker image on master build

gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/DefaultPluginRegistry.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/engine/VertxPluginRegistry.java
Use the url syntaxe like http://user:password@maven.repository to make an authentification on private nexus.
Impacted in Servlet plateform and Vertx
=> FIX 932 : take basic authentication from userInfo to request the maven repository

gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/DefaultPolicyErrorWriter.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/connector/HttpConnector.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/http/HttpPolicyAdapter.java
Hi together and a happy new year!
I did some little improvements on the vert.x part to prevent some unhandled exceptions that are thrown if we try to write to a closed response. So now there is a check if the response is closed and also I tried to reduce the duplicate lines of code here (by adding the class `DefaultApiClientResponse`).
This should prevent:
```java
[ERROR] 2020-06-04 12:34:52.346 [vert.x-eventloop-thread-2] ContextImpl - Unhandled exception
java.lang.IllegalStateException: Response has already been written
at io.vertx.core.http.impl.HttpServerResponseImpl.checkValid(HttpServerResponseImpl.java:572) ~[apiman-gateway.jar:?]
at io.vertx.core.http.impl.HttpServerResponseImpl.setChunked(HttpServerResponseImpl.java:138) ~[apiman-gateway.jar:?]
at …
```
=> fix(vertx): Check response before writing

common/es/src/main/java/io/apiman/common/es/util/DefaultEsClientFactory.java
@svzieg and I needed a while to figure out that we wrongly configured `client.host`. So we made the log it a little bit clearer.
=> Make elasticsearch logging output clearer

.github/workflows/verify.yaml
When a build to master succeeds, deploy a snapshot to OSSRH. This is what we did previously when using Travis CI. We need this to ensure that apiman-plugins continues to work correctly (it builds off these snapshots).
Fixes #996
=> ci: deploy successful master builds as SNAPSHOT to ossrh

manager/test/api/pom.xml, pom.xml
A dependency is pulling in TestNG (a different test framework). Maven-surefire-plugin decided to only run TestNG and not JUnit. This meant it "successfully" ran zero tests, hence all is green.
Thanks to @volkflo for noticing this gremlin.
I believe this occurred back in the distant past, and Eric fixed it using this same method. It came back to me as I was digging into it!
Fixes #998
=> build: ensure manager-test junit tests run by surefire even when testng on classpath

common/es/src/main/java/io/apiman/common/es/util/AbstractClientFactory.java, common/es/src/main/java/io/apiman/common/es/util/DefaultEsClientFactory.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/common/config/VertxEngineConfig.java, gateway/test/src/test/java/io/apiman/gateway/test/junit/vertx3/EsResetter.java, gateway/test/src/test/java/io/apiman/gateway/test/junit/vertx3/Vertx3GatewayEsServerFactory.java, gateway/test/src/test/resources/test-configs/vertx3-es.json, gateway/test/src/test/resources/vertx3/conf-es.json
Rather than relying on a background ES instance, a factory manages the lifecycle of an Elasticsearch Testcontainer with randomised ports for the Vert.x Gateway integration testsuite.
This means that the environment does not need an ES instance running when executing these integration tests from Maven, IDE, CI, etc.
Run as `mvn test -Dapiman.gateway-test.config=vertx3-es`
Fixes #1010
=> test: Autostart Elastic Testcontainer for Vert.x ES integration tests

manager/ui/war/pom.xml, manager/ui/war/tomcat8/pom.xml, manager/ui/war/wildfly8/pom.xml, pom.xml, tools/server-all/pom.xml
Fixes #1005
Also fixes some security-related issues with Ant, but it does not appear they are relevant for our use-cases, as we only use Ant during build time (no runtime stuff). 
In theory, there are also some permissions changes it could make in $TMP, but they would require some real contortion to exploit. 
Anyway, better to fix it and not wonder :-).
=> build(deps): bump ant to 1.10.9 & manage version in root pom

manager/api/export-import/src/main/java/io/apiman/manager/api/exportimport/manager/ExportImportManager.java, manager/api/export-import/src/main/java/io/apiman/manager/api/exportimport/manager/StorageImportDispatcher.java, manager/api/export-import/src/main/resources/io/apiman/manager/api/exportimport/i18n/messages.properties, manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/SystemResourceImpl.java, manager/api/war/src/main/java/io/apiman/manager/api/war/WarApiManagerBootstrapperServlet.java, manager/test/api/src/test/resources/test-plan-data/import/001_import.resttest, manager/test/api/src/test/resources/test-plan-data/import/002_import-again.resttest, manager/test/api/src/test/resources/test-plan-data/import/003_import-with-developer.resttest, manager/test/api/src/test/resources/test-plan-data/migrate/001_import-1.2.2.Final.resttest, pom.xml, test/common/pom.xml, test/common/src/main/java/io/apiman/test/common/util/TestPlanRunner.java
The importer now logs the filename at startup.
To test variable content in text payloads, regular expressions were enabled.
For this jUnits AssertEqual was replaced by the Java regex compiler.
In rest tests with text payload, special characters must be escaped for the regex compiler.
=> Importer should log file name

gateway/test/src/test/java/io/apiman/gateway/test/junit/vertx3/Vertx3GatewayEsServerFactory.java, gateway/test/src/test/resources/vertx3/conf-es.json
Just a little improvement that should allow running the tests also inside a docker container.
=> Refactor: Allow to configure host for gateway testcontainer

pom.xml
We have not used the referenced repositories for a number of years.
=> build: Remove references to old maven repos

distro/vertx/src/main/resources/overlay/apiman-gateway.sh
There is a change with java 9+ about the debugger.
This change allows debugging docker containers.
=> fix(gateway-vertx): debug with java 9+

manager/ui/war/plugins/api-manager/ts/api/api-def.ts, manager/ui/war/plugins/api-manager/ts/api/api-policies.ts, manager/ui/war/plugins/api-manager/ts/client/client-policies.ts
After removing a policy from a client/api or reloading the Re-Register/Re-Publish Button should be enabled without the need to reload the page
Therefore modifiedOn and modifiedBy need to be updated.
=> fix: refresh re-register / re-publish button after changes

.github/workflows/verify.yaml
IMO this makes to log very hard to read if you are searching for errors because of an updated dependency.
Let me know what you think about this? :)
=> ci: Remove Maven build flag for parallel builds

distro/vertx/src/main/resources/overlay/apiman-gateway.sh
Was prompted to add the quotes by shellcheck, but I think in this situation it was incorrect to use the recommended quotations because I want the arguments to expand.
=> fix(distro-vertx): remove argument quotes breaking launch script

gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/HttpConnectorFactory.java, gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/ok/HttpURLConnectionImpl.java, gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/components/jdbc/JdbcTestSuite.java, gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/components/jdbc/SpecHelpers.java, gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/components/jdbc/suitetests/CreateTableTest.java, gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/components/jdbc/suitetests/QueryTest.java, pom.xml
This is a slightly risky update because the internal OkHttp model was changed quite significantly between 2.4.0 and 2.7.5 to be more streaming-oriented. I'm not 100% sure I've selected appropriately equivalent methods. We should test this well before merging in.
The next stage will be bumping all the way up to the very latest OkHttp (or whatever we deem appropriate), but I suspect that will take a bit longer!
=> build(deps): bump OkHttp from 2.4.0 to 2.7.5

common/config/pom.xml, common/config/src/main/java/io/apiman/common/config/SystemPropertiesConfiguration.java, pom.xml
We use commons-lang3 everywhere now. Seems this was just hanging around.
=> build(deps): remove unused commons-lang v2 dep

gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/EsRegistry.java, manager/api/es/src/main/java/io/apiman/manager/api/es/EsStorage.java
Let's try this out... We can likely pick and choose which is appropriate.
=> refactor(es): revert waitUntil index refresh strategy. Use immediate.

pom.xml
build(deps): bump maven-dependency-plugin from 2.10 to 3.1.2
Bumps [maven-dependency-plugin](https://github.com/apache/maven-dependency-plugin) from 2.10 to 3.1.2.
- [Release notes](https://github.com/apache/maven-dependency-plugin/releases)
- [Commits](https://github.com/apache/maven-dependency-plugin/compare/maven-dependency-plugin-2.10...maven-dependency-plugin-3.1.2)
build(deps): bump version.org.hibernate
Bumps `version.org.hibernate` from 5.4.28.Final to 5.4.30.Final.
Updates `hibernate-core` from 5.4.28.Final to 5.4.30.Final
- [Release notes](https://github.com/hibernate/hibernate-orm/releases)
- [Changelog](https://github.com/hibernate/hibernate-orm/blob/5.4.30/changelog.txt)
- [Commits](https://github.com/hibernate/hibernate-orm/compare/5.4.28...5.4.30)
Updates …
=> build(deps): bump maven-dependency-plugin, hibernate, ant

distro/ddl/pom.xml, pom.xml
build(deps): bump version.org.junit.jupiter from 5.4.2 to 5.7.1
Bumps `version.org.junit.jupiter` from 5.4.2 to 5.7.1.
Updates `junit-jupiter-api` from 5.4.2 to 5.7.1
- [Release notes](https://github.com/junit-team/junit5/releases)
- [Commits](https://github.com/junit-team/junit5/compare/r5.4.2...r5.7.1)
Updates `junit-jupiter-params` from 5.4.2 to 5.7.1
- [Release notes](https://github.com/junit-team/junit5/releases)
- [Commits](https://github.com/junit-team/junit5/compare/r5.4.2...r5.7.1)
Updates `junit-jupiter-engine` from 5.4.2 to 5.7.1
- [Release notes](https://github.com/junit-team/junit5/releases)
- [Commits](https://github.com/junit-team/junit5/compare/r5.4.2...r5.7.1)
build(deps): bump snakeyaml from 1.13 to 1.28
Bumps [snakeyaml](https://bitbucket.org/asomov/snakeyaml) from 1.13 …
=> build(deps): bump junit 5, snakeyaml, guava, & apache ldap-api

distro/tomcat/pom.xml, distro/tomcat/src/main/assembly/overlay.xml, distro/tomcat/src/main/resources/overlay/bin/setenv.sh, distro/tomcat/src/main/resources/overlay/log4j2/conf/log4j2-tomcat.xml, pom.xml
Note, I've left the JSON logging option enabled so it's easier for people to try out, but we'll ship with human-readable. I'll do a commit before we merge changing it back to 'default'.
=> feat(distro-tomcat): use log4j2 by default to enable easy unified JSON logging

manager/pom.xml, parent/pom.xml
Ensure that TestNG does not barge in at any point transitively.
Also seems that junit5 dependencies declared in unnecessarily in certain places were causing some tests not to run.
I tried extensively to follow the instructions/examples from the surefire examples, but they didn't seem to work for me 🤷🏻‍♂️.
In future we should just move to JUnit 5.
=> build(parent): force junit4 as default for surefire plugin

parent/pom.xml
Batched dependency updates.
---
build(deps): bump mockito-core from 3.10.0 to 3.11.0 in /parent
Bumps [mockito-core](https://github.com/mockito/mockito) from 3.10.0 to 3.11.0.
- [Release notes](https://github.com/mockito/mockito/releases)
- [Commits](https://github.com/mockito/mockito/compare/v3.10.0...v3.11.0)
---
- dependency-name: org.mockito:mockito-core
update-type: version-update:semver-minor
...
Signed-off-by: dependabot[bot] <support@github.com>
build(deps): bump icu4j from 68.2 to 69.1 in /parent
Bumps [icu4j](https://github.com/unicode-org/icu) from 68.2 to 69.1.
- [Release notes](https://github.com/unicode-org/icu/releases)
- [Commits](https://github.com/unicode-org/icu/commits)
---
- …
=> build(deps): bump mockito-core, icu4j, jandex, & hibernate

parent/pom.xml
Rollup update of...
---
build(deps): bump version.org.elasticsearch in /parent
Bumps `version.org.elasticsearch` from 7.13.0 to 7.13.1.
Updates `elasticsearch` from 7.13.0 to 7.13.1
- [Release notes](https://github.com/elastic/elasticsearch/releases)
- [Commits](https://github.com/elastic/elasticsearch/compare/v7.13.0...v7.13.1)
Updates `elasticsearch-rest-high-level-client` from 7.13.0 to 7.13.1
- [Release notes](https://github.com/elastic/elasticsearch/releases)
- [Commits](https://github.com/elastic/elasticsearch/compare/v7.13.0...v7.13.1)
---
- dependency-name: org.elasticsearch:elasticsearch
update-type: version-update:semver-patch
- dependency-name: org.elasticsearch.client:elasticsearch-rest-high-level-client
dependency-type: …
=> build(deps): bump elasticsearch, redisson, json-unit-assertj

parent/pom.xml
build(deps): bump version.org.elasticsearch in /parent
Bumps `version.org.elasticsearch` from 7.13.1 to 7.13.2.
Updates `elasticsearch` from 7.13.1 to 7.13.2
- [Release notes](https://github.com/elastic/elasticsearch/releases)
- [Commits](https://github.com/elastic/elasticsearch/compare/v7.13.1...v7.13.2)
Updates `elasticsearch-rest-high-level-client` from 7.13.1 to 7.13.2
- [Release notes](https://github.com/elastic/elasticsearch/releases)
- [Commits](https://github.com/elastic/elasticsearch/compare/v7.13.1...v7.13.2)
---
- dependency-name: org.elasticsearch:elasticsearch
update-type: version-update:semver-patch
- dependency-name: org.elasticsearch.client:elasticsearch-rest-high-level-client …
=> build(deps): elasticsearch, hibernate, commons-io, mockito, Maven dependency plugin

.github/workflows/verify.yaml
To reduce the duration of the CI, yarn should also be cached in addition to mvn.
Closes #1026
=> ci: add yarn caching

common/config/src/main/java/io/apiman/common/config/options/exceptions/BadOptionConfigurationException.java, manager/api/war/src/main/java/io/apiman/manager/api/war/WarCdiFactory.java
`ESMetricsAccessor` should always use `config#getMetricsESClientFactoryConfig` *not*
`config#getStorageESClientFactoryConfig`.
Fixes #1346
=> fix(manager-api): use correct configuration accessor for ESMetricsAccessor

parent/pom.xml, tools/i18n/pom.xml
Bumps `version.org.elasticsearch` from 7.13.2 to 7.13.4.
Updates `elasticsearch` from 7.13.2 to 7.13.4
- [Release notes](https://github.com/elastic/elasticsearch/releases)
- [Commits](https://github.com/elastic/elasticsearch/compare/v7.13.2...v7.13.4)
Updates `elasticsearch-rest-high-level-client` from 7.13.2 to 7.13.4
- [Release notes](https://github.com/elastic/elasticsearch/releases)
- [Commits](https://github.com/elastic/elasticsearch/compare/v7.13.2...v7.13.4)
---
- dependency-name: org.elasticsearch:elasticsearch
update-type: version-update:semver-patch
- dependency-name: org.elasticsearch.client:elasticsearch-rest-high-level-client
update-type: version-update:semver-patch
...
Signed-off-by: …
=> build(deps): batched minor and patch dependency updates

manager/api/core/src/test/java/io/apiman/manager/api/core/plugin/AbstractPluginRegistryTest.java, manager/test/api/src/main/java/io/apiman/manager/test/junit/ManagerRestTester.java, manager/test/api/src/main/java/io/apiman/manager/test/server/ApiManagerTestPluginRegistry.java, manager/test/api/src/test/java/io/apiman/manager/test/PluginsTest.java, manager/test/api/src/test/resources/test-plans/plugins-testPlan.xml
… 
As I discovered through a tortuous process, multiple ManagerRestTester JUnit testrunner instances
were being initialised simultaneously. This meant that the code to set environment variables via
`@RestTestSystemProperties`, which is triggered in the constructor, was running in each
ManagerRestTester instance one after another(long before the test code ran). Hence, the environment
variables were overriding each other in surprising and confusing ways (i.e. dependent on
not-entirely-deterministic ordering).
This was compounded by (for whatever reason) CI running the tests in a different order to everyone
else's dev setup, which took a while to notice.
As a bonus, `@RestTestSystemProperties` can now be a reference to a Java resource instead of just a
file. If the file lookup fails, it will …
=> test: fix improper init of ManagerRestTester JUnit testrunner causing Sys props to overwrite one another

manager/api/beans/src/main/java/io/apiman/manager/api/beans/policies/PolicyDefinitionTemplateBean.java, manager/api/es/src/test/java/io/apiman/manager/api/es/EsMarshallingTest.java
PolicyDefinitionTemplate is referenced in a Set from PolicyDefinitionBean.
The lack of #equals and #hashCode can cause Hibernate to duplicate the templates and write them back to the the database under certain circumstances.
Once the bug is triggered, the templates will often double in size on each occasion, which causes exponential growth.
Fixes: #1566
=> fix(manager-api): policyDefinitionTemplate missing #equals and #hashCode

manager/api/jpa/src/main/java/io/apiman/manager/api/jpa/JpaStorage.java
The #getApiDefinition JPA query used in export was mistakenly missing the API version part of the
WHERE/AND predicate. This meant that if two different API versions had schemas attached, then the
query would return multiple entries.
Fixes #1567
=> fix(manager-api-jpa): include API version in query fetching API definition

manager/api/jpa/src/main/java/io/apiman/manager/api/jpa/blobstore/SqlBlobStoreService.java, manager/api/jpa/src/main/java/io/apiman/manager/api/jpa/model/outbox/TransactionalOutboxService.java, manager/api/rest-impl/src/main/java/io/apiman/manager/api/events/EventService.java, manager/api/rest-impl/src/main/java/io/apiman/manager/api/service/ImportExportService.java
During an import we use the same code paths as a 'real' user interacting with the system,
this causes events to be replayed that would have been generated when the original interaction
occurred. An unwanted side effect of this is that notifications are sent again, which can cause
notifications to be resurrected (with misleading timestamps).
Fixes #1557
=> fix(manager-api): disable event dispatch during import to prevent event & notification replay

manager/ui/war/package.json, manager/ui/war/yarn.lock
build(deps-dev): bump webpack-bundle-analyzer in /manager/ui/war
Bumps [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) from 4.4.2 to 4.5.0.
- [Release notes](https://github.com/webpack-contrib/webpack-bundle-analyzer/releases)
- [Changelog](https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/master/CHANGELOG.md)
- [Commits](https://github.com/webpack-contrib/webpack-bundle-analyzer/compare/v4.4.2...v4.5.0)
---
- dependency-name: webpack-bundle-analyzer
dependency-type: direct:development
update-type: version-update:semver-minor
...
Signed-off-by: dependabot[bot] <support@github.com>
build(deps-dev): bump webpack-dev-server in /manager/ui/war
Bumps [webpack-dev-server](https://github.com/webpack/webpack-dev-server) …
=> build(dev-deps): update webpack, webpack-bundle-analyzer, & webpack-dev-server

manager/api/jpa/src/main/java/io/apiman/manager/api/jpa/JpaStorage.java
If orgId not included multiple schemas may be returned if there are mirrored setups in multiple orgs. This will cause errors during export, for example.
Fixes #1642
=> fix(manager-api-jpa): orgId must be part of #getApiDefinition select to ensure uniqueness

tools/dummy-last-module/pom.xml
Due to NEXUS-9138, if the last module in the Maven reactor has skipNexusStagingDeployMojo=true,
then deployment of *all* modules will be skipped.
For whatever reason this has been marked as WONTFIX, so we're going to have to work around it
by adding a dummy empty module as the last item in the reactor with skipNexusStagingDeployMojo=false
See https://issues.sonatype.org/browse/NEXUS-9138
Fixes: #1650
=> build: add dummy last Maven module to work around nexus-staging-plugin skipping all deployments

manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/BlobResourceImpl.java
A filename is generated for any blob uploaded, and it included the username. This has been removed.
Closes: #1654
=> refactor(manager-api): remove username from uploaded blob's generated filename

manager/ui/war/plugins/api-manager/html/headers/community.include, manager/ui/war/plugins/api-manager/ts/configuration.ts, manager/ui/war/plugins/api-manager/ts/navbar.ts
Backend provides config that lets us know whether the notifications subsystem is enabled
or not.
```
var APIMAN_CONFIG_DATA = {
<snip>
"ui" : {
"header" : "apiman",
"metrics" : true,
"notifications": true <-- backend indicating notification subsystem is active 
}
<snip>
};
```
Closes: #1671
=> feat(ui): hide notifications icon if notifications subsystem disabled

parent/pom.xml
Also match Netty version, bump 4.1.67 to 4.1.69
=> build(deps): bump Vert.x from 3.9.8 to 3.9.10

distro/wildfly/pom.xml, distro/wildfly/src/main/resources/overlay/standalone/configuration/standalone-apiman.xml, gateway/platforms/war/wildfly8/api/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, gateway/platforms/war/wildfly8/gateway/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, manager/api/war/wildfly8/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, manager/ui/war/wildfly8/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, parent/pom.xml, pom.xml, tools/server-all/pom.xml
refactor: Align Apiman with  Keycloak 15.1.1, which required upgrading to WildFly 23.0.2
This mostly included reworking the WildFly quickstart distro's `standalone-apiman.xml` config (again).
Now using a self-signed cert instead of default certificate. Could there be unintended consequences to this? For example, it is not explicitly linked to the apiman keystore, so could that mess with existing configs.
=> refactor(distro-wildfly): align Apiman to Keycloak 15.1.1, which required upgrading to WildFly 23.0.2

parent/pom.xml
---
build(deps): bump version.org.jboss.resteasy in /parent
Bumps `version.org.jboss.resteasy` from 3.15.1.Final to 3.15.3.Final.
Updates `resteasy-jaxrs` from 3.15.1.Final to 3.15.3.Final
Updates `resteasy-vertx` from 3.15.1.Final to 3.15.3.Final
Updates `resteasy-jackson2-provider` from 3.15.1.Final to 3.15.3.Final
Updates `resteasy-jaxb-provider` from 3.15.1.Final to 3.15.3.Final
Updates `resteasy-cdi` from 3.15.1.Final to 3.15.3.Final
- [Release notes](https://github.com/resteasy/Resteasy/releases)
- [Commits](https://github.com/resteasy/Resteasy/compare/3.15.1.Final...3.15.3.Final)
---
- dependency-name: org.jboss.resteasy:resteasy-jaxrs
update-type: version-update:semver-patch
- dependency-name: …
=> build(deps): bump resteasy, mvel2, testcontainers, and ldapsdk

manager/api/beans/src/main/java/io/apiman/manager/api/beans/developers/DeveloperApiVersionBeanDto.java, manager/api/beans/src/main/java/io/apiman/manager/api/beans/developers/DeveloperBean.java, manager/api/beans/src/main/java/io/apiman/manager/api/beans/developers/DeveloperMapper.java, manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/DeveloperResourceImpl.java, manager/api/rest/src/main/java/io/apiman/manager/api/rest/IDeveloperResource.java
To avoid Jackson IdentityInfo references leaking to presentation layer we add a simple DTO.
=> refactor(manager-api-rest): use DTO for old devportal #getAllApiVersions

common/es/src/main/resources-filtered/io/apiman/common/es/util/apiman-es.properties, parent/pom.xml, test/common/src/main/java/io/apiman/test/common/es/EsTestUtil.java
Changed the ability to run opensearch instead of opendistro if you run apiman test suites
Closes #1825
=> replace "Opendistro for Elasticsearch" with "Opensearch"

distro/data/src/main/resources/ddls/apiman_postgresql9.ddl, distro/ddl/src/main/liquibase/current/201-postgres-add-bool-function.xml
Previously we were manually inserting the intotobool functions into our DDL, which made it easy to
accidentally overwrite when we updated our data model.
This is now done automatically, so should reduce mistakes in this area.
Closes #1845
=> refactor(distro-ddl): put Postgres bool functions into Liquibase definition

gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/ApiRequest.java, gateway/engine/policies/src/main/java/io/apiman/gateway/engine/policies/URLRewritingPolicy.java, gateway/engine/policies/src/test/java/io/apiman/gateway/engine/policies/URLRewritingPolicyTest.java
- fix(gateway-engine-policies): check for null request path in URLRewritingPolicy
- test(gateway-engine-policies): add test for empty resource on URLRewritingPolicy
Fixes #1828
=> fix(gateway-engine-policies): check for null request path in URLRewritingPolicy

manager/api/beans/src/main/java/io/apiman/manager/api/beans/apis/ApiVersionBean.java, manager/api/beans/src/main/java/io/apiman/manager/api/beans/apis/UpdateApiVersionBean.java
With previous code `exposeInPortal` would default to false, and hence if the UI tried to submit a
patch update it could accidentally be set to `false` automatically.
Fixes #1861
=> fix(manager-api-beans): UpdateApiVersionBean should use Boolean wrapper to allow null (indicates no update)

gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/EsMetrics.java
If ES goes down the buffer will eventually fill up, and the calling thread will be blocked by the
BlockingQueue. Although this is rare, it can cause the caller to be blocked forever.
This is a particular problem for the Vert.x gateway where it is not acceptable for calling threads
to be blocked for long periods of time.
Fixes: #1884
=> feat(metrics): drop new RecordMetrics in ESMetrics if buffer is full, rather than blocking

common/es/src/main/java/io/apiman/common/es/util/AbstractEsComponent.java, common/es/src/main/java/io/apiman/common/es/util/ApimanEsClientOptionsParser.java, gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/EsCacheStoreComponent.java, gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/EsMetrics.java, gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/EsRateLimiterComponent.java, gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/EsRegistry.java, gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/EsSharedStateComponent.java, gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/PollCachingEsRegistry.java, manager/api/es/src/main/java/io/apiman/manager/api/es/EsStorage.java, manager/ui/war/package.json, manager/ui/war/yarn.lock
Add backwards compatibility with `client.index` key alias.
Fixes: #1451
=> fix(metrics-es): use custom index prefix without unnecessary underscore

parent/pom.xml
- [build(deps): bump Jackson from 2.12.4 to 2.12.6.1](https://github.com/apiman/apiman/commit/bf324ea63ce3e1d3004ccf13836712ac425262b5)
- [build(deps): bump ipaddress from 5.3.3 to 5.3.4](https://github.com/apiman/apiman/commit/9d209c3643c9f6711fdb68fb54a44a40ebc297a9)
- [build(deps): bump ldapsdk from 6.0.3 to 6.0.4](https://github.com/apiman/apiman/commit/7beed87929d46446b502222ccb92e2bc4f97f291)
- [build(deps): bump Guava 30.1.1-jre to 31.1-jre](https://github.com/apiman/apiman/commit/86bbd59fde85b9ea9bf6178b1df7c53e31d5e566)
- [build(deps): bump log4j2 to 2.17.2](https://github.com/apiman/apiman/commit/2b86183ddf2766e6757cb7384d4ded352a68f94a)
- [build(deps): bump jdbi from 3.21.0 to 3.28.0](https://github.com/apiman/apiman/commit/c7549a80b341e0998dda35168486f5f08f8a82d1)
- …
=> build(deps): minor Java dependency update bundle 

manager/ui/war/plugins/api-manager/html/api/api-devportal.html, manager/ui/war/plugins/api-manager/ts/api/api-devportal.ts
Switched to the PlanSummary beans in the ui to display the correct name and discoverability level.
Changed the onChange method to get the "real" plan bean updated from the summary bean before the update request is sent
Closes: #2002
=> fix(ui): show correct discoverability on the plans

gateway/platforms/vertx3/vertx3/pom.xml
We should make a more optimal one using the Vert.x-specific async JDBC libraries soon
In general, only the polling JDBC library should be used to avoid blocking issues. Even then, it's probably not perfect.
I'll make a version with the Vert.x JDBC non-blocking library, if possible.
=> build(gateway-platforms-vertx3): ensure Vert.x gateway can use JDBC registry

manager/api/war/tomcat8/src/main/webapp/WEB-INF/web.xml, manager/api/war/wildfly8/src/main/webapp/WEB-INF/web.xml
Because of a missing entry in the web.xml (wildfly and tomcat) the loggedIn-check for uploading images didnt work properly.
We added the entry for the /blobs endpoint back in, to fix the loggedIn-check.
Closes: #2049
=> fix(manager-api): fix image upload

manager/ui/war/plugins/api-manager/html/api/api-contracts.html
Due to a wrong permission check on the approve contract button only user with the IDM role 'apiadmin' were able to approve contracts.
We fixed this permission check, that it only checks the apiman permission 'planAdmin' now. User with the IDM role 'apiadmin' will still bypass this permission check.
Closes: #2046
=> fix(ui): fix permission check of contract approve button

manager/api/rest-impl/src/main/java/io/apiman/manager/api/service/OrganizationService.java, manager/test/api/src/test/resources/test-plan-data/members/auditing/001_activity.resttest, manager/test/api/src/test/resources/test-plan-data/members/manage/004_grant-user1-api.resttest, manager/test/api/src/test/resources/test-plan-data/members/manage/005_grant-user2-api.resttest, manager/test/api/src/test/resources/test-plan-data/members/manage/006_get-members.resttest, manager/test/api/src/test/resources/test-plan-data/members/manage/007_revoke-user2.resttest, manager/test/api/src/test/resources/test-plan-data/members/manage/008_get-members.resttest
By changing from `IUserResource` to the `UserService` directly we avoid the `checkIfUserIsCurrentUser` in the security context.
This check was a problem during granting memberships as non-admin user because it was not allowed to get the user object as non-admin / as non-being the user itself.
Closes: #2069
=> fix(manager-api): grant membership as non-admin user

manager/ui/war/plugins/api-manager/html/api/api-devportal.html, manager/ui/war/plugins/api-manager/ts/api/api-devportal.ts
Partially reverted changes that got introduced with "fix(ui): show correct discoverability on the plans" (a9552462f86fa2a5d753ffb670d4f8f2c54afb6f).
Changes of the `requiresApproval` were lost because the wrong entity was modified (ApiPlanSummaryBeans instead of ApiPlanBeans).
The summary beans are now only used to display a `planDescription` and the `planName` as these fields are not available in the ApiPlanBean.
Closes: #2071
=> fix(ui): restore "requires approval" functionality on devportal tab

manager/ui/war/plugins/api-manager/ts/policies.ts
According to docs this is not necessary, but seems it can trigger issues on page re-entry with
the current dependency versions being used.
=> fix(ui): ensure JSON schema forms renderer ready before attempting to render

common/plugin/src/main/java/io/apiman/common/plugin/Plugin.java, common/plugin/src/main/java/io/apiman/common/plugin/PluginClassLoader.java, gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/DefaultPluginRegistry.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/logging/VertxLoggerDelegate.java, manager/api/beans/src/main/java/io/apiman/manager/api/beans/apis/ApiVersionBean.java
… behaviour
Finalize is deprecated, in part because it causes surprising behaviour whereby
objects can be GCed far earlier than the programmer might expect.
This causes many subtle bugs.
This patch removes finalize by using `Closeable` and `AutoCloseable`, although
there may be some edge cases we haven't picked up that require explicit close
now and could cause memory leaks in certain circumstances.
=> fix(common-plugin): remove in plugin loader code due to unpredictable behaviour

manager/api/rest-impl/src/main/java/io/apiman/manager/api/notifications/email/EmailSender.java
`setStartTLSRequired` is an addition that can be enabled to disconnect if the server does not support STARTTLS at all.
Closes: #2090
=> fix(manager-api-notifications): correctly enable STARTTLS if `startTLSMode` is set to `REQUIRED|OPTIONAL`

gateway/engine/core/pom.xml, gateway/engine/core/src/main/java/io/apiman/gateway/engine/metrics/BatchedMetricsConsumer.java, parent/pom.xml
A generic batched metrics consumer that should allow batched, thread-safe non-blocking metrics
ingestion by many different metrics implementations, rather than reinventing this pattern many
times.
This implementation runs as fast as it can, using a spin-wait worker thread that polls a
non-blocking queue. It passes these metrics to a call-handler which may then go and perform
actions such as serializing and transmitting those metrics.
This implementation does not have a minimum batch size nor minimum polling interval.
=> feat(gateway-engine-core): thread-safe batched non-blocking metrics consumer

distro/conf/src/main/resources/notifications/email/notification-template-index.json, distro/conf/src/main/resources/notifications/email/tpl/de/apiman.client.contract.request.user.html, distro/conf/src/main/resources/notifications/email/tpl/de/apiman.client.contract.request.user.txt, distro/conf/src/main/resources/notifications/email/tpl/en/apiman.client.contract.request.user.html, distro/conf/src/main/resources/notifications/email/tpl/en/apiman.client.contract.request.user.txt, distro/conf/src/test/java/DefaultTemplatesTest.java, manager/api/rest-impl/src/main/java/io/apiman/manager/api/notifications/email/handlers/ContractRequestUserEmailNotification.java, manager/api/rest-impl/src/main/java/io/apiman/manager/api/notifications/producers/ContractRequestUserNotificationProducer.java, manager/test/api/src/test/resources/test-plan-data/approvals/notifications/002_bwayne-notifications.resttest, manager/test/api/src/test/resources/test-plan-data/approvals/notifications/004_bwayne-list-notifications-all-read.resttest, manager/test/api/src/test/resources/test-plan-data/approvals/notifications/006_bwayne-count-all-notifications.resttest, manager/ui/war/plugins/api-manager/ts/notification/notificationmapper.service.ts
Add a new notification that is sent to the user who signs up to an API. This is sent in addition to the approval notifications to all plan admins.
Closes: #1852
=> feat(notifications): add email to user on api signup

common/logging/core/pom.xml, common/logging/core/src/main/java/io/apiman/common/logging/ApimanLoggerFactoryRegistry.java, parent/pom.xml
Reflections library was causing various issues, varying from incompatibilities with newer versions
of Java, through to silent errors in the case of certain exceptions (which was breaking logging
discovery).
=> refactor(common-logging): remove `Reflections` library, replace with `classgraph` library

manager/api/rest-impl/src/main/java/io/apiman/manager/api/service/ApiService.java
Avoid unnecessary `MalformedURLException`s by checking the string first.
Closes: #2213
=> fix(manager-api): add isBlank check to `definitionUrl`

manager/ui/war/plugins/api-manager/html/directives/policyList.html, manager/ui/war/plugins/api-manager/ts/directives.ts, manager/ui/war/plugins/api-manager/ts/plan/plan-policies.ts
A locked plan cannot be altered, therefore the delete button for a policy should also not be visible. This also applies for retired APIs.
Fixing the problem by passing the entity check from parent to child component.
Closes: #2030
=> fix(ui): only show remove button if removal is possible

manager/ui/war/plugins/api-manager/ts/api/api-contracts.ts
If an error occurs during the contract approval/rejection, the error is only logged but not shown to the user.
Therefore we have added the error page to the approval/rejection.
=> feat(ui): add approval error page

manager/api/jpa/src/main/java/io/apiman/manager/api/jpa/AbstractJpaStorage.java, manager/test/api/src/test/resources/test-plan-data/searching/queries/apis/013_query-integer-field-issue-2283.resttest, manager/test/api/src/test/resources/test-plans/searching-testPlan.xml
Previously, we were assuming all the fields were `Long`. In some cases they are `Integer` and this causes a data type mismatch with certain target fields.
Fixes: #2283
=> fix(manager-api-jpa): parse filter number into same numeric data type as target field

manager/ui/war/pom.xml, manager/ui/war/src/main/java/io/apiman/manager/ui/server/kc/DeploymentWithLogoutViaBackend.java, manager/ui/war/src/main/java/io/apiman/manager/ui/server/kc/KeyCloakLogoutServlet.java, manager/ui/war/wildfly8/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
In setups where the Keycloak backend URL is different to the frontend URL, Keycloak's Java adapter
currently (incorrectly, AFAICT?) always uses the frontend URL for logging out.
For example, this means it won't actually log out in situations where the internal Docker network
has a different name to the external network, because it attempts to call the frontend URL from
the Apiman backend, which is _inside_ the Docker network, and hence always fails to resolve.
We work around this by forcing the backend URL with a delegate pattern. It's not pretty...
=> fix(manager-ui-war): force KeyCloakLogoutServlet to use backend URL

common/util/src/main/java/io/apiman/common/util/JsonUtil.java, distro/tomcat/src/main/resources/overlay/log4j2/conf/log4j2-tomcat.xml, distro/wildfly/src/main/resources/overlay/standalone/configuration/standalone-apiman.xml, gateway/engine/core/src/main/java/io/apiman/gateway/engine/IMetrics.java, gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/EsMetrics.java, gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/EsMetricsClientOptionsParser.java, manager/test/api/src/test/java/io/apiman/manager/test/es/EsMetricsAccessorTest.java
To facilitate scrape-based metrics, this commit allows Apiman's ES metrics (as JSON) to be written
to a log file. The specific behaviour is controlled via whatever logging framework is used.
It is possible to write to any of: `remote` (ES server), `log`
The configuration provided in this commit calls the output `metrics.log`, but we the user can change
this, as per their preferences. Async logging is used, where possible, to mitigate the impact on
performance, as this is likely to generate a considerable number of log writes.
Thanks again to Terry, Russel, Joe, Colin, LN, Shivraj, and the rest of the team.
Fixes: #2100
=> feat(metrics-es): allow logging metrics to JSON file with `write-to` option

gateway/test/src/test/resources/test-plan-data/policies/transfer-quota/002-register-client.resttest, gateway/test/src/test/resources/test-plan-data/policies/transfer-quota/003-success.resttest, gateway/test/src/test/resources/test-plan-data/policies/transfer-quota/003.5-probe-transfer-quota.resttest, gateway/test/src/test/resources/test-plan-data/policies/transfer-quota/004-failure.resttest, gateway/test/src/test/resources/test-plan-data/policies/transfer-quota/005-register-client-ip-policy.resttest, gateway/test/src/test/resources/test-plan-data/policies/transfer-quota/006-success-ip-address.resttest, gateway/test/src/test/resources/test-plan-data/policies/transfer-quota/008-probe-ip-transfer-quota.resttest, gateway/test/src/test/resources/test-plan-data/policies/transfer-quota/009-probe-ip-transfer-quota.resttest, gateway/test/src/test/resources/test-plans/policies/transfer-quota-testPlan.xml
Use daily time granularity to avoid issue where test could fail due to coincidental rollover into new hour.
Add some data to the request to make the test more realistic.
=> test(gateway-test): refactor flaky transfer-quota test by using day granularity

manager/api/rest-impl/src/main/java/io/apiman/manager/api/service/ContractService.java, manager/test/api/src/test/java/io/apiman/manager/test/ReregisterClientTest.java, manager/test/api/src/test/resources/test-plan-data/reregister-client/109_create-contract.resttest, manager/test/api/src/test/resources/test-plan-data/reregister-client/115_delete-contract.resttest, manager/test/api/src/test/resources/test-plan-data/reregister-client/116_get-version-1.0.resttest, manager/test/api/src/test/resources/test-plans/reregister-client-testPlan.xml
If a contracts is deleted we try to reregister or unregister the client automatically, however there was no check if the current state was correct and an `ActionException` was thrown in some cases.
Closes: #2404
=> fix(manager-api): perform unregister only if client is in correct state

CHANGELOG.adoc, gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/EsRegistry.java
Replace ApiNotFoundException with ClientNotFoundException
=> fix(gateway-engine-es): throw `ClientNotFoundException` if client not found when unregistering

manager/ui/war/plugins/api-manager/ts/policies.ts, manager/ui/war/pom.xml, manager/ui/war/webpack.config.js
If one switches between ip policies the ip-list could be undefined. Moving the check into the validate method fixes the problem.
=> fix(ui): avoid undefined errors

CHANGELOG.adoc, distro/data/src/main/resources/ddls/apiman-gateway_mssql15.ddl, distro/data/src/main/resources/ddls/apiman_mssql15.ddl, distro/ddl/src/main/resources/liquibase/current/000-apiman-manager-api.db.sequences.changelog.xml, distro/ddl/src/main/resources/liquibase/current/201-add-json-type.changelog.xml, distro/ddl/src/main/resources/liquibase/master.xml, manager/api/jpa/src/main/java/io/apiman/manager/api/jpa/ApimanH2Dialect.java, manager/api/jpa/src/main/java/io/apiman/manager/api/jpa/ApimanMSSQLDialect.java, manager/api/jpa/src/main/java/io/apiman/manager/api/jpa/JpaDialectMapper.java
∙ `hibernate_sequence` creation was limited to H2 and Postgres only for some reason.
∙ `GO` statement separators in gateway DDL did not play nicely with Apiman's Gateway DDL runner.
∙ Explicit database name was used in Gateway DDL which caused issues if using non-default DB name.
∙ Use custom JSON type to make handling of JSON in MSSQL easier when also using Hibernate.
=> fix(distro-ddl):  fix multiple MSSQL DDL issues

manager/api/rest-impl/src/main/java/io/apiman/manager/api/schema/SchemaRewriterService.java, manager/api/rest-impl/src/main/java/io/apiman/manager/api/service/ApiService.java, manager/api/rest-impl/src/test/java/io/apiman/manager/api/schema/SchemaRewriterServiceTest.java, manager/api/rest-impl/src/test/resources/schema/swagger-petstore-modified.json, manager/api/rest-impl/src/test/resources/schema/swagger-petstore.json
Use `modifiedOn` as key to make sure that we refresh the cache once the definition is updated. Otherwise definition changes are not directly available after an update. Also this fixes caching as the cacheKey class did not override equals/hashCode.
Closes: #2542
See: https://github.com/ben-manes/caffeine/discussions/603
=> refactor(manager-api): change cacheKey for api definition rewrite cache

CHANGELOG.adoc, containers/docker-compose/src/docker/data/conf-es.json, containers/docker-compose/src/docker/docker-compose.yml, distro/vertx/src/main/resources/overlay/configs/conf-es.json, distro/vertx/src/main/resources/overlay/configs/conf-headless-es.json, docs/installation/modules/ROOT/pages/keycloak.adoc, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/api/auth/KeycloakDiscovery.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/api/auth/KeycloakOAuthFactory.java, gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/common/config/VertxEngineConfig.java, gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/common/config/JsonMapToPropertiesTest.java
If you need multiple issuers, this can handle it more gracefully.
Useful if you have internal vs external issuers (sometimes several).
=> feat(gateway-vertx): enable allowed-issuers list in `KeycloakOAuthFactory`

containers/docker-compose/src/docker/docker-compose.yml
Bump from Keycloak 21.1.1 to 21.1.2
Bump Traefik from v2.8.3 to v2.10.3
=> build(deps): bump Keycloak and Traefik containers in containers/docker-compose

CHANGELOG.adoc, gateway/engine/policies/pom.xml, gateway/engine/policies/src/main/java/io/apiman/gateway/engine/policies/TimeRestrictedAccessPolicy.java, gateway/engine/policies/src/main/java/io/apiman/gateway/engine/policies/config/TimeRestrictedAccess.java, gateway/engine/policies/src/test/java/io/apiman/gateway/engine/policies/TimeRestrictedAccessPolicyTest.java
During the previous deserialization of `java.util.Date` the config was parsed by jackson to local time of the gateway instead of UTC. Date and joda-time are replaced with java default `OffsetDateTime` now, which also allows us to be more flexible in future. Old configuration are still compatible. Test is added back again and fixed.
Closes: #2557
=> fix: ensure use of UTC for the time-restricted-access-policy
