apiman/apiman

- manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/OrganizationResourceImpl.java
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/pages/AbstractAppPage.java
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/pages/AbstractPage.java
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/pages/AbstractPlanPage.java
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/pages/AbstractServicePage.java
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/pages/AppContractsPage.java
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/pages/AppOverviewPage.java
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/pages/NewAppVersionPage.java
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/pages/NewPlanVersionPage.java
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/pages/NewServiceVersionPage.java
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/pages/PlanOverviewPage.java
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/pages/ServiceImplPage.java
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/pages/ServiceOverviewPage.java
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/pages/ServicePlansPage.java
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/site/app-activity.html
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/site/app-apis.html
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/site/app-contracts.html
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/site/app-overview.html
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/site/app-policies.html
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/site/plan-activity.html
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/site/plan-overview.html
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/site/plan-policies.html
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/site/service-activity.html
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/site/service-contracts.html
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/site/service-impl.html
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/site/service-overview.html
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/site/service-plans.html
- manager/ui/war/src/main/java/io/apiman/manager/ui/client/local/site/service-policies.html
- manager/ui/war/src/main/webapp/css/apiman.css
- manager/ui/war/src/main/webapp/index.html
https://issues.jboss.org/browse/APIMAN-240
> Updated the UI to move common/overview entity information into a common area

- gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/exceptions/InterceptorAlreadyRegisteredException.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/ServiceRequestExecutorImpl.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/policy/IConnectorInterceptor.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/policy/IPolicyContext.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/policy/PolicyContextImpl.java
- gateway/test/src/test/java/io/apiman/gateway/test/SimpleConnectorInterceptorPolicyTest.java
- gateway/test/src/test/java/io/apiman/gateway/test/policies/SimpleConnectorInterceptorPolicy.java
- gateway/test/src/test/java/io/apiman/gateway/test/policies/connectors/CannedResponseServiceConnection.java
- gateway/test/src/test/resources/test-plan-data/simple/simple-connector-interceptor-policy/connector-interceptor/001.resttest
- gateway/test/src/test/resources/test-plan-data/simple/simple-connector-interceptor-policy/connector-interceptor/002-intercepted-response.resttest
- gateway/test/src/test/resources/test-plan-data/simple/simple-connector-interceptor-policy/setup/001-publish-service.resttest
- gateway/test/src/test/resources/test-plans/simple/simple-connector-interceptor-policy-testPlan.xml
Created the IConnectorInterceptor concept which can be set into the context in order to intercept remote connections.
> Apiman 238

- gateway/engine/core/src/main/java/io/apiman/gateway/engine/IMetrics.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/EngineImpl.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/InMemoryMetrics.java
- gateway/test/src/main/java/io/apiman/gateway/test/server/TestMetrics.java
> APIMAN-322 Make component registry available to metrics

- gateway/engine/core/src/main/java/io/apiman/gateway/engine/metrics/impl/influxdb/InfluxDb09Driver.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/metrics/impl/influxdb/InfluxDb09Metrics.java
I haven't finished writing tests yet, but want to put this up for review to see what @EricWittmann and @KurtStam think.
> For review: Initial Influxdb 0.9.x metrics impl

- gateway/engine/core/src/main/java/io/apiman/gateway/engine/components/IPeriodicComponent.java
- gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/components/PeriodicComponentImpl.java
- gateway/platforms/vertx/src/main/java/io/apiman/gateway/vertx/components/PeriodicComponentImpl.java
Component interface plus implementations in Vert.x and Servlet.
Let me know if there are any gaps.
> Timers for apiman

- gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/IServiceObject.java
- gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/ServiceRequest.java
- gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/ServiceResponse.java
Change IServiceObjectBean to IServiceObject as requested.
> Naming consistency

- manager/ui/apiman-plugin/plugins/apiman/html/org/apiman-user-card-back.html
- manager/ui/apiman-plugin/plugins/apiman/html/org/apiman-user-card-front.html
- manager/ui/apiman-plugin/plugins/apiman/html/org/org-manage-members.html
- manager/ui/apiman-plugin/plugins/apiman/html/org/org-manage-members_bc.include
- manager/ui/apiman-plugin/plugins/apiman/html/org/org-members.html
- manager/ui/apiman-plugin/plugins/apiman/ts/apimanPlugin.ts
- manager/ui/apiman-plugin/plugins/apiman/ts/org/org-manage-members.ts
Things to note:
- Some elements of styling seem to have changed slightly (there's now a search icon on the search box, and the text is no longer italicised). I think this is a result of @EricWittmann's apiman-search-box element as far as I can ascertain from a bit of CSS sleuthing. Still looks fine, IMO.
-  Sometimes I can see a slight flash when flipping the card in chrome. I will come back and do more experiments with ng-cloak (etc), but I haven't managed to solve that one yet...
Long slog and mildly traumatic, but finally my first significant angular commit: hurrah!
> Completed port of org-manage-members (including card flipping, search, drop-downs, etc).

- manager/ui/apiman-plugin/plugins/apiman/ts/logger.ts
```
$log.info({ MNight: "ShamaLamaDingDong"});
$log.info(['stottie', 'pease pudding']);
$log.info("{0}: {1}", "translations", {ganning: "going", hyem: "home"});
apiman [9:07:27 PM]>>  {"MNight":"ShamaLamaDingDong"}
apiman-plugin.js:637 apiman [9:07:27 PM]>>  ["stottie","pease pudding"]
apiman-plugin.js:637 apiman [9:07:27 PM]>>  translations: {"ganning":"going","hyem":"home"}
```
> Logger with Stringify for Objects to get useful inspection of objects; no more [Object object]

- manager/ui/apiman-plugin/bower.json
- manager/ui/apiman-plugin/index.html
- manager/ui/apiman-plugin/plugins/apiman/html/app/app_entity.include
- manager/ui/apiman-plugin/plugins/apiman/html/org/org_entity.include
- manager/ui/apiman-plugin/plugins/apiman/html/plan/plan_entity.include
- manager/ui/apiman-plugin/plugins/apiman/html/service/service_entity.include
- manager/ui/apiman-plugin/plugins/apiman/ts/apimanPlugin.ts
- manager/ui/apiman-plugin/plugins/apiman/ts/app/app.ts
- manager/ui/apiman-plugin/plugins/apiman/ts/directives.ts
- manager/ui/apiman-plugin/plugins/apiman/ts/org/org-services.ts
- manager/ui/apiman-plugin/plugins/apiman/ts/org/org-sidebar.ts
- manager/ui/apiman-plugin/plugins/apiman/ts/plan/plan.ts
- manager/ui/apiman-plugin/plugins/apiman/ts/service/service.ts
Is flexible enough to re-use elsewhere if we decide to do that.
At the moment I haven't added styling, that's my next task!
> Description in-place editing

- manager/ui/hawtio/plugins/api-manager/css/apiman.css
- manager/ui/hawtio/plugins/api-manager/html/directives/editDescription.html
- manager/ui/hawtio/plugins/api-manager/html/org/org_entity.include
- manager/ui/hawtio/plugins/api-manager/ts/directives.ts
Going to tidy this all up tomorrow and try to fix one or two tiny glitches, but putting it here so you can test it out. I've already fixed-up and squashed a bunch of stuff: went through lots of renditions to get something working nicely :o)...
> Ui style fixes rebased 2

- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/AbstractEngineFactory.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/io/IApimanBuffer.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/policy/Chain.java
- gateway/engine/policies/src/main/java/io/apiman/gateway/engine/policies/connectors/CachedResponseConnection.java
- gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/GatewayServlet.java
- gateway/platforms/vertx/src/main/java/io/apiman/gateway/vertx/api/ApiListener.java
- gateway/platforms/vertx/src/main/java/io/apiman/gateway/vertx/api/GenericError.java
- gateway/platforms/vertx/src/main/java/io/apiman/gateway/vertx/conversation/AbstractServiceExecutor.java
- gateway/platforms/vertx/src/main/java/io/apiman/gateway/vertx/conversation/ServiceResponseExecutor.java
- gateway/platforms/vertx/src/main/java/io/apiman/gateway/vertx/verticles/HttpDispatcherVerticle.java
- gateway/platforms/war/src/main/java/io/apiman/gateway/platforms/war/WarEngineConfig.java
- manager/api/jpa/src/main/java/io/apiman/manager/api/jpa/EntityManagerFactoryAccessor.java
Just went through and added missing override tags.
> Missing @override tags

- distro/wildfly8/src/main/resources/overlay/standalone/configuration/standalone-apiman.xml
- manager/api/war/wildfly8/src/main/webapp/WEB-INF/web.xml
I'm honestly not sure whether I might have missed something out of this, as I'm not an expert with WF config (yet ;-)).
I think I just needed to reintroduce the CORS filter and turn off the KC one. Seems to be fine, but please  let me know if I might have missed out something.
> Fix cors 2

- pom.xml
Presume this is an error. Was looking into which version of HttpClient we're using for the 2 way auth stuff.
> Fix versions pom error - multiple versions of same dep defined

- gateway/engine/core/src/main/java/io/apiman/gateway/engine/metrics/impl/influxdb/InfluxDb09Metrics.java
See https://github.com/influxdb/influxdb/issues/2108
> InfluxDB breaking field-name change timestamp -> time

- distro/wildfly8/src/main/resources/overlay/apiman/ddls/apiman_mysql5.ddl
- distro/wildfly8/src/main/resources/overlay/apiman/ddls/apiman_postgresql.ddl
Not worth the effort with opening JIRA.
> removing redundant comma in PostgreSQL DDL script

- manager/ui/hawtio/plugins/api-manager/html/app/app-policies.html
- manager/ui/hawtio/plugins/api-manager/html/plan/plan-policies.html
- manager/ui/hawtio/plugins/api-manager/html/service/service-policies.html
- manager/ui/hawtio/plugins/api-manager/ts/app/app-policies.ts
- manager/ui/hawtio/plugins/api-manager/ts/directives.ts
- manager/ui/hawtio/plugins/api-manager/ts/logger.ts
- manager/ui/hawtio/plugins/api-manager/ts/plan/plan-policies.ts
- manager/ui/hawtio/plugins/api-manager/ts/service/service-policies.ts
> Implement POSTing elements of policy reordering functionality

- gateway/engine/core/src/main/java/io/apiman/gateway/engine/metrics/impl/influxdb/InfluxDb09Driver.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/metrics/impl/influxdb/InfluxDb09Metrics.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/metrics/impl/influxdb/InfluxException.java
I know we're thinking about refactoring things a fair bit in the near future, but this is a good first step
> Influx refactor line format

- manager/api/beans/src/main/java/io/apiman/manager/api/beans/apps/ApplicationBean.java
- manager/api/beans/src/main/java/io/apiman/manager/api/beans/apps/ApplicationVersionBean.java
- manager/api/beans/src/main/java/io/apiman/manager/api/beans/audit/AuditEntryBean.java
- manager/api/beans/src/main/java/io/apiman/manager/api/beans/contracts/ContractBean.java
- manager/api/beans/src/main/java/io/apiman/manager/api/beans/gateways/GatewayBean.java
- manager/api/beans/src/main/java/io/apiman/manager/api/beans/idm/RoleBean.java
- manager/api/beans/src/main/java/io/apiman/manager/api/beans/idm/RoleMembershipBean.java
- manager/api/beans/src/main/java/io/apiman/manager/api/beans/idm/UserBean.java
- manager/api/beans/src/main/java/io/apiman/manager/api/beans/orgs/OrganizationBean.java
- manager/api/beans/src/main/java/io/apiman/manager/api/beans/plans/PlanBean.java
- manager/api/beans/src/main/java/io/apiman/manager/api/beans/plans/PlanVersionBean.java
- manager/api/beans/src/main/java/io/apiman/manager/api/beans/plugins/PluginBean.java
- manager/api/beans/src/main/java/io/apiman/manager/api/beans/policies/PolicyBean.java
- manager/api/beans/src/main/java/io/apiman/manager/api/beans/policies/PolicyDefinitionBean.java
- manager/api/beans/src/main/java/io/apiman/manager/api/beans/services/ServiceBean.java
- manager/api/beans/src/main/java/io/apiman/manager/api/beans/services/ServiceDefinitionBean.java
- manager/api/beans/src/main/java/io/apiman/manager/api/beans/services/ServiceVersionBean.java
- manager/api/jpa/src/main/java/io/apiman/manager/api/jpa/JpaStorage.java
As part of the larger APIMAN-451 DDL generation task, it is necessary to make these updates to be more compatible across database engines.
> APIMAN-451 Entities updated to remove camelCase in database columns

- manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/ActionResourceImpl.java
- manager/test/api/src/test/resources/test-plan-data/publishing/create/014_create-admin-role.resttest
- manager/test/api/src/test/resources/test-plan-data/publishing/create/015_create-dev-role.resttest
- manager/test/api/src/test/resources/test-plan-data/publishing/manage/001_grant-user1-admin-role.resttest
- manager/test/api/src/test/resources/test-plan-data/publishing/manage/002_grant-user2-dev-role.resttest
- manager/test/api/src/test/resources/test-plan-data/publishing/manage/003_get-members.resttest
- manager/test/api/src/test/resources/test-plan-data/publishing/publish/003_lock-plan-version-1.0.resttest
- manager/test/api/src/test/resources/test-plan-data/publishing/publish/004_dev-user2-publish-service-1.resttest
- manager/test/api/src/test/resources/test-plan-data/publishing/publish/005_dev-user2-register-application-1.resttest
- manager/test/api/src/test/resources/test-plan-data/publishing/publish/006_dev-user2-lock-plan-version-1.0.resttest
- manager/test/api/src/test/resources/test-plan-data/publishing/retire/003_dev-user2-unregister-application-1.resttest
- manager/test/api/src/test/resources/test-plan-data/publishing/retire/004_dev-user2-retire-service-1.resttest
- manager/test/api/src/test/resources/test-plans/publishing-testPlan.xml
- manager/ui/hawtio/plugins/api-manager/html/app/app_entity.include
- manager/ui/hawtio/plugins/api-manager/html/plan/plan_entity.include
- manager/ui/hawtio/plugins/api-manager/html/service/service_entity.include
Updated ActionResourceImpl to hook-up the appAdmin, svcAdmin and planAdmin roles for Register/Unregister, Publish/Retire and Lock operations as appropriate.  Expanded the rest publishing test plan to include testing role membership support against the *Admiin operations.  Looks good.
> APIMAN-458 Add meaning/purpose to the *Admin permissions

- manager/ui/hawtio/plugins/api-manager/html/policyForms/ip-list.include
Added a regular expression to match on IPv4 addresses + to also allow the '*' wildcard for octets within the IP address.
> APIMAN-452 Policy definitions now verify IPv4 + wildcard format

- gateway/test/src/test/java/io/apiman/gateway/test/junit/GatewayRestTester.java
- gateway/test/src/test/resources/test-plan-data/simple/simple-data-policy/datap/001.resttest
- gateway/test/src/test/resources/test-plan-data/simple/simple-echo-public/echo/002-success.resttest
- gateway/test/src/test/resources/test-plan-data/simple/simple-echo-public/echo/003-success-accept.resttest
- gateway/test/src/test/resources/test-plan-data/simple/simple-echo-public/echo/004-success-header.resttest
- gateway/test/src/test/resources/test-plan-data/simple/simple-echo/echo/002.resttest
- gateway/test/src/test/resources/test-plan-data/simple/simple-echo/echo/003.resttest
- gateway/test/src/test/resources/test-plan-data/simple/simple-policy/policy/002.resttest
- gateway/test/src/test/resources/test-plan-data/simple/simple-shared-state-policy/state/002.resttest
- pom.xml
- test/common/pom.xml
- test/common/src/main/java/io/apiman/test/common/util/TestPlanRunner.java
> Refactor test suite to use OkHttpClient for cleaner code and nicer error messages

- gateway/platforms/vertx3/pom.xml
- gateway/test/src/test/resources/test-configs/vertx3-mem.json
Think I managed to re-materialise it during a squash somehow.
> Remove dep that broke 1.8 builds

- gateway/engine/pom.xml
- gateway/platforms/pom.xml
- pom.xml
Figured out this approach which has a lot less noise.
> Cleaner way of splitting out java8 only bits

- .travis.yml
Bonus once we've enabled Travis is that all PRs will automatically be tested against my config. Pretty nice!
> Simple travis file - will add more advanced bits later

- gateway/engine/core/src/main/java/io/apiman/gateway/engine/policy/Chain.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/policy/IPolicyChain.java
- gateway/engine/core/src/test/java/io/apiman/gateway/engine/impl/PolicyChainTest.java
Add skip functionality to policyChain which allows immediate jump to  end of policy chain
> [1.1.x]  Fast terminate functionality & test

- .travis.yml
- gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/Application.java
- gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/Service.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/api/ApplicationResourceImpl.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/api/IRouteBuilder.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/api/ServiceResourceImpl.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/verticles/ApiVerticle.java
- gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/junit/resttest/EsResetter.java
- gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/junit/resttest/NoOpResetter.java
- gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/junit/resttest/Resetter.java
- gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/junit/resttest/Vertx3GatewayTestServer.java
- gateway/test/src/test/java/io/apiman/gateway/test/junit/GatewayRestTester.java
- gateway/test/src/test/resources/test-configs/vertx3-es.json
- gateway/test/src/test/resources/test-configs/vertx3-mem.json
- gateway/test/src/test/resources/vertx3/conf-es.json
- Enhance Vert.x 3 test framework to allow DB resetting
- Add ES tests for Vert.x 3
- Fix Vert.x API impl errors after ES tests triggered them
> Testing related enhancements and fixes

- .travis.yml
- gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/Application.java
- gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/Service.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/api/ApplicationResourceImpl.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/api/IRouteBuilder.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/api/ServiceResourceImpl.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/verticles/ApiVerticle.java
- gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/junit/resttest/EsResetter.java
- gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/junit/resttest/NoOpResetter.java
- gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/junit/resttest/Resetter.java
- gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/junit/resttest/Vertx3GatewayTestServer.java
- gateway/test/src/test/java/io/apiman/gateway/test/junit/GatewayRestTester.java
- gateway/test/src/test/resources/test-configs/vertx3-es.json
- gateway/test/src/test/resources/test-configs/vertx3-mem.json
- gateway/test/src/test/resources/vertx3/conf-es.json
- Enhance Vert.x 3 test framework to allow DB resetting
- Add ES tests for Vert.x 3
- Fix Vert.x API impl errors after ES tests triggered them
> [1.1.x] Testing related enhancements and fixes

- common/plugin/src/main/java/io/apiman/common/plugin/PluginSpec.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/DefaultPluginRegistry.java
Handy for when someone keeps loading the wrong plugin!
In the future I might extend that to have a file hash as well, which would be useful for determining which snapshot someone might be using.
> Print plugin version on load into gateway

- common/plugin/src/main/java/io/apiman/common/plugin/PluginSpec.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/DefaultPluginRegistry.java
> [1.1.x] Print plugin version on load into gateway

- gateway/platforms/vertx3/vertx3/pom.xml
- pom.xml
@jcechace let me know if it works okay.
> [Do not merge] Move sonatype snapshot repo into parent pom temporarily

- manager/ui/hawtio/plugins/api-manager/html/directives/editDescription.html
- manager/ui/hawtio/plugins/api-manager/ts/directives.ts
Changes:
- Fixes issue with editable description directive, where the changes were not being saved.
JIRA Issue: https://issues.jboss.org/browse/APIMAN-675
> re #675 Fix for Editable Description Directive

- manager/ui/hawtio/plugins/api-manager/ts/apimanPlugin.ts
- manager/ui/hawtio/plugins/api-manager/ts/forms/edit-gateway.ts
- manager/ui/hawtio/plugins/api-manager/ts/profile.ts
- manager/ui/hawtio/plugins/api-manager/ts/service/service-def.ts
- manager/ui/hawtio/plugins/api-manager/ts/service/service-impl.ts
- manager/ui/hawtio/plugins/api-manager/ts/service/service-plans.ts
Cleanup
re #306 Add check to other tabs
Remove directive, controller, and add rootScope flag
Minor fix for form
Updating other files to use rootScope flag
Cleanup console logs
Addl cleanup
> Add ctrl for service tabs

- pom.xml
Aligning versions with fabric8
> Setting elasticsearch version to 1.7.2

- manager/ui/hawtio/bower.json
- manager/ui/hawtio/gulpfile.js
- manager/ui/hawtio/index.html
- manager/ui/hawtio/package.json
- manager/ui/hawtio/plugins/api-manager/html/admin/admin_bc.include
- manager/ui/hawtio/plugins/api-manager/html/app/app_bc.include
- manager/ui/hawtio/plugins/api-manager/html/consumer/consumer-org.html
- manager/ui/hawtio/plugins/api-manager/html/consumer/consumer-orgs.html
- manager/ui/hawtio/plugins/api-manager/html/consumer/consumer-service-def.html
- manager/ui/hawtio/plugins/api-manager/html/consumer/consumer-service.html
- manager/ui/hawtio/plugins/api-manager/html/consumer/consumer-services.html
- manager/ui/hawtio/plugins/api-manager/html/headers/community.include
- manager/ui/hawtio/plugins/api-manager/html/org/org-manage-members_bc.include
- manager/ui/hawtio/plugins/api-manager/html/org/org_bc.include
- manager/ui/hawtio/plugins/api-manager/html/plan/plan_bc.include
- manager/ui/hawtio/plugins/api-manager/html/service/import-services.html
- manager/ui/hawtio/plugins/api-manager/html/service/service_bc.include
- manager/ui/hawtio/plugins/api-manager/html/user/user_bc.include
- manager/ui/hawtio/plugins/api-manager/ts/admin/admin-plugins.ts
- manager/ui/hawtio/plugins/api-manager/ts/apimanPlugin.ts
Many thanks to @msavy for helping me clean up this commit mess.
Here's where I messed up: Created a feature branch, worked off of it, created a feature branch off of that feature branch (once we decided to only remove Hawtio nav stuff, yet keep the original feature branch in tact in case I go back to it), ran `git pull upstream master` once or twice to further complicate matters, and then, because I wasn't satisfied with how much I had complicated things, merged it onto master, pushed and created a PR.
Lessons learned: Rebase master, don't pull from upstream. Do it once, at the end once I'm ready to merge. Create PRs for feature branches, not master. Maybe go a little less crazy with commits?
Original PR: https://github.com/apiman/apiman/pull/232
> re #707 Remove Hawtio navigation references, add and manage own routing

- gateway/platforms/vertx3/vertx3/pom.xml
- gateway/platforms/vertx3/vertx3/src/main/asciidoc/dataobjects.adoc
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/verticles/ApiVerticle.java
- pom.xml
> Move to 3.1.0 release of vert.x

- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/http/HttpExecutor.java
> Change error output to align with servlet behaviour/new tests

- manager/ui/hawtio/plugins/api-manager/html/org/org-new-member.html
Removed a script tag from the head that was preventing the page from being loaded.
> re #735 Fix for new member page

- tools/src/intellij/apiman-intellij-formatter.xml
Add intellij code formater based on eclipse code formater - https://github.com/apiman/apiman/issues/251
> Add intellij code formater

- gateway/platforms/vertx3/vertx3/src/main/resources/apiman-vertx-services-js/ingestor_to_policy_service.js
- gateway/platforms/vertx3/vertx3/src/main/resources/apiman-vertx-services-js/policy_to_ingestor_service.js
> Commit js service adapter 

- manager/ui/hawtio/plugins/api-manager/html/admin/admin-export.html
- manager/ui/hawtio/plugins/api-manager/ts/admin/admin-export.ts
Changes:
JIRA: https://issues.jboss.org/browse/APIMAN-770
> re #770 Improvements to Import Export UI

- gateway/engine/core/pom.xml
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/components/IBufferFactoryComponent.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/components/jdbc/IJdbcClient.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/components/jdbc/IJdbcComponent.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/components/jdbc/IJdbcConnection.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/components/jdbc/IJdbcResultSet.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/components/jdbc/JdbcConnection.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/components/jdbc/JdbcOptionsBean.java
- gateway/platforms/vertx3/vertx3/pom.xml
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/components/JdbcClientComponentImpl.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/components/jdbc/VertxJdbcClientImpl.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/components/jdbc/VertxJdbcConnection.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/components/jdbc/VertxJdbcResultSet.java
- gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/components/jdbc/JdbcTestSuite.java
- gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/components/jdbc/SpecHelpers.java
- gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/components/jdbc/suitetests/CreateTableTest.java
- gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/components/jdbc/suitetests/ExecuteTest.java
- gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/components/jdbc/suitetests/NestedQueryTest.java
- gateway/platforms/vertx3/vertx3/src/test/java/io/apiman/gateway/platforms/vertx3/components/jdbc/suitetests/QueryTest.java
- pom.xml
I've already squashed this down into a much smaller number of commits (hence weird dates and times on commits), but want to run it through CI first. 
Will rebase and squash down a bit more before asking for merge.
> JDBC component interface, Vert.x 3 impl and test suite

- manager/ui/hawtio/plugins/api-manager/css/apiman.css
- manager/ui/hawtio/plugins/api-manager/html/service/service_entity.include
- manager/ui/hawtio/plugins/api-manager/ts/directives.ts
- manager/ui/hawtio/plugins/api-manager/ts/filters.ts
- manager/ui/hawtio/plugins/api-manager/ts/service/service.ts
- manager/ui/hawtio/typings-custom/directives.d.ts
- manager/ui/hawtio/typings-custom/tsd.d.ts
Changes:
- Switched from collapse directive to accordion directive.
- Added Bootstrap UI. Update Browserify's entry.js file and package.json.
JIRA: https://issues.jboss.org/browse/APIMAN-750
Screenshots:
NOTE: The popover will not close automatically on clicking outside of it (for now), due to a known conflict between jQuery, Bootstrap, and Bootstrap UI. See the following issue: https://issues.jboss.org/browse/APIMAN-784
> re #750 Completion Checklist

- manager/ui/hawtio/plugins/api-manager/html/service/service_entity.include
- manager/ui/hawtio/plugins/api-manager/ts/service/service.ts
JIRA: https://issues.jboss.org/browse/APIMAN-786
> re #786 Cleanup and fix for Go There icon

- manager/ui/hawtio/plugins/api-manager/css/apiman.css
- manager/ui/hawtio/plugins/api-manager/html/app/app-apis.html
- manager/ui/hawtio/plugins/api-manager/ts/app/app-apis.ts
- manager/ui/hawtio/plugins/api-manager/ts/directives.ts
Changes:
- Removed tooltip directive. Replaced old tooltip directive references with UI Bootstrap tooltip.
- Fixed styling issue with clipboard icon.
This fixes the issue where copying was not functional from within a modal.
JIRA: https://issues.jboss.org/browse/APIMAN-752
> re #752 Copy-to-Clipboard Modal Fix

- manager/ui/hawtio/plugins/api-manager/ts/service/service-impl.ts
Clear validation errors being displayed, if applicable, whenever saving the Service Implementation form.
JIRA: https://issues.jboss.org/browse/APIMAN-800
> re #800 Clear validation errors on saving Service Implementation form

- common/servlet/pom.xml
- manager/api/export-import/pom.xml
- manager/api/micro/pom.xml
- manager/api/micro/src/main/resources/WEB-INF/web.xml
- Add missing apache maven felix plugin 
- Change packaging to bundle
- Include web.xml file to run jetty standalone
> Add OSGI Karaf branch

- manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/ActionResourceImpl.java
@kasparjarek can you please test this out?
> Fix APIMAN-854

- manager/ui/hawtio/plugins/api-manager/html/forms/edit-gateway.html
- manager/ui/hawtio/plugins/api-manager/html/user/user-profile.html
- manager/ui/hawtio/plugins/api-manager/ts/apimanPlugin.ts
- manager/ui/hawtio/plugins/api-manager/ts/forms/edit-gateway.ts
- manager/ui/hawtio/plugins/api-manager/ts/user/user-profile.ts
Changes:
- Fixed an issue where pressing the cancel button on a form with unsaved changes would result in an 'Unsaved changes' dialog. I could only find this issue in the Edit Gateway and User Profile views.
- Forgot to move User Profile HTML along with TS in another issue, did that here
- Fixed browser console error for fullName & email that was driving me nuts
JIRA: https://issues.jboss.org/browse/APIMAN-825
> re # 825 Unsaved changes fix

- manager/ui/hawtio/plugins/api-manager/css/apiman.css
- manager/ui/hawtio/plugins/api-manager/html/api/api-impl.html
- manager/ui/hawtio/plugins/api-manager/html/org/org-manage-members.html
- manager/ui/hawtio/plugins/api-manager/ts/api/api-impl.ts
- Fix border color for multiple gateways dropdown
- Fix random bug found where directive to search for members was not working
- Fixed issue where endpoint not required for Save button to become enabled
- Support for multiple gateways in the UI
- Add isEntityDisabled()
**JIRA**: https://issues.jboss.org/browse/APIMAN-820
--
*Disabled*:
*2 gateways selected, closed*:
*2 gateways selected, expanded*:
*3 gateways selected, closed*:
*3 gateways selected, expanded*:
--
cc @EricWittmann  - See the last two screenshots above (with 3 gateways selected) and let me know if everything looks okay. We may want to consider using a special directive in the future where we can just display "3 Gateways Selected" or something similar, when the number selected is greater than 2.
> re #820 Support for Multiple Gateways in UI

- manager/ui/hawtio/plugins/api-manager/html/forms/new-contract.html
- manager/ui/hawtio/plugins/api-manager/ts/forms/new-contract.ts
Fixes issue where incorrect `planId` is passed when submitting New Contract form.
JIRA: https://issues.jboss.org/browse/APIMAN-893
> re #893 Fix for incorrect planId and New Contract form

- gateway/engine/policies/src/main/java/io/apiman/gateway/engine/policies/auth/LDAPIdentityValidator.java
> Fix APIMAN-917 - 	Ensure we set roles before handler is called 

- pom.xml
As discussed with @EricWittmann before
> Dep changes

- .travis.yml
- gateway/engine/pom.xml
- gateway/platforms/pom.xml
- gateway/platforms/vertx3/vertx3/pom.xml
- gateway/test/pom.xml
- gateway/test/src/test/java/io/apiman/gateway/test/junit/vertx3/EsResetter.java
- gateway/test/src/test/java/io/apiman/gateway/test/junit/vertx3/NoOpResetter.java
- gateway/test/src/test/java/io/apiman/gateway/test/junit/vertx3/Resetter.java
- gateway/test/src/test/java/io/apiman/gateway/test/junit/vertx3/Vertx3GatewayTestServer.java
- gateway/test/src/test/java/io/apiman/gateway/test/junit/vertx3/Vertx3GatewayTestServerFactory.java
- gateway/test/src/test/resources/test-configs/vertx3-es.json
- gateway/test/src/test/resources/test-configs/vertx3-mem.json
- pom.xml
@EricWittmann @kahboom @ldimaggi @sbunciak @jcechace 
This will break Java 7 support, as discussed on ML, IRC, etc. If there are any final objections, please let us know here!
> Refactoring to enable move to Java 8.

- gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/util/QueryMap.java
- gateway/engine/beans/src/test/java/io/apiman/gateway/engine/beans/util/QueryMapTest.java
@EricWittmann as requested... :smile:
> QueryMap #toString and #toQueryString that builds www-form-urlencoded query string

- gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/GatewayServlet.java
- gateway/platforms/servlet/src/test/java/io/apiman/gateway/platforms/servlet/GatewayServletTest.java
Fix for handling parameters with & and = encoded in its values or keys.
> APIMAN-970 parameter decoding

- manager/ui/war/npm-shrinkwrap.json
- manager/ui/war/package.json
@kahboom Please verify this doesn't break any of the stuff you were working on lately! 
Fixes https://issues.jboss.org/browse/APIMAN-544
> Upgrade to json-editor 0.7.23 to fix spinner issue in APIMAN-544

- common/config/src/main/java/io/apiman/common/config/ConfigFileConfiguration.java
- common/servlet/src/main/java/io/apiman/common/servlet/AuthenticationFilter.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/ApiRequestExecutorImpl.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/InMemoryCacheStoreComponent.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/InMemoryRateLimiterComponent.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/InMemorySharedStateComponent.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/policy/PolicyFactoryImpl.java
- gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/AsyncESRateLimiterComponent.java
- gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/AsyncESSharedStateComponent.java
- gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/CachingESRegistry.java
- gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/ESClientFactory.java
- gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/ESRateLimiterComponent.java
- gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/ESSharedStateComponent.java
- gateway/engine/ispn/src/main/java/io/apiman/gateway/engine/ispn/InfinispanRateLimiterComponent.java
- gateway/engine/policies/src/main/java/io/apiman/gateway/engine/policies/BasicAuthenticationPolicy.java
- gateway/engine/policies/src/main/java/io/apiman/gateway/engine/policies/auth/JDBCIdentityValidator.java
- gateway/engine/policies/src/test/java/io/apiman/gateway/engine/policies/RateLimitingPolicyTest.java
- gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/GatewayServlet.java
- manager/api/gateway/src/main/java/io/apiman/manager/api/gateway/rest/GatewayClient.java
- manager/api/jpa/src/main/java/io/apiman/manager/api/jpa/AbstractJpaStorage.java
- manager/api/micro/src/main/java/io/apiman/manager/api/micro/ManagerApiMicroServiceCdiFactory.java
- manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/ActionResourceImpl.java
- manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/OrganizationResourceImpl.java
- manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/PluginResourceImpl.java
- manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/UserResourceImpl.java
- manager/api/war/src/main/java/io/apiman/manager/api/war/WarCdiFactory.java
- test/common/src/main/java/io/apiman/test/common/mock/EchoServlet.java
- test/common/src/main/java/io/apiman/test/common/util/TestUtil.java
- test/policies/src/main/java/io/apiman/test/policies/PolicyTester.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1854 - “ Dead stores should be removed ”. You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1854
> Dead stores should be removed

- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/DefaultJdbcConnection.java
This pull request is focused on resolving occurrences of Findbugs rule OS_OPEN_STREAM - “ Method may fail to close stream”. You can find more information about the issue here: http://findbugs.sourceforge.net/bugDescriptions.html#OS_OPEN_STREAM
> Closing non-closed streams

- gateway/api/rest/pom.xml
- manager/api/rest/pom.xml
Dear maintainers of apiman,
We noticed that your previous open-source license expired and that you are currently using a free Miredot license. We thought we'd help you out and upgrade your license back to an open-source license.
With this license you get access to all the paying features, free of charge. If you have any questions, problems or feedback, please let us know!
Kind Regards,
Ewout & The Miredot team.
> Updates the Miredot license of the gateway and manager rest modules.

- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/DefaultPluginRegistry.java
- gateway/test/src/main/java/io/apiman/gateway/test/server/GatewayServer.java
- manager/api/core/src/main/java/io/apiman/manager/api/core/util/EntityValidator.java
- manager/api/micro/src/main/java/io/apiman/manager/api/micro/ManagerApiMicroServiceCdiFactory.java
- manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/OrganizationResourceImpl.java
- manager/api/war/src/main/java/io/apiman/manager/api/war/WarCdiFactory.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1066 - “ Collapsible "if" statements should be merged”. You can find more information about the issue here: https://dev.eclipse.org/sonar/rules/show/squid:S1066
> Merging collapsible if statements increases the code's readability

- gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/util/CaseInsensitiveStringMultiMap.java
- gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/util/IStringMultiMap.java
> Fix accidentally aliased method. Add addAll(IStringMultiMap).

- pom.xml
> APIMAN-979 Change netty ver -  4.0.33.Final -> 4.0.32.Final

- manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/ActionResourceImpl.java
- manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/mappers/RestExceptionMapper.java
Changes:
- Add try/catch statement around unregistering client call in ActionResourceImpl
- Remove code to add headers in RestExceptionMapper
JIRA: https://issues.jboss.org/browse/APIMAN-349
> re #349 Duplicate Headers Result in CORS Error

- gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/ssl/CipherSelectingSSLSocketFactory.java
I guess this code path is not being hit at the moment during tests/production, as it would have broken.
> (Bug) Delegate not called in CipherSelectingSSLSocketFactory

- distro/tomcat8/src/main/resources/overlay/conf/apiman.properties
- distro/wildfly8/src/main/resources/overlay/standalone/configuration/apiman.properties
- distro/wildfly9/src/main/resources/overlay/standalone/configuration/apiman.properties
> (Bug) Missing IHttpClientComponent from default apiman.properties.

- gateway/api/rest-impl/src/main/java/io/apiman/gateway/api/rest/impl/AbstractResourceImpl.java
- gateway/api/rest-impl/src/main/java/io/apiman/gateway/api/rest/impl/ApiResourceImpl.java
- gateway/api/rest-impl/src/main/java/io/apiman/gateway/api/rest/impl/ClientResourceImpl.java
- gateway/api/rest-impl/src/main/java/io/apiman/gateway/api/rest/impl/IEngineAccessor.java
Some fair chunks of code were repeated, so extracted into AbstractResourceImpl
> (Chore) Refactor common code in api/rest/impl

- distro/wildfly9/src/main/resources/overlay/themes/apiman/login/theme.properties
> (Bug) Update theme.properties for some additional (possibly undocumented) changes

- .gitignore
- distro/karaf/bundles/gateway/readme.md
- distro/karaf/features/src/main/resources/repository/features.xml
- distro/karaf/test/pom.xml
- distro/karaf/test/src/test/java/io/apiman/osgi/pax/testing/GatewayApiTest.java
- distro/karaf/test/src/test/java/io/apiman/osgi/pax/testing/GatewayRestOSGITester.java
- distro/karaf/test/src/test/java/io/apiman/osgi/pax/testing/SimpleKarafTest.java
- distro/karaf/test/src/test/java/io/apiman/osgi/pax/testing/util/GatewayRestTestPlan.java
- distro/karaf/test/src/test/java/io/apiman/osgi/pax/testing/util/KarafBaseTest.java
- distro/karaf/test/src/test/java/io/apiman/osgi/pax/testing/util/KarafConfiguration.java
Some minor modificatons before to start the merging process
- Remove not required dep
- Change password for testing purpose,
- Add instructions to use echo service locally
- Add a test mimic class using ParentRunner with annotated class (like project gateway/manager) - DOESN' T work unfortunately
- Exclude file generated by maven shade 
- Replace wrapped bundle by its ServiceMix bundle
> Remove not required dep, change password, add instructions to use echo service

- manager/ui/war/plugins/api-manager/css/apiman.css
- manager/ui/war/plugins/api-manager/html/catalog/api-catalog.html
Fixed issue with multiple tags not expanding field.
> Minor styling changes, fix for vertical expansion

- manager/ui/war/plugins/api-manager/css/apiman.css
- manager/ui/war/plugins/api-manager/html/directives/editDescription.html
- manager/ui/war/plugins/api-manager/ts/directives.ts
Changes:
- Use CSS instead of JS to set height and position of editor button.
--
Screenshots:
**Before hover:**
**After hover:**
--
JIRA: https://issues.jboss.org/browse/APIMAN-801
cc @EricWittmann - I commented out some of the original code in case it is relevant somewhere I haven't found yet, as I couldn't figure out why we would be setting these values from within the controller.
> re #801 Fix edit button not displaying

- .gitignore
- distro/karaf/test/pom.xml
- distro/karaf/test/src/test/java/io/apiman/osgi/pax/testing/util/HttpTestClient.java
- Use admin:admin as login/password
- Exclude SimpleKarafTest.java from maven surefire
- Remove dep with apiman gateway test module
- Correct typo error within .gitignore
- Igonre dependency-reduced-pom.xml files
> Some minor changes

- manager/api/es/src/main/java/io/apiman/manager/api/es/EsStorage.java
- manager/api/jpa/src/main/java/io/apiman/manager/api/jpa/JpaStorage.java
- manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/OrganizationResourceImpl.java
- manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/util/ExceptionFactory.java
- manager/api/rest/src/main/java/io/apiman/manager/api/rest/contract/IOrganizationResource.java
- manager/api/rest/src/main/java/io/apiman/manager/api/rest/contract/exceptions/ErrorCodes.java
- manager/api/rest/src/main/java/io/apiman/manager/api/rest/contract/exceptions/InvalidPlanStatusException.java
- manager/test/api/src/test/resources/test-plan-data/plans/delete/001_lock-plan-version-1.0.resttest
- manager/test/api/src/test/resources/test-plan-data/plans/delete/002_delete-plan1.resttest
- manager/test/api/src/test/resources/test-plan-data/plans/delete/003_delete-plan2.resttest
- manager/test/api/src/test/resources/test-plan-data/plans/delete/004_get-plan2-not-found.resttest
- manager/test/api/src/test/resources/test-plans/plans-testPlan.xml
I'm going to add some extra tests now, but this is just to let folk have a quick look.
> [APIMAN-1018] Delete plan

- manager/ui/war/plugins/api-manager/html/api/api_entity.include
- manager/ui/war/plugins/api-manager/html/client/client_entity.include
- manager/ui/war/plugins/api-manager/html/org/org_entity.include
- manager/ui/war/plugins/api-manager/html/plan/plan_entity.include
- manager/ui/war/plugins/api-manager/ts/api/api.ts
- manager/ui/war/plugins/api-manager/ts/client/client.ts
- manager/ui/war/plugins/api-manager/ts/org/org-sidebar.ts
- manager/ui/war/plugins/api-manager/ts/plan/plan.ts
**Changes:**
- Added ability to delete client apps, organizations and plans in UI
- Improvements to delete API
--
**Screenshots:**
_APIs:_
_Client Apps:_
_Organizations:_
_Plans:_
--
**JIRA**: https://issues.jboss.org/browse/APIMAN-1094 & https://issues.jboss.org/browse/APIMAN-1095
> re #1094 #1095 Delete Client Apps, Organizations, and Plans in UI

- manager/ui/war/plugins/api-manager/ts/api/api.ts
- manager/ui/war/plugins/api-manager/ts/client/client.ts
- manager/ui/war/plugins/api-manager/ts/org/org-sidebar.ts
- manager/ui/war/plugins/api-manager/ts/plan/plan.ts
> Fix modal not displaying and not closing on conflict error

- common/plugin/src/main/java/io/apiman/common/plugin/PluginUtils.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/DefaultPluginRegistry.java
- manager/api/core/src/main/java/io/apiman/manager/api/core/config/ApiManagerConfig.java
- manager/api/core/src/main/java/io/apiman/manager/api/core/plugin/AbstractPluginRegistry.java
- manager/api/core/src/test/java/io/apiman/manager/api/core/plugin/AbstractPluginRegistryTest.java
- manager/api/micro/src/main/java/io/apiman/manager/api/micro/ManagerApiMicroServicePluginRegistry.java
- manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/PluginResourceImpl.java
- manager/api/war/tomcat8/src/main/java/io/apiman/manager/api/war/tomcat8/Tomcat8PluginRegistry.java
- manager/api/war/wildfly8/src/main/java/io/apiman/manager/api/war/wildfly8/Wildfly8PluginRegistry.java
> perf(plugins) Refactoring of URL to URI to avoid URL's blocking equals and hashCode

- manager/ui/war/plugins/api-manager/css/apiman.css
- manager/ui/war/plugins/api-manager/html/api/api-def.html
- manager/ui/war/plugins/api-manager/ts/api/api-def.ts
Summary:
- Changed the order in which the functions are executed, since they are done so synchronously. However, for a quick second I thought I was able to replicate the issue again, but tried another 10 times to no avail. If it happens again, this could very well be a timing issue. Please verify that this fixes it on your end as well.
JIRA: https://issues.jboss.org/browse/APIMAN-1128
> Fix for API definition double save

- .travis.yml
- README.md
This will only be faster on the build *after* this one (so that the cache can be accumulated).
> chore(travis) Cache node_modules in updated location.

- manager/ui/war/plugins/api-manager/ts/dialogs.ts
- manager/ui/war/plugins/api-manager/ts/forms/new-contract.ts
Changes:
- There was an Angular compilation timeout on the directive as opposed to in the controller, so I moved it from [here](https://github.com/apiman/apiman/compare/master...kahboom:1169-contracts-modal?expand=1#diff-e1b6251f1664c4d1bb96ef8224b4a574L82) to [here](https://github.com/apiman/apiman/compare/master...kahboom:1169-contracts-modal?expand=1#diff-0795281b263dcfde870bbd6b45c92f19R95).
Apologies for the formatting, but it was driving me crazy that the code wasn't aligned. Let me know if you'd like for me to undo that and just commit the change.
JIRA: https://issues.jboss.org/browse/APIMAN-1169
cc @EricWittmann - Since I couldn't replicate this locally, I'll need to do a test fix for the New Contract page issue. If it works, I'll be sure to fix it on the Client App Contracts page …
> re #1169 Move timeout to ctrl for New Contract page vs directive

- manager/ui/war/plugins/api-manager/ts/dialogs.ts
JIRA: https://issues.jboss.org/browse/APIMAN-1169
cc @EricWittmann - Yet another test. Please merge and restart on bluejay when you get the chance so that I can test just for the New Contracts page. Thanks! :)
> re #1169 Increase timeout again

- manager/api/es/src/main/java/io/apiman/manager/api/es/EsStorage.java
> fix(manager-api-es) Fix for policies left lingering after delete

- pom.xml
@EricWittmann : Can you take a look and see if this looks reasonable please?
> Remove unused managed dependencies

- common/auth/pom.xml
- common/logging/log4j2/pom.xml
- common/net/pom.xml
- common/plugin/pom.xml
- distro/es/pom.xml
- gateway/api/rest/pom.xml
- gateway/engine/es/pom.xml
- gateway/engine/jdbc/pom.xml
- gateway/platforms/servlet/pom.xml
- gateway/platforms/war/pom.xml
- manager/api/core/pom.xml
- manager/api/es/pom.xml
- manager/api/export-import/pom.xml
- manager/api/hawkular/pom.xml
- manager/api/migrator/pom.xml
- manager/api/rest-impl/pom.xml
- manager/api/rest/pom.xml
- manager/api/war/pom.xml
- manager/ui/war/pom.xml
- pom.xml
- test/common/pom.xml
- test/policies/pom.xml
- test/suite/pom.xml
- tools/ddl/pom.xml
- tools/jdbc/pom.xml
@EricWittmann Can you review this please? Thanks!
> Remove unused dependencies

- gateway/engine/core/src/main/java/io/apiman/gateway/engine/components/http/IHttpClientRequest.java
- gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/components/HttpClientRequestImpl.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/components/HttpClientComponentImpl.java
* feat(gateway-engine-components) Write on IHttpClientRequest now accepts IApimanBuffer
* bug(gateway-platforms-vert3-components) Fix improper handler assignment which could cause the wrong response to be returned for a given request.
> Add #write(IApimanBuffer) to IHttpClientRequest & fix bugs in Vert.x HttpClientComponentImpl

- README.md
- tools/server-all/pom.xml
* Update from WildFly 10.0.0.Final to 10.1.0.Final
> chore(server-all) Update to WildFly 10.1.0.Final

- gateway/engine/hazelcast/pom.xml
- gateway/engine/hazelcast/src/main/java/io/apiman/gateway/engine/hazelcast/AbstractHazelcastComponent.java
- gateway/engine/hazelcast/src/main/java/io/apiman/gateway/engine/hazelcast/HazelcastRateLimiterComponent.java
- gateway/engine/hazelcast/src/main/java/io/apiman/gateway/engine/hazelcast/HazelcastSharedStateComponent.java
- gateway/engine/pom.xml
- gateway/platforms/war/micro/pom.xml
- gateway/platforms/war/pom.xml
- gateway/test/pom.xml
- pom.xml
Rate limiter and shared state implementations added for Hazelcast.
* Modelled on the ISPN implementations.
* Please could you check I've included it as a dependency in the right places? I have matched where the `*-engine-ispn` dependency was used, but not sure this is right.
> Adds a Hazelcast implementation for rate limiting and shared state.

- gateway/engine/core/src/main/java/io/apiman/gateway/engine/IConnectorFactory.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/ApiRequestExecutorImpl.java
- gateway/engine/core/src/test/java/io/apiman/gateway/engine/impl/DefaultEngineFactoryTest.java
- gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/HttpApiConnection.java
- gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/HttpConnectorFactory.java
- gateway/platforms/servlet/src/test/java/io/apiman/gateway/platforms/servlet/auth/basic/BasicAuthTest.java
- gateway/platforms/servlet/src/test/java/io/apiman/gateway/platforms/servlet/auth/tls/BasicMutualAuthTest.java
- gateway/platforms/servlet/src/test/java/io/apiman/gateway/platforms/servlet/auth/tls/CAMutualAuthTest.java
- gateway/platforms/servlet/src/test/java/io/apiman/gateway/platforms/servlet/auth/tls/CipherAndProtocolSelectionTest.java
- gateway/platforms/servlet/src/test/java/io/apiman/gateway/platforms/servlet/auth/tls/StandardTLSTest.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/connector/ConnectorFactory.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/connector/HttpConnector.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/http/HttpPolicyAdapter.java
- pom.xml
- test/policies/src/main/java/io/apiman/test/policies/PolicyTesterConnectorFactory.java
> feat(APIMAN-1230) Keep Content-Length when no mutating policies in the pipeline

- distro/tomcat8/src/main/resources/overlay/conf/apiman.properties
- distro/wildfly8/src/main/resources/overlay/standalone/configuration/apiman.properties
- distro/wildfly9/src/main/resources/overlay/standalone/configuration/apiman.properties
Timeout comment added in apiman.properties (under tomcat/wildfly distros).
> Timeout comment in apiman.properties

- .travis.yml
Also wasn't being applied properly due to Travis' own setup overriding it. See: https://github.com/travis-ci/travis-ci/issues/4613#issuecomment-135215956
Thanks @bertramn.
> ci(.travis) Fix typo in MAVEN_OPTS

- gateway/platforms/vertx3/vertx3-common/src/main/java/io/apiman/gateway/platforms/vertx3/common/AsyncInitialize.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/engine/VertxConfigDrivenEngineFactory.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/verticles/ApiVerticle.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/verticles/ApimanVerticleBase.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/verticles/ApimanVerticleWithEngine.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/verticles/HttpGatewayVerticle.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/verticles/HttpsGatewayVerticle.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/verticles/InitVerticle.java
*  Async initialisation features for better startup and error handling.
* Temporary measure of hard-coding ELEMENTS_TO_START.
> feat(gateway-vertx) Registry async initialisation features; better startup and error handling.

- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/common/config/VertxEngineConfig.java
Uses `StrSubstitutor`; first checks environment, then system properties.
Example:
```
Env = { "USERNAME": "admin" }
{ "username": "${USERNAME}" } =>  { "username" : "admin" }
```
Supports default values, recursion and escaping, see following link for more
details.
See: https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/text/StrSubstitutor.html
> feat(gateway-vertx) Var substitutions in config values.

- README.md
> Add build status badges to README.md

- test/common/src/main/java/io/apiman/test/common/echo/EchoServer.java
@EricWittmann Any objection to this?
> refactor(echo) Join main thread onto Echo Server instead of loop.

- gateway/engine/vertx-polling/src/main/java/io/apiman/gateway/engine/vertx/polling/URILoadingRegistry.java
Useful for rapid development and debugging.
> feat(polling-registry) Add URILoadingRegistry constructor for Servlet.

- gateway/engine/beans/src/main/java/io/apiman/gateway/engine/beans/exceptions/RequestAbortedException.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/ApiRequestExecutorImpl.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/EngineResultImpl.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/InMemoryCacheStoreComponent.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/io/IAbortable.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/policy/Chain.java
- gateway/engine/core/src/test/java/io/apiman/gateway/engine/impl/DefaultEngineFactoryTest.java
- gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/ESCacheStoreComponent.java
- gateway/engine/ispn/src/main/java/io/apiman/gateway/engine/ispn/InfinispanCacheStoreComponent.java
- gateway/engine/policies/src/main/java/io/apiman/gateway/engine/policies/caching/CacheConnectorInterceptor.java
- gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/GatewayServlet.java
- gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/HttpApiConnection.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/connector/HttpConnector.java
- test/policies/src/main/java/io/apiman/test/policies/PolicyTesterApiConnection.java
- test/policies/src/main/java/io/apiman/test/policies/PolicyTesterApiConnectionResponse.java
- Fix multiple errors being written on #abort in Servlet.
- Feature to allow exception to be passed into #abort.
> fix(gateway) Fix multiple errors being written on #abort in Servlet.

- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/api/auth/AuthFactory.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/api/auth/BasicAuth.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/api/auth/KeycloakOAuthFactory.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/api/auth/NoneAuth.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/common/config/VertxEngineConfig.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/verticles/ApiVerticle.java
- gateway/test/src/test/resources/vertx3/conf-api-to-file.json
- gateway/test/src/test/resources/vertx3/conf-es.json
- gateway/test/src/test/resources/vertx3/conf-file.json
- gateway/test/src/test/resources/vertx3/conf-mem.json
- gateway/test/src/test/resources/vertx3/conf-shared-global-data.json
Example of setup imitating servlet situation (BASIC then OAuth2 password flow):
```json
"auth": {
"type": "keycloak",
"config": {
"flowType": "PASSWORD",
"requiredRole": "realm:apipublisher",
"realm": "apiman",
"realm-public-key": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxyG61ohrfJQKNmDA/ePZtqZVpPXjwn3k3T+iWiTvMsxW2+WlnqIEmL5qZ09DMhBH9r50WZRO2gVoCb657Er9x0vfD6GNf/47XU2y33TX8axhP+hSwkv/VViaDlu4jQrfgPWz/FXMjWIZxg1xQS+nOBF2ScCRYWNQ/ZnUNnvrq8dGC2/AlyeYcgDUOdwlJuvgkGlF0QoVPQiRPurR3RwlG+BjL8JB3hbaAZhdJqwqApmGQbcpgLj2tODnlrZnEAp5cPPU/lgqCE1OOp78BAEiE91ZLPl/+D8qDHk+Maz0Io3bkeRZMXPpvtbL3qN+3GlF8Yz264HDSsTNrH+nd19tFQIDAQAB",
"auth-server-url": "http://localhost:8080/auth",
"ssl-required": "none",
"resource": "apiman-gateway-api",
"credentials": {
"secret": "217b725d-7790-47a7-a3fc-5cf31f92a8db" …
```
> feat(gateway-vertx) API auth: Add OAuth2, BASIC+Keycloak & improved BASIC

- gateway/engine/beans/src/test/java/io/apiman/gateway/engine/beans/util/CaseInsensitiveStringMultiMapTest.java
FYI @outofcoffee -- BTW, will endeavour to cherry-pick in your testing improvements, comments & annotations soon.
> test(gateway-engine) Paramaterise MultiMap tests to expose any collision issues.

- .gitignore
- distro/vertx/src/main/assembly/overlay.xml
- distro/vertx/src/main/resources/overlay/apiman-gateway.sh
- pom.xml
> build(distro-vertx) Add directory structure and change jar name slightly in distro.

- pom.xml
- test/common/pom.xml
- test/common/src/main/java/io/apiman/test/common/echo/EchoServerVertx.java
Probably should try to improve the performance of the XML output as it's presently awful due to StringWriter
> Vert.x edition of Echo servlet

- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/DefaultPolicyErrorWriter.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/connector/HttpConnector.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/http/HttpApiFactory.java
fix(platform-vertx): Ensure that Host header is not suppressed before the connector
Resolves APIMAN-1271
> fix(platform-vertx): Fix NPE where HTTP reasonCode or Exception messages are not set.

- gateway/platforms/vertx3/vertx3/pom.xml
- gateway/test/src/test/java/io/apiman/gateway/test/junit/vertx3/EsResetter.java
Also, try to placate Travis + ES test.
> build(gateway-vertx): Add 3scale registry.

- gateway/test/src/test/java/io/apiman/gateway/test/junit/vertx3/Vertx3GatewayTestServer.java
Try to avoid resetting before and after as this might cause issues.
> test(gateway-vertx) Attempt to fix ES Vertx3GatewayTestServer behaviour

- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/common/config/VertxEngineConfig.java
Thanks, @jcechace!
BTW, this is just a first step in improving this area. I'm going to overhaul it in an upcoming release.
> bug(platform-vertx) Ensure all leaf nodes have variable substitution performed.

- distro/eap7/pom.xml
- distro/tomcat8/pom.xml
- distro/wildfly10/pom.xml
- distro/wildfly10/src/main/docker/Dockerfile
- pom.xml
> build(distro-wildfly) Use DMP to produce WF10 docker image using latest code.

- .travis.yml
build(.travis) After successful master branch build deploy to DockerHub.
> build(.travis) Use build pipelines to avoid multiple docker deployments.

- manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/GatewayResourceImpl.java
Prevents the root cause for storage exceptions being swallowed by a failure to roll back the transaction.
When certain storage exceptions occur, such as a failure to log in to the database, apiman attempts to roll back the transaction. If the transaction rollback fails (or the transaction is not active), then another exception is thrown. Unfortunately, this second exception masks the first - so the original cause is lost, making debugging very difficult.
Ensures the original storage exception is thrown, optionally adding any rollback exceptions to the 'suppressed' list.
> Prevents the root cause for storage exceptions being swallowed

- gateway/engine/policies/src/main/java/io/apiman/gateway/engine/policies/TimeRestrictedAccessPolicy.java
fixed #664 
The **TimeRestrictedAccessPolicy** has another bug found, I will post later.
> Fixes TimeRestrictedAccessPolicy bounds checks (Fixes  #664)

- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/DefaultPluginRegistry.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/common/config/VertxEngineConfig.java
> fix(gateway-vertx): Ensure non-policy plugins load properly from Vert.x static config

- manager/ui/war/plugins/api-manager/html/directives/requestMethod.html
Add PATCH http verb to requestMethod using in authorization policy and Ignored Resources Policy
> [FIX #705]Add PATCH verb

- common/plugin/src/main/java/io/apiman/common/plugin/PluginClassLoader.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/DefaultPluginRegistry.java
Please include fix of plugin deployment bug also in docker images.
> APIMAN-1347, custom plugin loading during deployment problem fixed

- common/plugin/src/main/java/io/apiman/common/plugin/PluginClassLoader.java
Fixed [PR 720](https://github.com/apiman/apiman/pull/720) and removed duplicate code partially.
> Ensure Stream closing before renaming tmp file

- gateway/test/src/test/resources/log4j2-test.xml
- gateway/test/src/test/resources/test-plans/api/api-testPlan.xml
- test/common/src/main/resources/log4j2.xml
- test/common/src/test/resources/log4j.properties
- test/common/src/test/resources/log4j2-test.xml
Here is the PR for issue #744.
The missing log4j files are just copied from another apiman module.
> Add little delay to wait for elasticsearch and fix missing logging

- gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/ESRateLimiterComponent.java
We detected a bug in the ES-RateLimitingPolicy, causing the policy to fail under load.
I re-implemented the old logic with jest and did some testing on two gateways with j-meter.
I think the original FIXME was missed after migrating everything to jest.
@EricWittmann I hope this change will also make it into the upcoming release :)
Thanks @bekihm for the reviewing.
> Fix failing es rate limiting policy

- pom.xml
upgraded log4j version from 2.8.2 to 2.12.0
> Log4j version 2.12.0

- distro/vertx/src/main/resources/overlay/log4j2.xml
- pom.xml
> build(vertx): Update lmax disruptor to 3.4.2

- common/es/src/main/java/io/apiman/common/es/util/DefaultEsClientFactory.java
- distro/tomcat8/src/main/resources/overlay/conf/apiman.properties
- distro/wildfly11/src/main/resources/overlay/standalone/configuration/apiman.properties
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/DefaultPluginRegistry.java
- manager/api/war/src/main/java/io/apiman/manager/api/war/WarCdiFactory.java
Support options for self-signed certificates and host names not listed in certificates.
Correct handling of snapshot plugin reloading.
> Self-signed ES certificates, Snapshot plugin reloading

- gateway/api/rest/pom.xml
- manager/api/rest/pom.xml
> Fix #787: Update miredot license

- manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/OrganizationResourceImpl.java
Just a little improvement for API deletion if the download of the definition has failed before :)
> Improvement: Fix api deletion failure

- manager/test/api/src/test/resources/test-plan-data/apis/definitions/009_get-api-definition-wsdl.resttest
- manager/test/api/src/test/resources/test-plan-data/apis/definitions/018_get-api-definition-wsdl.resttest
- test/common/src/main/java/io/apiman/test/common/util/TestPlanRunner.java
I've fixed the tests related to the WSDL definition.
I'm sorry about that and I'll be careful of tests before I make a new pull request.
> fixing tests run for PR #835

- distro/data/src/main/resources/bootstrap/apiman-default-config.json
Revert apiman-default-config.json, replace Caching Policy with Caching Resource Policy
> Revert apiman-default-config.json

- manager/ui/war/plugins/api-manager/css/apiman.css
- manager/ui/war/plugins/api-manager/html/admin/admin-export.html
- manager/ui/war/plugins/api-manager/html/admin/admin-gateways.html
- manager/ui/war/plugins/api-manager/html/admin/admin-plugins.html
- manager/ui/war/plugins/api-manager/html/admin/admin-policyDefs.html
- manager/ui/war/plugins/api-manager/html/admin/admin-roles.html
- manager/ui/war/plugins/api-manager/html/dash.html
- manager/ui/war/plugins/api-manager/html/headers/amg.include
- manager/ui/war/plugins/api-manager/html/headers/community.include
- manager/ui/war/plugins/api-manager/html/sidebar/sidebar.include
- manager/ui/war/plugins/api-manager/ts/sidebar.ts
Added a fixed (very simple) sidebar navigation to improve UX
I've removed some tabs of administration pages (redundancy) and adjusted some alignments.
Change proposes are welcome ;)
Preview:
> Sidebar Navigation

- README.md
- common/es/src/main/java/io/apiman/common/es/util/EsIndexMapping.java
- tools/devenv/README.md
- tools/devenv/init-devenv.sh
- tools/server-all/pom.xml
I changed a little bit on how wildfly is unzipped and copied so that the scripts work if we update wildfly again.
Additionally fixed a little ES bug we accidentally committed.
> Update readme and fix scripts 

- gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/EsRegistry.java
Little logic fix that could cause problems with the gateway when using elasticsearch.
> Fix lookup clients for gateway

- .github/workflows/verify.yaml
- pom.xml
We updated the elasticsearch to a newer version.
> Update elasticsearch from 7.6.2 to 7.9.1

- .editorconfig
fix #925 
These are some common configurations that work in every IDE and can be changed in the future if needed.
> adding .editconfig

- .github/workflows/verify.yaml
> ci: build for Java 8, 11, and 15

- .github/workflows/verify.yaml
I think we have to add this step after each test run. But for now, this is just a test of how it looks/works.
> Test action-surefire-report plugin

- .github/workflows/verify.yaml
* Rework actions to remove some workarounds/hacks
* Ensure that test capture statistics are accurate
* Parallelise test suites, and hopefully clearer to understand
Fixes #1008
> ci: Parallelise integration test suite

- pom.xml
Very old version of ISPN, let's see if we can update it without major issue...
> build(deps): bump Infinispan from 8.1.9.Final to 8.2.12.Final

- distro/wildfly/src/main/resources/overlay/standalone/configuration/apiman.properties
- manager/api/micro/src/main/resources/micro-apiman.properties
- manager/ui/war/plugins/api-manager/html/headers/amg.include
> fix: Revert release script reinserting invalid rawgit URLs

- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/DefaultPolicyFailureWriter.java
> fix: Set PolicyFailure error code if '0' before write

- manager/ui/war/plugins/api-manager/css/apiman.css
- manager/ui/war/plugins/api-manager/html/api/api-def.html
- manager/ui/war/plugins/api-manager/html/modals/errorModal.html
- manager/ui/war/plugins/api-manager/ts/api/api-def.ts
- manager/ui/war/plugins/api-manager/ts/modals.ts
This is a refactoring of https://github.com/apiman/apiman/pull/951 originally contributed by @tevosouza.
I improved some small things and reverted a bit of the indentation and code styles.
@tevosouza Please feel free to comment and review my changes.
Thanks for the contribution @tevosouza and sorry for the long delay about this.
We will make sure that you will get the credits for this change even if I opened a different PR :)
@msavy and @EricWittmann please have also a look at this (if you have time).
> feat(ui): validation for api definitions & user-friendly error modal

- common/logging/jboss-logging/pom.xml
- common/logging/jboss-logging/src/main/java/io/apiman/common/logging/jboss/JbossLoggerFactory.java
- common/logging/jboss-logging/src/main/java/io/apiman/common/logging/jboss/JbossLoggerImpl.java
- common/logging/pom.xml
Useful to enhance logging support for Wildfly, EAP, Quarkus, etc.
Closes #1109
> feat(common-logging): add support for jboss-logging

- common/es/src/main/java/io/apiman/common/es/util/EsConstants.java
- common/es/src/main/java/io/apiman/common/es/util/EsUtils.java
- common/es/src/main/resources-filtered/io/apiman/common/es/util/apiman-embedded-elastic.properties
- common/es/src/main/resources-filtered/io/apiman/common/es/util/apiman-es.properties
- gateway/test/src/test/java/io/apiman/gateway/test/junit/servlet/ServletGatewayTestServer.java
- gateway/test/src/test/java/io/apiman/gateway/test/junit/vertx3/Vertx3GatewayEsServerFactory.java
- manager/test/api/src/main/java/io/apiman/manager/test/server/ManagerApiTestServer.java
- manager/test/api/src/test/java/io/apiman/manager/test/es/EsMetricsAccessorTest.java
- pom.xml
- test/common/pom.xml
- test/common/src/main/java/io/apiman/test/common/es/EsTestUtil.java
This should allow to switch between Amazon OpenDistro and the official elastic images for the test runs
> chore(es): allow optional use of Amazon open distro images

- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/DefaultPolicyErrorWriter.java
- gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/EsMetrics.java
- gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/EsRegistry.java
- gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/PollCachingEsRegistry.java
- gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/HttpApiConnection.java
> refactor: use new Apiman logging framework everywhere

- gateway/engine/core/src/main/java/io/apiman/gateway/engine/async/AsyncResultImpl.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/ConfigDrivenEngineFactory.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/DefaultJdbcComponent.java
- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/DefaultLdapSearchImpl.java
- gateway/engine/filesystem/src/main/java/io/apiman/gateway/engine/filesystem/LocalFileRegistry.java
- gateway/engine/influxdb/src/main/java/io/apiman/gateway/engine/influxdb/InfluxDb09Metrics.java
- gateway/engine/jdbc/src/main/java/io/apiman/gateway/engine/jdbc/JdbcMetrics.java
- gateway/engine/vertx-shareddata/src/main/java/io/apiman/gateway/engine/vertx/shareddata/SharedGlobalDataRegistry.java
- gateway/platforms/servlet/src/main/java/io/apiman/gateway/platforms/servlet/connectors/ssl/SSLSessionStrategyFactory.java
- gateway/platforms/vertx3/vertx3/src/main/java/io/apiman/gateway/platforms/vertx3/components/ldap/LdapSearchImpl.java
> refactor: use Apiman logger instead of System.err where possible

- distro/README.adoc
Add a little bit of information about the different apiman distros.
> docs: add information about the apiman distros

- distro/vertx/src/main/resources/overlay/log4j2.xml
> docs(distro-vertx): commented-out log4j2 JSON config layout examples

- distro/tomcat/src/main/resources/overlay/bin/setenv.bat
> feat(distro-tomcat): add setenv.bat for windows environments

- manager/api/beans/pom.xml
- manager/api/core/pom.xml
- manager/api/es/pom.xml
- manager/api/gateway/pom.xml
- manager/pom.xml
- manager/test/api/pom.xml
- test/common/pom.xml
> build(deps): removed duplicates of testcontainers/elasticsearch

- common/es/src/main/java/io/apiman/common/es/util/DefaultEsClientFactory.java
- common/es/src/main/java/io/apiman/common/es/util/EsConnectionPoller.java
> refactor(es): rework TLS configuration for Elasticsearch

- distro/tomcat/src/main/resources/overlay/log4j2/conf/log4j2-tomcat.xml
- distro/vertx/src/main/resources/overlay/log4j2.xml
Relates to https://github.com/apiman/apiman/issues/967
> Harmonize log4j2 configuration through the project

- manager/ui/war/plugins/api-manager/html/headers/community.include
> fix(ui): fix spelling error in community.include

- distro/tomcat/src/main/resources/overlay/conf/server.xml
- distro/wildfly/src/main/resources/overlay/standalone/configuration/standalone-apiman.xml
> chore(distro-wildfly): increase max-post-size to 256MB

- test/common/src/main/java/io/apiman/test/common/util/TestPlanRunner.java
> test(test-common): TestPlanRunner retry up to 4 times on IOException

- manager/ui/war/plugins/api-manager/html/dash.html
- manager/ui/war/plugins/api-manager/html/headers/community.include
> refactor(ui): add IDs to sidebar menu and dash-groups on dash page

- manager/ui/war/cypress/integration/Basic_Functionality.js
- manager/ui/war/cypress/support/commands.js
changed sidebar interaction from clicks to the corresponding mouse events
Additionally changed css selectors of sidebar elements to IDs
Cypress test works locally
> test(ui): fix sidebar interaction in cypress test 

- manager/api/rest/src/main/java/io/apiman/manager/api/rest/IDeveloperPortalResource.java
…to provide a complete API documentation
> fix(manager-api): add devportal endpoint into generated swagger file to provide a complete API documentation

- manager/api/rest-impl/src/main/java/io/apiman/manager/api/rest/impl/util/RestHelper.java
That helps to reduce the count of requests in the new Devportal
> fix(manager-api): add image to censored api object 

- manager/ui/war/plugins/api-manager/html/consumer/consumer-api.html
Fixes the broken API consumer page layout in V3
> fix(ui): api overview page

- manager/ui/war/package.json
- manager/ui/war/plugins/api-manager/css/apiman.css
- manager/ui/war/plugins/api-manager/ts/api/api-devportal.ts
- manager/ui/war/yarn.lock
> fix: change behaviour of markdown editor and fix css issues

- manager/ui/war/plugins/api-manager/html/api/api_entity.include
- manager/ui/war/plugins/api-manager/html/client/client_entity.include
- manager/ui/war/plugins/api-manager/html/plan/plan_entity.include
valid html5 requires closing tags on span elements
> fix(ui): modified status label restored by removing self-closing span

- manager/ui/war/plugins/api-manager/html/policyForms/time-restricted-access.include
- manager/ui/war/plugins/api-manager/ts/policies.ts
- manager/ui/war/src/main/resources/io/apiman/manager/ui/server/i18n/template_messages.properties
- fixing DateTime issues that where caused by previous library replacement of moment
- adding local time along utc time view in table
- changing some functions to anonymous functions to avoid unexpected behaviour
@msavy The same PR you already reviewed :)
> fix(ui): add local time to time-restricted-access-policy

- distro/data/src/main/resources/ddls/apiman_h2.ddl
- distro/data/src/main/resources/ddls/apiman_mssql15.ddl
- distro/data/src/main/resources/ddls/apiman_mysql8.ddl
- distro/data/src/main/resources/ddls/apiman_oracle19.ddl
- distro/data/src/main/resources/ddls/apiman_postgresql9.ddl
- manager/api/core/src/main/java/io/apiman/manager/api/core/config/ApiManagerConfig.java
- fix(manager-api): use correct system property for UI endpoint
- chore(distro): regenerate Apiman Manager DDL
> Regenerate Apiman 3.x DDL

- manager/ui/war/plugins/api-manager/html/headers/community.include
- manager/ui/war/plugins/api-manager/html/user/user-orgs.html
- manager/ui/war/plugins/api-manager/ts/dash.ts
- manager/ui/war/plugins/api-manager/ts/forms/new-org.ts
- manager/ui/war/plugins/api-manager/ts/lifecycle.ts
> fix(ui): org create button always hidden if not admin

- gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/EsMetrics.java
> fix(metrics): use user index rather than default

- manager/api/beans/src/main/java/io/apiman/manager/api/beans/idm/UserBean.java
- manager/api/beans/src/main/java/io/apiman/manager/api/beans/idm/UserDto.java
> fix(ui): add joinedOn field to UserDto

- parent/pom.xml
chore(deps): bump Vert.x from 3.9.8 to 3.9.13
chore(deps): bump Netty from 4.1.65.Final to 4.1.74.Final
> chore(deps): bump Vert.x and Netty

- gateway/platforms/war/src/main/java/io/apiman/gateway/platforms/war/WarEngineConfig.java
> fix(manager-api-war): handle comma-separated lists properly in `apiman.properties`

- common/es/src/main/java/io/apiman/common/es/util/AbstractClientFactory.java
Can be a race condition to create an ES index (such as apiman_metrics) which may cause secondary 
attempts to create the index to fail. We just need to ignore this as there's still no 
'create if not exist' in ES.
See: https://github.com/elastic/elasticsearch/issues/19862
Fixes: #2035
> fix(manager): work around ES index creation race condition

- distro/data/src/main/resources/bootstrap/default-policies.json
> refactor(distro-data): change policy names blacklist -> blocklist; whitelist -> allowlist

- manager/ui/war/plugins/api-manager/html/forms/edit-policy.html
Remove css classes to be consistent with "new-policy" view.
Closes: #2033
> fix(ui): fix display of policy edit view

- manager/ui/war/plugins/api-manager/html/modals/errorModal.html
- manager/ui/war/plugins/api-manager/ts/api/api-def.ts
- manager/ui/war/plugins/api-manager/ts/modals.ts
- manager/ui/war/plugins/api-manager/ts/rpc.ts
@msavy You already reviewed this one in our downstream fork.
> fix(ui): print error message in modal

- manager/ui/war/plugins/api-manager/html/api/api-devportal.html
- manager/ui/war/plugins/api-manager/html/api/api-plans.html
@msavy You already reviewed that one in our downstream fork
> fix(ui): remove warning in developer portal tab

- docs/modules/migration/pages/migrations.adoc
* Elasticsearch removal
* WildFly + Keycloak AIO distro removal
* Docker AIO removal
> docs(migration): document initial 3.x breaking changes

- manager/api/security/src/main/java/io/apiman/manager/api/security/impl/IndexedDiscoverabilities.java
- manager/api/security/src/test/java/io/apiman/manager/api/security/impl/IndexedDiscoverabilitiesCombinedTest.java
> fix(manager-api-security): plans added to discoverability index must inherit highest discoverability

- CHANGELOG.adoc
> docs(changelog): add changelog to repo

- parent/pom.xml
> chore(deps): bump Hibernate to 5.3.20.Final

- gateway/engine/policies/src/main/java/io/apiman/gateway/engine/policies/probe/ProbeRegistry.java
> fix(manager-api): register subtypes for deserializing policy probe response

- CHANGELOG.adoc
- portal/ui/src/app/app.module.ts
- portal/ui/src/app/components/account/account.component.html
- portal/ui/src/app/components/account/account.component.ts
- portal/ui/src/app/components/api-documentation-buttons/api-documentation-buttons.component.html
- portal/ui/src/app/components/api-documentation-buttons/api-documentation-buttons.component.ts
- portal/ui/src/app/components/swagger/swagger.component.html
- portal/ui/src/app/components/swagger/swagger.component.ts
- portal/ui/src/app/services/backend/backend.service.ts
- portal/ui/src/app/services/keycloak-helper/keycloak-helper.service.ts
- portal/ui/src/app/shared/components/img-or-icon-selector/img-or-icon-selector.component.html
- portal/ui/src/app/shared/components/img-or-icon-selector/img-or-icon-selector.component.scss
- portal/ui/src/app/shared/components/img-or-icon-selector/img-or-icon-selector.component.spec.ts
- portal/ui/src/app/shared/components/img-or-icon-selector/img-or-icon-selector.component.ts
- portal/ui/src/app/shared/shared.module.ts
- portal/ui/src/assets/i18n/de.json
- portal/ui/src/assets/i18n/en.json
Fixes a couple of problems regarding tokens and swagger-ui.
Originally authored by @BastianGem
> fix(swagger-ui): fixed data transfer to swagger component

- gateway/engine/core/src/main/java/io/apiman/gateway/engine/impl/ApiRequestExecutorImpl.java
> fix(gateway-engine): ensure that API is resolved before using it
